[<AutoOpen>]
module PureScript_Control_Monad_Gen

open System
open System.Collections.Generic

type Control_Monad_Gen_LL =
  | Control_Monad_Gen_Consusd_Ctor of obj * obj
  | Control_Monad_Gen_Nilusd_Ctor

let Control_Monad_Gen_lessThanOrEq  = (sharpurs_apply (box (Data_Ord_lessThanOrEq)) (box (Data_Ord_ordInt)))

let Control_Monad_Gen_sub  = (sharpurs_apply (box (Data_Ring_sub)) (box (Data_Ring_ringInt)))

let Control_Monad_Gen_compose  = (sharpurs_apply (box (Control_Semigroupoid_compose)) (box (Control_Semigroupoid_semigroupoidFn)))

let Control_Monad_Gen_un  = (sharpurs_apply (box (Data_Newtype_un)) (box (Prim_undefined)))

let Control_Monad_Gen_greaterThanOrEq  = (sharpurs_apply (box (Data_Ord_greaterThanOrEq)) (box (Data_Ord_ordNumber)))

let Control_Monad_Gen_sub1  = (sharpurs_apply (box (Data_Ring_sub)) (box (Data_Ring_ringNumber)))

let Control_Monad_Gen_alaF  = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Newtype_alaF)) (box (Prim_undefined))))) (box (Prim_undefined))))) (box (Prim_undefined))))) (box (Prim_undefined)))

let Control_Monad_Gen_monoidAdditive  = (sharpurs_apply (box (Data_Monoid_Additive_monoidAdditive)) (box (Data_Semiring_semiringNumber)))

let Control_Monad_Gen_Cons  = (fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Control_Monad_Gen_Consusd_Ctor(usd__arg1, usd__arg2)))))

let Control_Monad_Gen_Nil  = (box Control_Monad_Gen_Nilusd_Ctor)

let Control_Monad_Gen_FreqSemigroup  = (fun (x: obj) -> x)

let Control_Monad_Gen_unfoldable  = (fun (dictMonadRec: obj) -> (let tailRecM = (sharpurs_apply (box (Control_Monad_Rec_Class_tailRecM)) (box (dictMonadRec))) in (fun (dictMonadGen: obj) -> (let Monad0 = (sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> (dictMonadGen))))) (box (Prim_undefined))) in let pure_ = (sharpurs_apply (box (Control_Applicative_pure)) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> (Monad0))))) (box (Prim_undefined)))))) in let Bind1 = (sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> (Monad0))))) (box (Prim_undefined))) in let bind_ = (sharpurs_apply (box (Control_Bind_bind)) (box (Bind1))) in let map = (sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> (Bind1))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))) in let sized = (sharpurs_apply (box (Control_Monad_Gen_Class_sized)) (box (dictMonadGen))) in (fun (dictUnfoldable: obj) -> (let unfoldr = (sharpurs_apply (box (Data_Unfoldable_unfoldr)) (box (dictUnfoldable))) in (fun (gen: obj) -> (let unfold = (fun (v: obj) -> (match ((unbox (v))) with | Control_Monad_Gen_Nilusd_Ctor -> (box ((box Data_Maybe_Nothingusd_Ctor))) | Control_Monad_Gen_Consusd_Ctor(x, xs) -> (box ((box (Data_Maybe_Justusd_Ctor((box (Data_Tuple_Tupleusd_Ctor(x, xs)))))))))) in let loopGen = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(acc, n) when (unbox (sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_lessThanOrEq)) (box (n))))) (box ((box 0))))) -> (box ((sharpurs_apply (box (pure_)) (box ((box (Control_Monad_Rec_Class_Doneusd_Ctor(acc)))))))) | Data_Tuple_Tupleusd_Ctor(acc, n) when (unbox Data_Boolean_otherwise) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (bind_)) (box (gen))))) (box ((fun (x: obj) -> (sharpurs_apply (box (pure_)) (box ((box (Control_Monad_Rec_Class_Loopusd_Ctor((box (Data_Tuple_Tupleusd_Ctor((box (Control_Monad_Gen_Consusd_Ctor(x, acc))), (sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_sub)) (box (n))))) (box ((box 1))))))))))))))))))))) in (sharpurs_apply (box ((sharpurs_apply (box (map)) (box ((sharpurs_apply (box (unfoldr)) (box (unfold)))))))) (box ((sharpurs_apply (box (sized)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_compose)) (box ((sharpurs_apply (box (tailRecM)) (box (loopGen)))))))) (box ((fun (usd__arg1: obj) -> (box (Data_Tuple_Tupleusd_Ctor((box Control_Monad_Gen_Nilusd_Ctor), usd__arg1)))))))))))))))))))))

let Control_Monad_Gen_semigroupFreqSemigroup  = (sharpurs_apply (box (Data_Semigroup_Semigroupusd_Dict)) (box ((Map.add "append" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (f, g) -> (box ((sharpurs_apply (box (Control_Monad_Gen_FreqSemigroup)) (box ((fun (pos: obj) -> (let v2 = (sharpurs_apply (box (f)) (box (pos))) in (match ((unbox (v2))) with | Data_Tuple_Tupleusd_Ctor(Unbox(Data_Maybe_Justusd_Ctor(pos_prime)), _) -> (box ((sharpurs_apply (box (g)) (box (pos_prime))))) | result -> (box (result))))))))))))))) Map.empty))))

let Control_Monad_Gen_getFreqVal  = (fun (v: obj) -> (match ((unbox (v))) with | f -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_compose)) (box (Data_Tuple_snd))))) (box (f)))))))

let Control_Monad_Gen_fromIndex  = (fun (dictFoldable1: obj) -> (let foldMap1 = (sharpurs_apply (box ((sharpurs_apply (box (Data_Semigroup_Foldable_foldMap1)) (box (dictFoldable1))))) (box (Data_Semigroup_Last_semigroupLast))) in let foldr = (sharpurs_apply (box (Data_Foldable_foldr)) (box ((sharpurs_apply (box ((Map.find "Foldable0" (unbox<Map<string, obj>> (dictFoldable1))))) (box (Prim_undefined)))))) in (fun (i: obj) -> (fun (xs: obj) -> (let mutable go : obj = null in go <- (fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (_, Control_Monad_Gen_Consusd_Ctor(a, Unbox(Control_Monad_Gen_Nilusd_Ctor))) -> (box (a)) | (j, Control_Monad_Gen_Consusd_Ctor(a, _)) when (unbox (sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_lessThanOrEq)) (box (j))))) (box ((box 0))))) -> (box (a)) | (j, Control_Monad_Gen_Consusd_Ctor(_, as_)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (go)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_sub)) (box (j))))) (box ((box 1))))))))) (box (as_))))) | (_, Control_Monad_Gen_Nilusd_Ctor) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_un)) (box (Data_Semigroup_Last_Last))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (foldMap1)) (box (Data_Semigroup_Last_Last))))) (box (xs))))))))))); (sharpurs_apply (box ((sharpurs_apply (box (go)) (box (i))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (foldr)) (box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Control_Monad_Gen_Consusd_Ctor(usd__arg1, usd__arg2)))))))))) (box ((box Control_Monad_Gen_Nilusd_Ctor)))))) (box (xs)))))))))))

let Control_Monad_Gen_oneOf  = (fun (dictMonadGen: obj) -> (let bind_ = (sharpurs_apply (box (Control_Bind_bind)) (box ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> (dictMonadGen))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))) in let chooseInt = (sharpurs_apply (box (Control_Monad_Gen_Class_chooseInt)) (box (dictMonadGen))) in (fun (dictFoldable1: obj) -> (let length = (sharpurs_apply (box ((sharpurs_apply (box (Data_Foldable_length)) (box ((sharpurs_apply (box ((Map.find "Foldable0" (unbox<Map<string, obj>> (dictFoldable1))))) (box (Prim_undefined)))))))) (box (Data_Semiring_semiringInt))) in let fromIndex1 = (sharpurs_apply (box (Control_Monad_Gen_fromIndex)) (box (dictFoldable1))) in (fun (xs: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (bind_)) (box ((sharpurs_apply (box ((sharpurs_apply (box (chooseInt)) (box ((box 0)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_sub)) (box ((sharpurs_apply (box (length)) (box (xs)))))))) (box ((box 1)))))))))))) (box ((fun (n: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (fromIndex1)) (box (n))))) (box (xs))))))))))))

let Control_Monad_Gen_freqSemigroup  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(weight, x) -> (box ((sharpurs_apply (box (Control_Monad_Gen_FreqSemigroup)) (box ((fun (pos: obj) -> (match ((unbox ((sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_greaterThanOrEq)) (box (pos))))) (box (weight)))))) with | LitBool true () -> (box ((box (Data_Tuple_Tupleusd_Ctor((box (Data_Maybe_Justusd_Ctor((sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_sub1)) (box (pos))))) (box (weight)))))), x))))) | _ -> (box ((box (Data_Tuple_Tupleusd_Ctor((box Data_Maybe_Nothingusd_Ctor), x))))))))))))))

let Control_Monad_Gen_frequency  = (fun (dictMonadGen: obj) -> (let bind_ = (sharpurs_apply (box (Control_Bind_bind)) (box ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> (dictMonadGen))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))) in let chooseFloat = (sharpurs_apply (box (Control_Monad_Gen_Class_chooseFloat)) (box (dictMonadGen))) in (fun (dictFoldable1: obj) -> (let foldMap = (sharpurs_apply (box ((sharpurs_apply (box (Data_Foldable_foldMap)) (box ((sharpurs_apply (box ((Map.find "Foldable0" (unbox<Map<string, obj>> (dictFoldable1))))) (box (Prim_undefined)))))))) (box (Control_Monad_Gen_monoidAdditive))) in let foldMap1 = (sharpurs_apply (box ((sharpurs_apply (box (Data_Semigroup_Foldable_foldMap1)) (box (dictFoldable1))))) (box (Control_Monad_Gen_semigroupFreqSemigroup))) in (fun (xs: obj) -> (let total = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_alaF)) (box (Data_Monoid_Additive_Additive))))) (box (foldMap))))) (box (Data_Tuple_fst))))) (box (xs))) in (sharpurs_apply (box ((sharpurs_apply (box (bind_)) (box ((sharpurs_apply (box ((sharpurs_apply (box (chooseFloat)) (box ((box 0.0)))))) (box (total)))))))) (box ((sharpurs_apply (box (Control_Monad_Gen_getFreqVal)) (box ((sharpurs_apply (box ((sharpurs_apply (box (foldMap1)) (box (Control_Monad_Gen_freqSemigroup))))) (box (xs)))))))))))))))

let Control_Monad_Gen_filtered  = (fun (dictMonadRec: obj) -> (let tailRecM = (sharpurs_apply (box (Control_Monad_Rec_Class_tailRecM)) (box (dictMonadRec))) in (fun (dictMonadGen: obj) -> (let mapFlipped = (sharpurs_apply (box (Data_Functor_mapFlipped)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> (dictMonadGen))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))) in (fun (gen: obj) -> (let go = (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (mapFlipped)) (box (gen))))) (box ((fun (a: obj) -> (match ((unbox (a))) with | Data_Maybe_Nothingusd_Ctor -> (box ((box (Control_Monad_Rec_Class_Loopusd_Ctor(Data_Unit_unit))))) | Data_Maybe_Justusd_Ctor(a_prime) -> (box ((box (Control_Monad_Rec_Class_Doneusd_Ctor(a_prime))))))))))) in (sharpurs_apply (box ((sharpurs_apply (box (tailRecM)) (box (go))))) (box (Data_Unit_unit)))))))))

let Control_Monad_Gen_suchThat  = (fun (dictMonadRec: obj) -> (let filtered1 = (sharpurs_apply (box (Control_Monad_Gen_filtered)) (box (dictMonadRec))) in (fun (dictMonadGen: obj) -> (let filtered2 = (sharpurs_apply (box (filtered1)) (box (dictMonadGen))) in let mapFlipped = (sharpurs_apply (box (Data_Functor_mapFlipped)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> (dictMonadGen))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))) in (fun (gen: obj) -> (fun (pred: obj) -> (sharpurs_apply (box (filtered2)) (box ((sharpurs_apply (box ((sharpurs_apply (box (mapFlipped)) (box (gen))))) (box ((fun (a: obj) -> (match ((unbox ((sharpurs_apply (box (pred)) (box (a)))))) with | LitBool true () -> (box ((box (Data_Maybe_Justusd_Ctor(a))))) | _ -> (box ((box Data_Maybe_Nothingusd_Ctor)))))))))))))))))

let Control_Monad_Gen_elements  = (fun (dictMonadGen: obj) -> (let Monad0 = (sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> (dictMonadGen))))) (box (Prim_undefined))) in let bind_ = (sharpurs_apply (box (Control_Bind_bind)) (box ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> (Monad0))))) (box (Prim_undefined)))))) in let chooseInt = (sharpurs_apply (box (Control_Monad_Gen_Class_chooseInt)) (box (dictMonadGen))) in let pure_ = (sharpurs_apply (box (Control_Applicative_pure)) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> (Monad0))))) (box (Prim_undefined)))))) in (fun (dictFoldable1: obj) -> (let length = (sharpurs_apply (box ((sharpurs_apply (box (Data_Foldable_length)) (box ((sharpurs_apply (box ((Map.find "Foldable0" (unbox<Map<string, obj>> (dictFoldable1))))) (box (Prim_undefined)))))))) (box (Data_Semiring_semiringInt))) in let fromIndex1 = (sharpurs_apply (box (Control_Monad_Gen_fromIndex)) (box (dictFoldable1))) in (fun (xs: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (bind_)) (box ((sharpurs_apply (box ((sharpurs_apply (box (chooseInt)) (box ((box 0)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_sub)) (box ((sharpurs_apply (box (length)) (box (xs)))))))) (box ((box 1)))))))))))) (box ((fun (n: obj) -> (sharpurs_apply (box (pure_)) (box ((sharpurs_apply (box ((sharpurs_apply (box (fromIndex1)) (box (n))))) (box (xs)))))))))))))))

let Control_Monad_Gen_choose  = (fun (dictMonadGen: obj) -> (let bind_ = (sharpurs_apply (box (Control_Bind_bind)) (box ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> (dictMonadGen))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))) in let chooseBool = (sharpurs_apply (box (Control_Monad_Gen_Class_chooseBool)) (box (dictMonadGen))) in (fun (genA: obj) -> (fun (genB: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (bind_)) (box (chooseBool))))) (box ((fun (v: obj) -> (match ((unbox (v))) with | LitBool true () -> (box (genA)) | _ -> (box (genB)))))))))))
