[<AutoOpen>]
module PureScript_Control_Monad_Gen_Common

open System
open System.Collections.Generic

let Control_Monad_Gen_Common_compose  = (sharpurs_apply (box (Control_Semigroupoid_compose)) (box (Control_Semigroupoid_semigroupoidFn)))

let Control_Monad_Gen_Common_max  = (sharpurs_apply (box (Data_Ord_max)) (box (Data_Ord_ordInt)))

let Control_Monad_Gen_Common_sub  = (sharpurs_apply (box (Data_Ring_sub)) (box (Data_Ring_ringInt)))

let Control_Monad_Gen_Common_lessThan  = (sharpurs_apply (box (Data_Ord_lessThan)) (box (Data_Ord_ordNumber)))

let Control_Monad_Gen_Common_genTuple  = (fun (dictApply: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Control_Apply_lift2)) (box (dictApply))))) (box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2)))))))))

let Control_Monad_Gen_Common_genNonEmpty  = (fun (dictMonadRec: obj) -> (let unfoldable = (sharpurs_apply (box (Control_Monad_Gen_unfoldable)) (box (dictMonadRec))) in (fun (dictMonadGen: obj) -> (let Apply0 = (sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> (dictMonadGen))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined))) in let apply = (sharpurs_apply (box (Control_Apply_apply)) (box (Apply0))) in let map = (sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (Apply0))))) (box (Prim_undefined)))))) in let resize = (sharpurs_apply (box (Control_Monad_Gen_Class_resize)) (box (dictMonadGen))) in let unfoldable1 = (sharpurs_apply (box (unfoldable)) (box (dictMonadGen))) in (fun (dictUnfoldable: obj) -> (let unfoldable2 = (sharpurs_apply (box (unfoldable1)) (box (dictUnfoldable))) in (fun (gen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (apply)) (box ((sharpurs_apply (box ((sharpurs_apply (box (map)) (box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2)))))))))) (box (gen)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (resize)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_Common_compose)) (box ((sharpurs_apply (box (Control_Monad_Gen_Common_max)) (box ((box 0))))))))) (box ((fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_Common_sub)) (box (v))))) (box ((box 1))))))))))))) (box ((sharpurs_apply (box (unfoldable2)) (box (gen))))))))))))))))

let Control_Monad_Gen_Common_genMaybe_prime  = (fun (dictMonadGen: obj) -> (let Monad0 = (sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> (dictMonadGen))))) (box (Prim_undefined))) in let Bind1 = (sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> (Monad0))))) (box (Prim_undefined))) in let bind_ = (sharpurs_apply (box (Control_Bind_bind)) (box (Bind1))) in let chooseFloat = (sharpurs_apply (box (Control_Monad_Gen_Class_chooseFloat)) (box (dictMonadGen))) in let map = (sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> (Bind1))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))) in let pure_ = (sharpurs_apply (box (Control_Applicative_pure)) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> (Monad0))))) (box (Prim_undefined)))))) in (fun (bias: obj) -> (fun (gen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (bind_)) (box ((sharpurs_apply (box ((sharpurs_apply (box (chooseFloat)) (box ((box 0.0)))))) (box ((box 1.0))))))))) (box ((fun (n: obj) -> (match ((unbox ((sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_Common_lessThan)) (box (n))))) (box (bias)))))) with | LitBool true () -> (box ((sharpurs_apply (box ((sharpurs_apply (box (map)) (box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1))))))))) (box (gen))))) | _ -> (box ((sharpurs_apply (box (pure_)) (box ((box Data_Maybe_Nothingusd_Ctor)))))))))))))))

let Control_Monad_Gen_Common_genMaybe  = (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_Common_genMaybe_prime)) (box (dictMonadGen))))) (box ((box 0.75)))))

let Control_Monad_Gen_Common_genIdentity  = (fun (dictFunctor: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_map)) (box (dictFunctor))))) (box (Data_Identity_Identity))))

let Control_Monad_Gen_Common_genEither_prime  = (fun (dictMonadGen: obj) -> (let Bind1 = (sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> (dictMonadGen))))) (box (Prim_undefined)))))))) (box (Prim_undefined))) in let bind_ = (sharpurs_apply (box (Control_Bind_bind)) (box (Bind1))) in let chooseFloat = (sharpurs_apply (box (Control_Monad_Gen_Class_chooseFloat)) (box (dictMonadGen))) in let map = (sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> (Bind1))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))) in (fun (bias: obj) -> (fun (genA: obj) -> (fun (genB: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (bind_)) (box ((sharpurs_apply (box ((sharpurs_apply (box (chooseFloat)) (box ((box 0.0)))))) (box ((box 1.0))))))))) (box ((fun (n: obj) -> (match ((unbox ((sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_Common_lessThan)) (box (n))))) (box (bias)))))) with | LitBool true () -> (box ((sharpurs_apply (box ((sharpurs_apply (box (map)) (box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1))))))))) (box (genA))))) | _ -> (box ((sharpurs_apply (box ((sharpurs_apply (box (map)) (box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1))))))))) (box (genB)))))))))))))))

let Control_Monad_Gen_Common_genEither  = (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_Common_genEither_prime)) (box (dictMonadGen))))) (box ((box 0.5)))))
