[<AutoOpen>]
module PureScript_Control_Monad_Rec_Class

open System
open System.Collections.Generic

type Control_Monad_Rec_Class_Step =
  | Control_Monad_Rec_Class_Loopusd_Ctor of obj
  | Control_Monad_Rec_Class_Doneusd_Ctor of obj

let Control_Monad_Rec_Class_compose  = (sharpurs_apply (box (Control_Semigroupoid_compose)) (box (Control_Semigroupoid_semigroupoidFn)))

let Control_Monad_Rec_Class_bind  = (sharpurs_apply (box (Control_Bind_bind)) (box (Effect_bindEffect)))

let Control_Monad_Rec_Class_bindFlipped  = (sharpurs_apply (box (Control_Bind_bindFlipped)) (box (Effect_bindEffect)))

let Control_Monad_Rec_Class_discard  = (sharpurs_apply (box ((sharpurs_apply (box (Control_Bind_discard)) (box (Control_Bind_discardUnit))))) (box (Effect_bindEffect)))

let Control_Monad_Rec_Class_pure  = (sharpurs_apply (box (Control_Applicative_pure)) (box (Effect_applicativeEffect)))

let Control_Monad_Rec_Class_map  = (sharpurs_apply (box (Data_Functor_map)) (box (Effect_functorEffect)))

let Control_Monad_Rec_Class_Loop  = (fun (usd__arg1: obj) -> (box (Control_Monad_Rec_Class_Loopusd_Ctor(usd__arg1))))

let Control_Monad_Rec_Class_Done  = (fun (usd__arg1: obj) -> (box (Control_Monad_Rec_Class_Doneusd_Ctor(usd__arg1))))

let Control_Monad_Rec_Class_MonadRecusd_Dict  = (fun (x: obj) -> x)

let Control_Monad_Rec_Class_tailRecM  = (fun (dict: obj) -> (match ((unbox (dict))) with | v -> (box ((Map.find "tailRecM" (unbox<Map<string, obj>> (v)))))))

let Control_Monad_Rec_Class_tailRecM2  = (fun (dictMonadRec: obj) -> (let tailRecM1 = (sharpurs_apply (box (Control_Monad_Rec_Class_tailRecM)) (box (dictMonadRec))) in (fun (f: obj) -> (fun (a: obj) -> (fun (b: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (tailRecM1)) (box ((fun (o: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (f)) (box ((Map.find "a" (unbox<Map<string, obj>> (o)))))))) (box ((Map.find "b" (unbox<Map<string, obj>> (o)))))))))))) (box ((Map.add "a" (box (a)) (Map.add "b" (box (b)) Map.empty))))))))))

let Control_Monad_Rec_Class_tailRecM3  = (fun (dictMonadRec: obj) -> (let tailRecM1 = (sharpurs_apply (box (Control_Monad_Rec_Class_tailRecM)) (box (dictMonadRec))) in (fun (f: obj) -> (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (tailRecM1)) (box ((fun (o: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (f)) (box ((Map.find "a" (unbox<Map<string, obj>> (o)))))))) (box ((Map.find "b" (unbox<Map<string, obj>> (o)))))))) (box ((Map.find "c" (unbox<Map<string, obj>> (o)))))))))))) (box ((Map.add "a" (box (a)) (Map.add "b" (box (b)) (Map.add "c" (box (c)) Map.empty))))))))))))

let Control_Monad_Rec_Class_untilJust  = (fun (dictMonadRec: obj) -> (let tailRecM1 = (sharpurs_apply (box (Control_Monad_Rec_Class_tailRecM)) (box (dictMonadRec))) in let mapFlipped = (sharpurs_apply (box (Data_Functor_mapFlipped)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> (dictMonadRec))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))) in (fun (m: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (tailRecM1)) (box ((fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (mapFlipped)) (box (m))))) (box ((fun (v1: obj) -> (match ((unbox (v1))) with | Data_Maybe_Nothingusd_Ctor -> (box ((box (Control_Monad_Rec_Class_Loopusd_Ctor(Data_Unit_unit))))) | Data_Maybe_Justusd_Ctor(x) -> (box ((box (Control_Monad_Rec_Class_Doneusd_Ctor(x)))))))))))))))) (box (Data_Unit_unit))))))

let Control_Monad_Rec_Class_whileJust  = (fun (dictMonoid: obj) -> (let append = (sharpurs_apply (box (Data_Semigroup_append)) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> (dictMonoid))))) (box (Prim_undefined)))))) in let mempty = (sharpurs_apply (box (Data_Monoid_mempty)) (box (dictMonoid))) in (fun (dictMonadRec: obj) -> (let tailRecM1 = (sharpurs_apply (box (Control_Monad_Rec_Class_tailRecM)) (box (dictMonadRec))) in let mapFlipped = (sharpurs_apply (box (Data_Functor_mapFlipped)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> (dictMonadRec))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))) in (fun (m: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (tailRecM1)) (box ((fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (mapFlipped)) (box (m))))) (box ((fun (v1: obj) -> (match ((unbox (v1))) with | Data_Maybe_Nothingusd_Ctor -> (box ((box (Control_Monad_Rec_Class_Doneusd_Ctor(v))))) | Data_Maybe_Justusd_Ctor(x) -> (box ((box (Control_Monad_Rec_Class_Loopusd_Ctor((sharpurs_apply (box ((sharpurs_apply (box (append)) (box (v))))) (box (x))))))))))))))))))) (box (mempty))))))))

let Control_Monad_Rec_Class_tailRec  = (fun (f: obj) -> (let mutable go : obj = null in go <- (fun (v: obj) -> (match ((unbox (v))) with | Control_Monad_Rec_Class_Loopusd_Ctor(a) -> (box ((sharpurs_apply (box (go)) (box ((sharpurs_apply (box (f)) (box (a)))))))) | Control_Monad_Rec_Class_Doneusd_Ctor(b) -> (box (b)))); (sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Rec_Class_compose)) (box (go))))) (box (f)))))

let Control_Monad_Rec_Class_tailRec2  = (fun (f: obj) -> (fun (a: obj) -> (fun (b: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Rec_Class_tailRec)) (box ((fun (o: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (f)) (box ((Map.find "a" (unbox<Map<string, obj>> (o)))))))) (box ((Map.find "b" (unbox<Map<string, obj>> (o)))))))))))) (box ((Map.add "a" (box (a)) (Map.add "b" (box (b)) Map.empty))))))))

let Control_Monad_Rec_Class_tailRec3  = (fun (f: obj) -> (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Rec_Class_tailRec)) (box ((fun (o: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (f)) (box ((Map.find "a" (unbox<Map<string, obj>> (o)))))))) (box ((Map.find "b" (unbox<Map<string, obj>> (o)))))))) (box ((Map.find "c" (unbox<Map<string, obj>> (o)))))))))))) (box ((Map.add "a" (box (a)) (Map.add "b" (box (b)) (Map.add "c" (box (c)) Map.empty))))))))))

let Control_Monad_Rec_Class_monadRecMaybe  = (sharpurs_apply (box (Control_Monad_Rec_Class_MonadRecusd_Dict)) (box ((Map.add "tailRecM" (box ((fun (f: obj) -> (fun (a0: obj) -> (let g = (fun (v: obj) -> (match ((unbox (v))) with | Data_Maybe_Nothingusd_Ctor -> (box ((box (Control_Monad_Rec_Class_Doneusd_Ctor((box Data_Maybe_Nothingusd_Ctor)))))) | Data_Maybe_Justusd_Ctor(Unbox(Control_Monad_Rec_Class_Loopusd_Ctor(a))) -> (box ((box (Control_Monad_Rec_Class_Loopusd_Ctor((sharpurs_apply (box (f)) (box (a)))))))) | Data_Maybe_Justusd_Ctor(Unbox(Control_Monad_Rec_Class_Doneusd_Ctor(b))) -> (box ((box (Control_Monad_Rec_Class_Doneusd_Ctor((box (Data_Maybe_Justusd_Ctor(b)))))))))) in (sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Rec_Class_tailRec)) (box (g))))) (box ((sharpurs_apply (box (f)) (box (a0))))))))))) (Map.add "Monad0" (box ((fun (_: obj) -> Data_Maybe_monadMaybe))) Map.empty)))))

let Control_Monad_Rec_Class_monadRecIdentity  = (sharpurs_apply (box (Control_Monad_Rec_Class_MonadRecusd_Dict)) (box ((Map.add "tailRecM" (box ((fun (f: obj) -> (let runIdentity = (fun (v: obj) -> (match ((unbox (v))) with | x -> (box (x)))) in (sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Rec_Class_compose)) (box (Data_Identity_Identity))))) (box ((sharpurs_apply (box (Control_Monad_Rec_Class_tailRec)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Rec_Class_compose)) (box (runIdentity))))) (box (f))))))))))))) (Map.add "Monad0" (box ((fun (_: obj) -> Data_Identity_monadIdentity))) Map.empty)))))

let Control_Monad_Rec_Class_monadRecFunction  = (sharpurs_apply (box (Control_Monad_Rec_Class_MonadRecusd_Dict)) (box ((Map.add "tailRecM" (box ((fun (f: obj) -> (fun (a0: obj) -> (fun (e: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Rec_Class_tailRec)) (box ((fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (f)) (box (a))))) (box (e))))))))) (box (a0)))))))) (Map.add "Monad0" (box ((fun (_: obj) -> Control_Monad_monadFn))) Map.empty)))))

let Control_Monad_Rec_Class_monadRecEither  = (sharpurs_apply (box (Control_Monad_Rec_Class_MonadRecusd_Dict)) (box ((Map.add "tailRecM" (box ((fun (f: obj) -> (fun (a0: obj) -> (let g = (fun (v: obj) -> (match ((unbox (v))) with | Data_Either_Leftusd_Ctor(e) -> (box ((box (Control_Monad_Rec_Class_Doneusd_Ctor((box (Data_Either_Leftusd_Ctor(e)))))))) | Data_Either_Rightusd_Ctor(Unbox(Control_Monad_Rec_Class_Loopusd_Ctor(a))) -> (box ((box (Control_Monad_Rec_Class_Loopusd_Ctor((sharpurs_apply (box (f)) (box (a)))))))) | Data_Either_Rightusd_Ctor(Unbox(Control_Monad_Rec_Class_Doneusd_Ctor(b))) -> (box ((box (Control_Monad_Rec_Class_Doneusd_Ctor((box (Data_Either_Rightusd_Ctor(b)))))))))) in (sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Rec_Class_tailRec)) (box (g))))) (box ((sharpurs_apply (box (f)) (box (a0))))))))))) (Map.add "Monad0" (box ((fun (_: obj) -> Data_Either_monadEither))) Map.empty)))))

let Control_Monad_Rec_Class_monadRecEffect  = (sharpurs_apply (box (Control_Monad_Rec_Class_MonadRecusd_Dict)) (box ((Map.add "tailRecM" (box ((fun (f: obj) -> (fun (a: obj) -> (let fromDone = (sharpurs_apply (box (Partial_Unsafe_unsafePartial)) (box ((fun (_: obj) -> (fun (v: obj) -> (sharpurs_apply (box ((fun (_: obj) -> (match ((unbox (v))) with | Control_Monad_Rec_Class_Doneusd_Ctor(b) -> (box (b)))))) (box (Prim_undefined)))))))) in (sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Rec_Class_bind)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Rec_Class_bindFlipped)) (box (Effect_Ref_new))))) (box ((sharpurs_apply (box (f)) (box (a))))))))))) (box ((fun (r: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Rec_Class_discard)) (box ((sharpurs_apply (box (Effect_untilE)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Rec_Class_bind)) (box ((sharpurs_apply (box (Effect_Ref_read)) (box (r)))))))) (box ((fun (v: obj) -> (match ((unbox (v))) with | Control_Monad_Rec_Class_Loopusd_Ctor(a_prime) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Rec_Class_bind)) (box ((sharpurs_apply (box (f)) (box (a_prime)))))))) (box ((fun (e: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Rec_Class_bind)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Effect_Ref_write)) (box (e))))) (box (r)))))))) (box ((fun (_: obj) -> (sharpurs_apply (box (Control_Monad_Rec_Class_pure)) (box ((box false)))))))))))))) | Control_Monad_Rec_Class_Doneusd_Ctor(_) -> (box ((sharpurs_apply (box (Control_Monad_Rec_Class_pure)) (box ((box true))))))))))))))))))) (box ((fun (_: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Rec_Class_map)) (box (fromDone))))) (box ((sharpurs_apply (box (Effect_Ref_read)) (box (r))))))))))))))))))) (Map.add "Monad0" (box ((fun (_: obj) -> Effect_monadEffect))) Map.empty)))))

let Control_Monad_Rec_Class_loop3  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (box (Control_Monad_Rec_Class_Loopusd_Ctor((Map.add "a" (box (a)) (Map.add "b" (box (b)) (Map.add "c" (box (c)) Map.empty)))))))))

let Control_Monad_Rec_Class_loop2  = (fun (a: obj) -> (fun (b: obj) -> (box (Control_Monad_Rec_Class_Loopusd_Ctor((Map.add "a" (box (a)) (Map.add "b" (box (b)) Map.empty)))))))

let Control_Monad_Rec_Class_functorStep  = (sharpurs_apply (box (Data_Functor_Functorusd_Dict)) (box ((Map.add "map" (box ((fun (f: obj) -> (fun (m: obj) -> (match ((unbox (m))) with | Control_Monad_Rec_Class_Loopusd_Ctor(v) -> (box ((box (Control_Monad_Rec_Class_Loopusd_Ctor(v))))) | Control_Monad_Rec_Class_Doneusd_Ctor(v) -> (box ((box (Control_Monad_Rec_Class_Doneusd_Ctor((sharpurs_apply (box (f)) (box (v))))))))))))) Map.empty))))

let Control_Monad_Rec_Class_forever  = (fun (dictMonadRec: obj) -> (let tailRecM1 = (sharpurs_apply (box (Control_Monad_Rec_Class_tailRecM)) (box (dictMonadRec))) in let voidRight = (sharpurs_apply (box (Data_Functor_voidRight)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> (dictMonadRec))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))) in (fun (ma: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (tailRecM1)) (box ((fun (u: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (voidRight)) (box ((box (Control_Monad_Rec_Class_Loopusd_Ctor(u)))))))) (box (ma))))))))) (box (Data_Unit_unit))))))

let Control_Monad_Rec_Class_bifunctorStep  = (sharpurs_apply (box (Data_Bifunctor_Bifunctorusd_Dict)) (box ((Map.add "bimap" (box ((fun (v: obj) -> (fun (v1: obj) -> (fun (v2: obj) -> (match (((unbox (v)), (unbox (v1)), (unbox (v2)))) with | (f, _, Control_Monad_Rec_Class_Loopusd_Ctor(a)) -> (box ((box (Control_Monad_Rec_Class_Loopusd_Ctor((sharpurs_apply (box (f)) (box (a)))))))) | (_, g, Control_Monad_Rec_Class_Doneusd_Ctor(b)) -> (box ((box (Control_Monad_Rec_Class_Doneusd_Ctor((sharpurs_apply (box (g)) (box (b)))))))))))))) Map.empty))))
