[<AutoOpen>]
module PureScript_Data_Semiring_Generic

open System
open System.Collections.Generic

let Data_Semiring_Generic_GenericSemiringusd_Dict  = (fun (x: obj) -> x)

let Data_Semiring_Generic_genericZero_prime  = (fun (dict: obj) -> (match ((unbox (dict))) with | v -> (box ((Map.find "genericZero'" (unbox<Map<string, obj>> (v)))))))

let Data_Semiring_Generic_genericZero  = (fun (dictGeneric: obj) -> (let to_ = (sharpurs_apply (box (Data_Generic_Rep_to)) (box (dictGeneric))) in (fun (dictGenericSemiring: obj) -> (sharpurs_apply (box (to_)) (box ((sharpurs_apply (box (Data_Semiring_Generic_genericZero_prime)) (box (dictGenericSemiring)))))))))

let Data_Semiring_Generic_genericSemiringNoArguments  = (sharpurs_apply (box (Data_Semiring_Generic_GenericSemiringusd_Dict)) (box ((Map.add "genericAdd'" (box ((fun (v: obj) -> (fun (v1: obj) -> (box Data_Generic_Rep_NoArgumentsusd_Ctor))))) (Map.add "genericZero'" (box ((box Data_Generic_Rep_NoArgumentsusd_Ctor))) (Map.add "genericMul'" (box ((fun (v: obj) -> (fun (v1: obj) -> (box Data_Generic_Rep_NoArgumentsusd_Ctor))))) (Map.add "genericOne'" (box ((box Data_Generic_Rep_NoArgumentsusd_Ctor))) Map.empty)))))))

let Data_Semiring_Generic_genericSemiringArgument  = (fun (dictSemiring: obj) -> (let add = (sharpurs_apply (box (Data_Semiring_add)) (box (dictSemiring))) in let mul = (sharpurs_apply (box (Data_Semiring_mul)) (box (dictSemiring))) in (sharpurs_apply (box (Data_Semiring_Generic_GenericSemiringusd_Dict)) (box ((Map.add "genericAdd'" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (x, y) -> (box ((sharpurs_apply (box (Data_Generic_Rep_Argument)) (box ((sharpurs_apply (box ((sharpurs_apply (box (add)) (box (x))))) (box (y))))))))))))) (Map.add "genericZero'" (box ((sharpurs_apply (box (Data_Generic_Rep_Argument)) (box ((sharpurs_apply (box (Data_Semiring_zero)) (box (dictSemiring)))))))) (Map.add "genericMul'" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (x, y) -> (box ((sharpurs_apply (box (Data_Generic_Rep_Argument)) (box ((sharpurs_apply (box ((sharpurs_apply (box (mul)) (box (x))))) (box (y))))))))))))) (Map.add "genericOne'" (box ((sharpurs_apply (box (Data_Generic_Rep_Argument)) (box ((sharpurs_apply (box (Data_Semiring_one)) (box (dictSemiring)))))))) Map.empty)))))))))

let Data_Semiring_Generic_genericOne_prime  = (fun (dict: obj) -> (match ((unbox (dict))) with | v -> (box ((Map.find "genericOne'" (unbox<Map<string, obj>> (v)))))))

let Data_Semiring_Generic_genericOne  = (fun (dictGeneric: obj) -> (let to_ = (sharpurs_apply (box (Data_Generic_Rep_to)) (box (dictGeneric))) in (fun (dictGenericSemiring: obj) -> (sharpurs_apply (box (to_)) (box ((sharpurs_apply (box (Data_Semiring_Generic_genericOne_prime)) (box (dictGenericSemiring)))))))))

let Data_Semiring_Generic_genericMul_prime  = (fun (dict: obj) -> (match ((unbox (dict))) with | v -> (box ((Map.find "genericMul'" (unbox<Map<string, obj>> (v)))))))

let Data_Semiring_Generic_genericMul  = (fun (dictGeneric: obj) -> (let to_ = (sharpurs_apply (box (Data_Generic_Rep_to)) (box (dictGeneric))) in let from = (sharpurs_apply (box (Data_Generic_Rep_from)) (box (dictGeneric))) in (fun (dictGenericSemiring: obj) -> (let genericMul_prime1 = (sharpurs_apply (box (Data_Semiring_Generic_genericMul_prime)) (box (dictGenericSemiring))) in (fun (x: obj) -> (fun (y: obj) -> (sharpurs_apply (box (to_)) (box ((sharpurs_apply (box ((sharpurs_apply (box (genericMul_prime1)) (box ((sharpurs_apply (box (from)) (box (x)))))))) (box ((sharpurs_apply (box (from)) (box (y)))))))))))))))

let Data_Semiring_Generic_genericAdd_prime  = (fun (dict: obj) -> (match ((unbox (dict))) with | v -> (box ((Map.find "genericAdd'" (unbox<Map<string, obj>> (v)))))))

let Data_Semiring_Generic_genericSemiringConstructor  = (fun (dictGenericSemiring: obj) -> (let genericAdd_prime1 = (sharpurs_apply (box (Data_Semiring_Generic_genericAdd_prime)) (box (dictGenericSemiring))) in let genericMul_prime1 = (sharpurs_apply (box (Data_Semiring_Generic_genericMul_prime)) (box (dictGenericSemiring))) in (sharpurs_apply (box (Data_Semiring_Generic_GenericSemiringusd_Dict)) (box ((Map.add "genericAdd'" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (a1, a2) -> (box ((sharpurs_apply (box (Data_Generic_Rep_Constructor)) (box ((sharpurs_apply (box ((sharpurs_apply (box (genericAdd_prime1)) (box (a1))))) (box (a2))))))))))))) (Map.add "genericZero'" (box ((sharpurs_apply (box (Data_Generic_Rep_Constructor)) (box ((sharpurs_apply (box (Data_Semiring_Generic_genericZero_prime)) (box (dictGenericSemiring)))))))) (Map.add "genericMul'" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (a1, a2) -> (box ((sharpurs_apply (box (Data_Generic_Rep_Constructor)) (box ((sharpurs_apply (box ((sharpurs_apply (box (genericMul_prime1)) (box (a1))))) (box (a2))))))))))))) (Map.add "genericOne'" (box ((sharpurs_apply (box (Data_Generic_Rep_Constructor)) (box ((sharpurs_apply (box (Data_Semiring_Generic_genericOne_prime)) (box (dictGenericSemiring)))))))) Map.empty)))))))))

let Data_Semiring_Generic_genericSemiringProduct  = (fun (dictGenericSemiring: obj) -> (let genericAdd_prime1 = (sharpurs_apply (box (Data_Semiring_Generic_genericAdd_prime)) (box (dictGenericSemiring))) in let genericZero_prime1 = (sharpurs_apply (box (Data_Semiring_Generic_genericZero_prime)) (box (dictGenericSemiring))) in let genericMul_prime1 = (sharpurs_apply (box (Data_Semiring_Generic_genericMul_prime)) (box (dictGenericSemiring))) in let genericOne_prime1 = (sharpurs_apply (box (Data_Semiring_Generic_genericOne_prime)) (box (dictGenericSemiring))) in (fun (dictGenericSemiring1: obj) -> (let genericAdd_prime2 = (sharpurs_apply (box (Data_Semiring_Generic_genericAdd_prime)) (box (dictGenericSemiring1))) in let genericMul_prime2 = (sharpurs_apply (box (Data_Semiring_Generic_genericMul_prime)) (box (dictGenericSemiring1))) in (sharpurs_apply (box (Data_Semiring_Generic_GenericSemiringusd_Dict)) (box ((Map.add "genericAdd'" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (Data_Generic_Rep_Productusd_Ctor(a1, b1), Data_Generic_Rep_Productusd_Ctor(a2, b2)) -> (box ((box (Data_Generic_Rep_Productusd_Ctor((sharpurs_apply (box ((sharpurs_apply (box (genericAdd_prime1)) (box (a1))))) (box (a2))), (sharpurs_apply (box ((sharpurs_apply (box (genericAdd_prime2)) (box (b1))))) (box (b2))))))))))))) (Map.add "genericZero'" (box ((box (Data_Generic_Rep_Productusd_Ctor(genericZero_prime1, (sharpurs_apply (box (Data_Semiring_Generic_genericZero_prime)) (box (dictGenericSemiring1)))))))) (Map.add "genericMul'" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (Data_Generic_Rep_Productusd_Ctor(a1, b1), Data_Generic_Rep_Productusd_Ctor(a2, b2)) -> (box ((box (Data_Generic_Rep_Productusd_Ctor((sharpurs_apply (box ((sharpurs_apply (box (genericMul_prime1)) (box (a1))))) (box (a2))), (sharpurs_apply (box ((sharpurs_apply (box (genericMul_prime2)) (box (b1))))) (box (b2))))))))))))) (Map.add "genericOne'" (box ((box (Data_Generic_Rep_Productusd_Ctor(genericOne_prime1, (sharpurs_apply (box (Data_Semiring_Generic_genericOne_prime)) (box (dictGenericSemiring1)))))))) Map.empty)))))))))))

let Data_Semiring_Generic_genericAdd  = (fun (dictGeneric: obj) -> (let to_ = (sharpurs_apply (box (Data_Generic_Rep_to)) (box (dictGeneric))) in let from = (sharpurs_apply (box (Data_Generic_Rep_from)) (box (dictGeneric))) in (fun (dictGenericSemiring: obj) -> (let genericAdd_prime1 = (sharpurs_apply (box (Data_Semiring_Generic_genericAdd_prime)) (box (dictGenericSemiring))) in (fun (x: obj) -> (fun (y: obj) -> (sharpurs_apply (box (to_)) (box ((sharpurs_apply (box ((sharpurs_apply (box (genericAdd_prime1)) (box ((sharpurs_apply (box (from)) (box (x)))))))) (box ((sharpurs_apply (box (from)) (box (y)))))))))))))))
