[<AutoOpen>]
module PureScript_Data_Profunctor_Star

open System
open System.Collections.Generic

let Data_Profunctor_Star_composeFlipped  = (sharpurs_apply (box (Control_Semigroupoid_composeFlipped)) (box (Control_Semigroupoid_semigroupoidFn)))

let Data_Profunctor_Star_compose  = (sharpurs_apply (box (Control_Semigroupoid_compose)) (box (Control_Semigroupoid_semigroupoidFn)))

let Data_Profunctor_Star_Star  = (fun (x: obj) -> x)

let Data_Profunctor_Star_semigroupoidStar  = (fun (dictBind: obj) -> (let bind_ = (sharpurs_apply (box (Control_Bind_bind)) (box (dictBind))) in (sharpurs_apply (box (Control_Semigroupoid_Semigroupoidusd_Dict)) (box ((Map.add "compose" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (f, g) -> (box ((sharpurs_apply (box (Data_Profunctor_Star_Star)) (box ((fun (x: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (bind_)) (box ((sharpurs_apply (box (g)) (box (x)))))))) (box (f)))))))))))))) Map.empty))))))

let Data_Profunctor_Star_profunctorStar  = (fun (dictFunctor: obj) -> (let map = (sharpurs_apply (box (Data_Functor_map)) (box (dictFunctor))) in (sharpurs_apply (box (Data_Profunctor_Profunctorusd_Dict)) (box ((Map.add "dimap" (box ((fun (f: obj) -> (fun (g: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (g)), (unbox (v)))) with | (f1, g1, ft) -> (box ((sharpurs_apply (box (Data_Profunctor_Star_Star)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Profunctor_Star_composeFlipped)) (box (f1))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Profunctor_Star_composeFlipped)) (box (ft))))) (box ((sharpurs_apply (box (map)) (box (g1)))))))))))))))))))) Map.empty))))))

let Data_Profunctor_Star_strongStar  = (fun (dictFunctor: obj) -> (let map = (sharpurs_apply (box (Data_Functor_map)) (box (dictFunctor))) in let profunctorStar1 = (sharpurs_apply (box (Data_Profunctor_Star_profunctorStar)) (box (dictFunctor))) in (sharpurs_apply (box (Data_Profunctor_Strong_Strongusd_Dict)) (box ((Map.add "first" (box ((fun (v: obj) -> (match ((unbox (v))) with | f -> (box ((sharpurs_apply (box (Data_Profunctor_Star_Star)) (box ((fun (v1: obj) -> (match ((unbox (v1))) with | Data_Tuple_Tupleusd_Ctor(s, x) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (map)) (box ((fun (v2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(v2, x))))))))) (box ((sharpurs_apply (box (f)) (box (s))))))))))))))))))) (Map.add "second" (box ((fun (v: obj) -> (match ((unbox (v))) with | f -> (box ((sharpurs_apply (box (Data_Profunctor_Star_Star)) (box ((fun (v1: obj) -> (match ((unbox (v1))) with | Data_Tuple_Tupleusd_Ctor(x, s) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (map)) (box ((fun (usd__arg1: obj) -> (box (Data_Tuple_Tupleusd_Ctor(x, usd__arg1))))))))) (box ((sharpurs_apply (box (f)) (box (s))))))))))))))))))) (Map.add "Profunctor0" (box ((fun (_: obj) -> profunctorStar1))) Map.empty))))))))

let Data_Profunctor_Star_newtypeStar  = (sharpurs_apply (box (Data_Newtype_Newtypeusd_Dict)) (box ((Map.add "Coercible0" (box ((fun (_: obj) -> Prim_undefined))) Map.empty))))

let Data_Profunctor_Star_invariantStar  = (fun (dictInvariant: obj) -> (let imap = (sharpurs_apply (box (Data_Functor_Invariant_imap)) (box (dictInvariant))) in (sharpurs_apply (box (Data_Functor_Invariant_Invariantusd_Dict)) (box ((Map.add "imap" (box ((fun (f: obj) -> (fun (g: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (g)), (unbox (v)))) with | (f1, g1, h) -> (box ((sharpurs_apply (box (Data_Profunctor_Star_Star)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Profunctor_Star_compose)) (box ((sharpurs_apply (box ((sharpurs_apply (box (imap)) (box (f1))))) (box (g1)))))))) (box (h)))))))))))))) Map.empty))))))

let Data_Profunctor_Star_hoistStar  = (fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, g) -> (box ((sharpurs_apply (box (Data_Profunctor_Star_Star)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Profunctor_Star_compose)) (box (f1))))) (box (g)))))))))))

let Data_Profunctor_Star_functorStar  = (fun (dictFunctor: obj) -> (let map = (sharpurs_apply (box (Data_Functor_map)) (box (dictFunctor))) in (sharpurs_apply (box (Data_Functor_Functorusd_Dict)) (box ((Map.add "map" (box ((fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, g) -> (box ((sharpurs_apply (box (Data_Profunctor_Star_Star)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Profunctor_Star_compose)) (box ((sharpurs_apply (box (map)) (box (f1)))))))) (box (g))))))))))))) Map.empty))))))

let rec Data_Profunctor_Star_distributiveStar  = (fun (dictDistributive: obj) -> (let collect = (sharpurs_apply (box (Data_Distributive_collect)) (box (dictDistributive))) in let functorStar1 = (sharpurs_apply (box (Data_Profunctor_Star_functorStar)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (dictDistributive))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Distributive_Distributiveusd_Dict)) (box ((Map.add "distribute" (box ((fun (dictFunctor: obj) -> (let collect1 = (sharpurs_apply (box (collect)) (box (dictFunctor))) in (fun (f: obj) -> (sharpurs_apply (box (Data_Profunctor_Star_Star)) (box ((fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (collect1)) (box ((fun (v: obj) -> (match ((unbox (v))) with | g -> (box ((sharpurs_apply (box (g)) (box (a)))))))))))) (box (f)))))))))))) (Map.add "collect" (box ((fun (dictFunctor: obj) -> (let map = (sharpurs_apply (box (Data_Functor_map)) (box (dictFunctor))) in (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Profunctor_Star_compose)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Distributive_distribute)) (box ((sharpurs_apply (box (Data_Profunctor_Star_distributiveStar)) (box (dictDistributive)))))))) (box (dictFunctor)))))))) (box ((sharpurs_apply (box (map)) (box (f))))))))))) (Map.add "Functor0" (box ((fun (_: obj) -> functorStar1))) Map.empty))))))))

let Data_Profunctor_Star_closedStar  = (fun (dictDistributive: obj) -> (let distribute = (sharpurs_apply (box ((sharpurs_apply (box (Data_Distributive_distribute)) (box (dictDistributive))))) (box (Data_Functor_functorFn))) in let profunctorStar1 = (sharpurs_apply (box (Data_Profunctor_Star_profunctorStar)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (dictDistributive))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Profunctor_Closed_Closedusd_Dict)) (box ((Map.add "closed" (box ((fun (v: obj) -> (match ((unbox (v))) with | f -> (box ((sharpurs_apply (box (Data_Profunctor_Star_Star)) (box ((fun (g: obj) -> (sharpurs_apply (box (distribute)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Profunctor_Star_compose)) (box (f))))) (box (g)))))))))))))))) (Map.add "Profunctor0" (box ((fun (_: obj) -> profunctorStar1))) Map.empty)))))))

let Data_Profunctor_Star_choiceStar  = (fun (dictApplicative: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> (dictApplicative))))) (box (Prim_undefined)))))))) (box (Prim_undefined))) in let map = (sharpurs_apply (box (Data_Functor_map)) (box (Functor0))) in let pure_ = (sharpurs_apply (box (Control_Applicative_pure)) (box (dictApplicative))) in let profunctorStar1 = (sharpurs_apply (box (Data_Profunctor_Star_profunctorStar)) (box (Functor0))) in (sharpurs_apply (box (Data_Profunctor_Choice_Choiceusd_Dict)) (box ((Map.add "left" (box ((fun (v: obj) -> (match ((unbox (v))) with | f -> (box ((sharpurs_apply (box (Data_Profunctor_Star_Star)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Either_either)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Profunctor_Star_compose)) (box ((sharpurs_apply (box (map)) (box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1)))))))))))) (box (f)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Profunctor_Star_compose)) (box (pure_))))) (box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1))))))))))))))))))) (Map.add "right" (box ((fun (v: obj) -> (match ((unbox (v))) with | f -> (box ((sharpurs_apply (box (Data_Profunctor_Star_Star)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Either_either)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Profunctor_Star_compose)) (box (pure_))))) (box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1)))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Profunctor_Star_compose)) (box ((sharpurs_apply (box (map)) (box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))))))) (box (f))))))))))))))) (Map.add "Profunctor0" (box ((fun (_: obj) -> profunctorStar1))) Map.empty))))))))

let Data_Profunctor_Star_categoryStar  = (fun (dictMonad: obj) -> (let semigroupoidStar1 = (sharpurs_apply (box (Data_Profunctor_Star_semigroupoidStar)) (box ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> (dictMonad))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Control_Category_Categoryusd_Dict)) (box ((Map.add "identity" (box ((sharpurs_apply (box (Data_Profunctor_Star_Star)) (box ((sharpurs_apply (box (Control_Applicative_pure)) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> (dictMonad))))) (box (Prim_undefined))))))))))) (Map.add "Semigroupoid0" (box ((fun (_: obj) -> semigroupoidStar1))) Map.empty)))))))

let Data_Profunctor_Star_applyStar  = (fun (dictApply: obj) -> (let apply = (sharpurs_apply (box (Control_Apply_apply)) (box (dictApply))) in let functorStar1 = (sharpurs_apply (box (Data_Profunctor_Star_functorStar)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (dictApply))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Control_Apply_Applyusd_Dict)) (box ((Map.add "apply" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (f, g) -> (box ((sharpurs_apply (box (Data_Profunctor_Star_Star)) (box ((fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (apply)) (box ((sharpurs_apply (box (f)) (box (a)))))))) (box ((sharpurs_apply (box (g)) (box (a))))))))))))))))) (Map.add "Functor0" (box ((fun (_: obj) -> functorStar1))) Map.empty)))))))

let Data_Profunctor_Star_bindStar  = (fun (dictBind: obj) -> (let bind_ = (sharpurs_apply (box (Control_Bind_bind)) (box (dictBind))) in let applyStar1 = (sharpurs_apply (box (Data_Profunctor_Star_applyStar)) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> (dictBind))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Control_Bind_Bindusd_Dict)) (box ((Map.add "bind" (box ((fun (v: obj) -> (fun (f: obj) -> (match (((unbox (v)), (unbox (f)))) with | (m, f1) -> (box ((sharpurs_apply (box (Data_Profunctor_Star_Star)) (box ((fun (x: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (bind_)) (box ((sharpurs_apply (box (m)) (box (x)))))))) (box ((fun (a: obj) -> (let v1 = (sharpurs_apply (box (f1)) (box (a))) in (match ((unbox (v1))) with | g -> (box ((sharpurs_apply (box (g)) (box (x)))))))))))))))))))))) (Map.add "Apply0" (box ((fun (_: obj) -> applyStar1))) Map.empty)))))))

let Data_Profunctor_Star_applicativeStar  = (fun (dictApplicative: obj) -> (let pure_ = (sharpurs_apply (box (Control_Applicative_pure)) (box (dictApplicative))) in let applyStar1 = (sharpurs_apply (box (Data_Profunctor_Star_applyStar)) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> (dictApplicative))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Control_Applicative_Applicativeusd_Dict)) (box ((Map.add "pure" (box ((fun (a: obj) -> (sharpurs_apply (box (Data_Profunctor_Star_Star)) (box ((fun (v: obj) -> (sharpurs_apply (box (pure_)) (box (a)))))))))) (Map.add "Apply0" (box ((fun (_: obj) -> applyStar1))) Map.empty)))))))

let Data_Profunctor_Star_monadStar  = (fun (dictMonad: obj) -> (let applicativeStar1 = (sharpurs_apply (box (Data_Profunctor_Star_applicativeStar)) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> (dictMonad))))) (box (Prim_undefined)))))) in let bindStar1 = (sharpurs_apply (box (Data_Profunctor_Star_bindStar)) (box ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> (dictMonad))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Control_Monad_Monadusd_Dict)) (box ((Map.add "Applicative0" (box ((fun (_: obj) -> applicativeStar1))) (Map.add "Bind1" (box ((fun (_: obj) -> bindStar1))) Map.empty)))))))

let Data_Profunctor_Star_altStar  = (fun (dictAlt: obj) -> (let alt = (sharpurs_apply (box (Control_Alt_alt)) (box (dictAlt))) in let functorStar1 = (sharpurs_apply (box (Data_Profunctor_Star_functorStar)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (dictAlt))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Control_Alt_Altusd_Dict)) (box ((Map.add "alt" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (f, g) -> (box ((sharpurs_apply (box (Data_Profunctor_Star_Star)) (box ((fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (alt)) (box ((sharpurs_apply (box (f)) (box (a)))))))) (box ((sharpurs_apply (box (g)) (box (a))))))))))))))))) (Map.add "Functor0" (box ((fun (_: obj) -> functorStar1))) Map.empty)))))))

let Data_Profunctor_Star_plusStar  = (fun (dictPlus: obj) -> (let empty = (sharpurs_apply (box (Control_Plus_empty)) (box (dictPlus))) in let altStar1 = (sharpurs_apply (box (Data_Profunctor_Star_altStar)) (box ((sharpurs_apply (box ((Map.find "Alt0" (unbox<Map<string, obj>> (dictPlus))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Control_Plus_Plususd_Dict)) (box ((Map.add "empty" (box ((sharpurs_apply (box (Data_Profunctor_Star_Star)) (box ((fun (v: obj) -> empty)))))) (Map.add "Alt0" (box ((fun (_: obj) -> altStar1))) Map.empty)))))))

let Data_Profunctor_Star_alternativeStar  = (fun (dictAlternative: obj) -> (let applicativeStar1 = (sharpurs_apply (box (Data_Profunctor_Star_applicativeStar)) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> (dictAlternative))))) (box (Prim_undefined)))))) in let plusStar1 = (sharpurs_apply (box (Data_Profunctor_Star_plusStar)) (box ((sharpurs_apply (box ((Map.find "Plus1" (unbox<Map<string, obj>> (dictAlternative))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Control_Alternative_Alternativeusd_Dict)) (box ((Map.add "Applicative0" (box ((fun (_: obj) -> applicativeStar1))) (Map.add "Plus1" (box ((fun (_: obj) -> plusStar1))) Map.empty)))))))

let Data_Profunctor_Star_monadPlusStar  = (fun (dictMonadPlus: obj) -> (let monadStar1 = (sharpurs_apply (box (Data_Profunctor_Star_monadStar)) (box ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> (dictMonadPlus))))) (box (Prim_undefined)))))) in let alternativeStar1 = (sharpurs_apply (box (Data_Profunctor_Star_alternativeStar)) (box ((sharpurs_apply (box ((Map.find "Alternative1" (unbox<Map<string, obj>> (dictMonadPlus))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Control_MonadPlus_MonadPlususd_Dict)) (box ((Map.add "Monad0" (box ((fun (_: obj) -> monadStar1))) (Map.add "Alternative1" (box ((fun (_: obj) -> alternativeStar1))) Map.empty)))))))
