[<AutoOpen>]
module PureScript_Data_Bifoldable

open System
open System.Collections.Generic

let Data_Bifoldable_compose  = (sharpurs_apply (box (Control_Semigroupoid_compose)) (box (Control_Semigroupoid_semigroupoidFn)))

let Data_Bifoldable_identity  = (sharpurs_apply (box (Control_Category_identity)) (box (Control_Category_categoryFn)))

let Data_Bifoldable_unwrap  = (sharpurs_apply (box (Data_Newtype_unwrap)) (box (Prim_undefined)))

let Data_Bifoldable_monoidEndo  = (sharpurs_apply (box (Data_Monoid_Endo_monoidEndo)) (box (Control_Category_categoryFn)))

let Data_Bifoldable_monoidDual  = (sharpurs_apply (box (Data_Monoid_Dual_monoidDual)) (box (Data_Bifoldable_monoidEndo)))

let Data_Bifoldable_Bifoldableusd_Dict  = (fun (x: obj) -> x)

let Data_Bifoldable_bifoldr  = (fun (dict: obj) -> (match ((unbox (dict))) with | v -> (box ((Map.find "bifoldr" (unbox<Map<string, obj>> (v)))))))

let Data_Bifoldable_bitraverse_  = (fun (dictBifoldable: obj) -> (let bifoldr1 = (sharpurs_apply (box (Data_Bifoldable_bifoldr)) (box (dictBifoldable))) in (fun (dictApplicative: obj) -> (let applySecond = (sharpurs_apply (box (Control_Apply_applySecond)) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> (dictApplicative))))) (box (Prim_undefined)))))) in let pure_ = (sharpurs_apply (box (Control_Applicative_pure)) (box (dictApplicative))) in (fun (f: obj) -> (fun (g: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (bifoldr1)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_compose)) (box (applySecond))))) (box (f)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_compose)) (box (applySecond))))) (box (g)))))))) (box ((sharpurs_apply (box (pure_)) (box (Data_Unit_unit))))))))))))

let Data_Bifoldable_bifor_  = (fun (dictBifoldable: obj) -> (let bitraverse_1 = (sharpurs_apply (box (Data_Bifoldable_bitraverse_)) (box (dictBifoldable))) in (fun (dictApplicative: obj) -> (let bitraverse_2 = (sharpurs_apply (box (bitraverse_1)) (box (dictApplicative))) in (fun (t: obj) -> (fun (f: obj) -> (fun (g: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (bitraverse_2)) (box (f))))) (box (g))))) (box (t))))))))))

let Data_Bifoldable_bisequence_  = (fun (dictBifoldable: obj) -> (let bitraverse_1 = (sharpurs_apply (box (Data_Bifoldable_bitraverse_)) (box (dictBifoldable))) in (fun (dictApplicative: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (bitraverse_1)) (box (dictApplicative))))) (box (Data_Bifoldable_identity))))) (box (Data_Bifoldable_identity))))))

let Data_Bifoldable_bifoldl  = (fun (dict: obj) -> (match ((unbox (dict))) with | v -> (box ((Map.find "bifoldl" (unbox<Map<string, obj>> (v)))))))

let Data_Bifoldable_bifoldableTuple  = (sharpurs_apply (box (Data_Bifoldable_Bifoldableusd_Dict)) (box ((Map.add "bifoldMap" (box ((fun (dictMonoid: obj) -> (let append = (sharpurs_apply (box (Data_Semigroup_append)) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> (dictMonoid))))) (box (Prim_undefined)))))) in (fun (f: obj) -> (fun (g: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (g)), (unbox (v)))) with | (f1, g1, Data_Tuple_Tupleusd_Ctor(a, b)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (append)) (box ((sharpurs_apply (box (f1)) (box (a)))))))) (box ((sharpurs_apply (box (g1)) (box (b)))))))))))))))) (Map.add "bifoldr" (box ((fun (f: obj) -> (fun (g: obj) -> (fun (z: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (g)), (unbox (z)), (unbox (v)))) with | (f1, g1, z1, Data_Tuple_Tupleusd_Ctor(a, b)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (f1)) (box (a))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (g1)) (box (b))))) (box (z1))))))))))))))) (Map.add "bifoldl" (box ((fun (f: obj) -> (fun (g: obj) -> (fun (z: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (g)), (unbox (z)), (unbox (v)))) with | (f1, g1, z1, Data_Tuple_Tupleusd_Ctor(a, b)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (g1)) (box ((sharpurs_apply (box ((sharpurs_apply (box (f1)) (box (z1))))) (box (a)))))))) (box (b)))))))))))) Map.empty))))))

let Data_Bifoldable_bifoldableJoker  = (fun (dictFoldable: obj) -> (let foldr = (sharpurs_apply (box (Data_Foldable_foldr)) (box (dictFoldable))) in let foldl = (sharpurs_apply (box (Data_Foldable_foldl)) (box (dictFoldable))) in let foldMap = (sharpurs_apply (box (Data_Foldable_foldMap)) (box (dictFoldable))) in (sharpurs_apply (box (Data_Bifoldable_Bifoldableusd_Dict)) (box ((Map.add "bifoldr" (box ((fun (v: obj) -> (fun (r: obj) -> (fun (u: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (r)), (unbox (u)), (unbox (v1)))) with | (_, r1, u1, f) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (foldr)) (box (r1))))) (box (u1))))) (box (f)))))))))))) (Map.add "bifoldl" (box ((fun (v: obj) -> (fun (r: obj) -> (fun (u: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (r)), (unbox (u)), (unbox (v1)))) with | (_, r1, u1, f) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (foldl)) (box (r1))))) (box (u1))))) (box (f)))))))))))) (Map.add "bifoldMap" (box ((fun (dictMonoid: obj) -> (let foldMap1 = (sharpurs_apply (box (foldMap)) (box (dictMonoid))) in (fun (v: obj) -> (fun (r: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (r)), (unbox (v1)))) with | (_, r1, f) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (foldMap1)) (box (r1))))) (box (f))))))))))))) Map.empty))))))))

let Data_Bifoldable_bifoldableEither  = (sharpurs_apply (box (Data_Bifoldable_Bifoldableusd_Dict)) (box ((Map.add "bifoldr" (box ((fun (v: obj) -> (fun (v1: obj) -> (fun (v2: obj) -> (fun (v3: obj) -> (match (((unbox (v)), (unbox (v1)), (unbox (v2)), (unbox (v3)))) with | (f, _, z, Data_Either_Leftusd_Ctor(a)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (f)) (box (a))))) (box (z))))) | (_, g, z, Data_Either_Rightusd_Ctor(b)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (g)) (box (b))))) (box (z)))))))))))) (Map.add "bifoldl" (box ((fun (v: obj) -> (fun (v1: obj) -> (fun (v2: obj) -> (fun (v3: obj) -> (match (((unbox (v)), (unbox (v1)), (unbox (v2)), (unbox (v3)))) with | (f, _, z, Data_Either_Leftusd_Ctor(a)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (f)) (box (z))))) (box (a))))) | (_, g, z, Data_Either_Rightusd_Ctor(b)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (g)) (box (z))))) (box (b)))))))))))) (Map.add "bifoldMap" (box ((fun (dictMonoid: obj) -> (fun (v: obj) -> (fun (v1: obj) -> (fun (v2: obj) -> (match (((unbox (v)), (unbox (v1)), (unbox (v2)))) with | (f, _, Data_Either_Leftusd_Ctor(a)) -> (box ((sharpurs_apply (box (f)) (box (a))))) | (_, g, Data_Either_Rightusd_Ctor(b)) -> (box ((sharpurs_apply (box (g)) (box (b)))))))))))) Map.empty))))))

let Data_Bifoldable_bifoldableConst  = (sharpurs_apply (box (Data_Bifoldable_Bifoldableusd_Dict)) (box ((Map.add "bifoldr" (box ((fun (f: obj) -> (fun (v: obj) -> (fun (z: obj) -> (fun (v1: obj) -> (match (((unbox (f)), (unbox (v)), (unbox (z)), (unbox (v1)))) with | (f1, _, z1, a) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (f1)) (box (a))))) (box (z1)))))))))))) (Map.add "bifoldl" (box ((fun (f: obj) -> (fun (v: obj) -> (fun (z: obj) -> (fun (v1: obj) -> (match (((unbox (f)), (unbox (v)), (unbox (z)), (unbox (v1)))) with | (f1, _, z1, a) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (f1)) (box (z1))))) (box (a)))))))))))) (Map.add "bifoldMap" (box ((fun (dictMonoid: obj) -> (fun (f: obj) -> (fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (f)), (unbox (v)), (unbox (v1)))) with | (f1, _, a) -> (box ((sharpurs_apply (box (f1)) (box (a)))))))))))) Map.empty))))))

let Data_Bifoldable_bifoldableClown  = (fun (dictFoldable: obj) -> (let foldr = (sharpurs_apply (box (Data_Foldable_foldr)) (box (dictFoldable))) in let foldl = (sharpurs_apply (box (Data_Foldable_foldl)) (box (dictFoldable))) in let foldMap = (sharpurs_apply (box (Data_Foldable_foldMap)) (box (dictFoldable))) in (sharpurs_apply (box (Data_Bifoldable_Bifoldableusd_Dict)) (box ((Map.add "bifoldr" (box ((fun (l: obj) -> (fun (v: obj) -> (fun (u: obj) -> (fun (v1: obj) -> (match (((unbox (l)), (unbox (v)), (unbox (u)), (unbox (v1)))) with | (l1, _, u1, f) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (foldr)) (box (l1))))) (box (u1))))) (box (f)))))))))))) (Map.add "bifoldl" (box ((fun (l: obj) -> (fun (v: obj) -> (fun (u: obj) -> (fun (v1: obj) -> (match (((unbox (l)), (unbox (v)), (unbox (u)), (unbox (v1)))) with | (l1, _, u1, f) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (foldl)) (box (l1))))) (box (u1))))) (box (f)))))))))))) (Map.add "bifoldMap" (box ((fun (dictMonoid: obj) -> (let foldMap1 = (sharpurs_apply (box (foldMap)) (box (dictMonoid))) in (fun (l: obj) -> (fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (l)), (unbox (v)), (unbox (v1)))) with | (l1, _, f) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (foldMap1)) (box (l1))))) (box (f))))))))))))) Map.empty))))))))

let Data_Bifoldable_bifoldMapDefaultR  = (fun (dictBifoldable: obj) -> (let bifoldr1 = (sharpurs_apply (box (Data_Bifoldable_bifoldr)) (box (dictBifoldable))) in (fun (dictMonoid: obj) -> (let append = (sharpurs_apply (box (Data_Semigroup_append)) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> (dictMonoid))))) (box (Prim_undefined)))))) in let mempty = (sharpurs_apply (box (Data_Monoid_mempty)) (box (dictMonoid))) in (fun (f: obj) -> (fun (g: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (bifoldr1)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_compose)) (box (append))))) (box (f)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_compose)) (box (append))))) (box (g)))))))) (box (mempty)))))))))

let Data_Bifoldable_bifoldMapDefaultL  = (fun (dictBifoldable: obj) -> (let bifoldl1 = (sharpurs_apply (box (Data_Bifoldable_bifoldl)) (box (dictBifoldable))) in (fun (dictMonoid: obj) -> (let append = (sharpurs_apply (box (Data_Semigroup_append)) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> (dictMonoid))))) (box (Prim_undefined)))))) in let mempty = (sharpurs_apply (box (Data_Monoid_mempty)) (box (dictMonoid))) in (fun (f: obj) -> (fun (g: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (bifoldl1)) (box ((fun (m: obj) -> (fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (append)) (box (m))))) (box ((sharpurs_apply (box (f)) (box (a))))))))))))) (box ((fun (m: obj) -> (fun (b: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (append)) (box (m))))) (box ((sharpurs_apply (box (g)) (box (b))))))))))))) (box (mempty)))))))))

let Data_Bifoldable_bifoldMap  = (fun (dict: obj) -> (match ((unbox (dict))) with | v -> (box ((Map.find "bifoldMap" (unbox<Map<string, obj>> (v)))))))

let Data_Bifoldable_bifoldableFlip  = (fun (dictBifoldable: obj) -> (let bifoldr1 = (sharpurs_apply (box (Data_Bifoldable_bifoldr)) (box (dictBifoldable))) in let bifoldl1 = (sharpurs_apply (box (Data_Bifoldable_bifoldl)) (box (dictBifoldable))) in let bifoldMap1 = (sharpurs_apply (box (Data_Bifoldable_bifoldMap)) (box (dictBifoldable))) in (sharpurs_apply (box (Data_Bifoldable_Bifoldableusd_Dict)) (box ((Map.add "bifoldr" (box ((fun (r: obj) -> (fun (l: obj) -> (fun (u: obj) -> (fun (v: obj) -> (match (((unbox (r)), (unbox (l)), (unbox (u)), (unbox (v)))) with | (r1, l1, u1, p) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (bifoldr1)) (box (l1))))) (box (r1))))) (box (u1))))) (box (p)))))))))))) (Map.add "bifoldl" (box ((fun (r: obj) -> (fun (l: obj) -> (fun (u: obj) -> (fun (v: obj) -> (match (((unbox (r)), (unbox (l)), (unbox (u)), (unbox (v)))) with | (r1, l1, u1, p) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (bifoldl1)) (box (l1))))) (box (r1))))) (box (u1))))) (box (p)))))))))))) (Map.add "bifoldMap" (box ((fun (dictMonoid: obj) -> (let bifoldMap2 = (sharpurs_apply (box (bifoldMap1)) (box (dictMonoid))) in (fun (r: obj) -> (fun (l: obj) -> (fun (v: obj) -> (match (((unbox (r)), (unbox (l)), (unbox (v)))) with | (r1, l1, p) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (bifoldMap2)) (box (l1))))) (box (r1))))) (box (p))))))))))))) Map.empty))))))))

let Data_Bifoldable_bifoldlDefault  = (fun (dictBifoldable: obj) -> (let bifoldMap1 = (sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_bifoldMap)) (box (dictBifoldable))))) (box (Data_Bifoldable_monoidDual))) in (fun (f: obj) -> (fun (g: obj) -> (fun (z: obj) -> (fun (p: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_unwrap)) (box ((sharpurs_apply (box (Data_Bifoldable_unwrap)) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (bifoldMap1)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_compose)) (box (Data_Monoid_Dual_Dual))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_compose)) (box (Data_Monoid_Endo_Endo))))) (box ((sharpurs_apply (box (Data_Function_flip)) (box (f)))))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_compose)) (box (Data_Monoid_Dual_Dual))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_compose)) (box (Data_Monoid_Endo_Endo))))) (box ((sharpurs_apply (box (Data_Function_flip)) (box (g)))))))))))))) (box (p))))))))))) (box (z)))))))))

let Data_Bifoldable_bifoldrDefault  = (fun (dictBifoldable: obj) -> (let bifoldMap1 = (sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_bifoldMap)) (box (dictBifoldable))))) (box (Data_Bifoldable_monoidEndo))) in (fun (f: obj) -> (fun (g: obj) -> (fun (z: obj) -> (fun (p: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_unwrap)) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (bifoldMap1)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_compose)) (box (Data_Monoid_Endo_Endo))))) (box (f)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_compose)) (box (Data_Monoid_Endo_Endo))))) (box (g)))))))) (box (p)))))))) (box (z)))))))))

let rec Data_Bifoldable_bifoldableProduct2  = (fun (dictBifoldable: obj) -> (let bifoldMap1 = (sharpurs_apply (box (Data_Bifoldable_bifoldMap)) (box (dictBifoldable))) in (fun (dictBifoldable1: obj) -> (let bifoldMap2 = (sharpurs_apply (box (Data_Bifoldable_bifoldMap)) (box (dictBifoldable1))) in (sharpurs_apply (box (Data_Bifoldable_Bifoldableusd_Dict)) (box ((Map.add "bifoldr" (box ((fun (l: obj) -> (fun (r: obj) -> (fun (u: obj) -> (fun (m: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_bifoldrDefault)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_bifoldableProduct2)) (box (dictBifoldable))))) (box (dictBifoldable1)))))))) (box (l))))) (box (r))))) (box (u))))) (box (m))))))))) (Map.add "bifoldl" (box ((fun (l: obj) -> (fun (r: obj) -> (fun (u: obj) -> (fun (m: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_bifoldlDefault)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_bifoldableProduct2)) (box (dictBifoldable))))) (box (dictBifoldable1)))))))) (box (l))))) (box (r))))) (box (u))))) (box (m))))))))) (Map.add "bifoldMap" (box ((fun (dictMonoid: obj) -> (let append = (sharpurs_apply (box (Data_Semigroup_append)) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> (dictMonoid))))) (box (Prim_undefined)))))) in let bifoldMap3 = (sharpurs_apply (box (bifoldMap1)) (box (dictMonoid))) in let bifoldMap4 = (sharpurs_apply (box (bifoldMap2)) (box (dictMonoid))) in (fun (l: obj) -> (fun (r: obj) -> (fun (v: obj) -> (match (((unbox (l)), (unbox (r)), (unbox (v)))) with | (l1, r1, Data_Functor_Product2_Product2usd_Ctor(f, g)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (append)) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (bifoldMap3)) (box (l1))))) (box (r1))))) (box (f)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (bifoldMap4)) (box (l1))))) (box (r1))))) (box (g)))))))))))))))) Map.empty))))))))))

let Data_Bifoldable_bifold  = (fun (dictBifoldable: obj) -> (let bifoldMap1 = (sharpurs_apply (box (Data_Bifoldable_bifoldMap)) (box (dictBifoldable))) in (fun (dictMonoid: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (bifoldMap1)) (box (dictMonoid))))) (box (Data_Bifoldable_identity))))) (box (Data_Bifoldable_identity))))))

let Data_Bifoldable_biany  = (fun (dictBifoldable: obj) -> (let bifoldMap1 = (sharpurs_apply (box (Data_Bifoldable_bifoldMap)) (box (dictBifoldable))) in (fun (dictBooleanAlgebra: obj) -> (let bifoldMap2 = (sharpurs_apply (box (bifoldMap1)) (box ((sharpurs_apply (box (Data_Monoid_Disj_monoidDisj)) (box ((sharpurs_apply (box ((Map.find "HeytingAlgebra0" (unbox<Map<string, obj>> (dictBooleanAlgebra))))) (box (Prim_undefined))))))))) in (fun (p: obj) -> (fun (q: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_compose)) (box (Data_Bifoldable_unwrap))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (bifoldMap2)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_compose)) (box (Data_Monoid_Disj_Disj))))) (box (p)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_compose)) (box (Data_Monoid_Disj_Disj))))) (box (q)))))))))))))))

let Data_Bifoldable_biall  = (fun (dictBifoldable: obj) -> (let bifoldMap1 = (sharpurs_apply (box (Data_Bifoldable_bifoldMap)) (box (dictBifoldable))) in (fun (dictBooleanAlgebra: obj) -> (let bifoldMap2 = (sharpurs_apply (box (bifoldMap1)) (box ((sharpurs_apply (box (Data_Monoid_Conj_monoidConj)) (box ((sharpurs_apply (box ((Map.find "HeytingAlgebra0" (unbox<Map<string, obj>> (dictBooleanAlgebra))))) (box (Prim_undefined))))))))) in (fun (p: obj) -> (fun (q: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_compose)) (box (Data_Bifoldable_unwrap))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (bifoldMap2)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_compose)) (box (Data_Monoid_Conj_Conj))))) (box (p)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Bifoldable_compose)) (box (Data_Monoid_Conj_Conj))))) (box (q)))))))))))))))
