[<AutoOpen>]
module PureScript_Data_Semigroup_Traversable

open System
open System.Collections.Generic

let Data_Semigroup_Traversable_identity  = (sharpurs_apply (box (Control_Category_identity)) (box (Control_Category_categoryFn)))

let Data_Semigroup_Traversable_Traversable1usd_Dict  = (fun (x: obj) -> x)

let Data_Semigroup_Traversable_traverse1  = (fun (dict: obj) -> (match ((unbox (dict))) with | v -> (box ((Map.find "traverse1" (unbox<Map<string, obj>> (v)))))))

let Data_Semigroup_Traversable_traversableTuple  = (sharpurs_apply (box (Data_Semigroup_Traversable_Traversable1usd_Dict)) (box ((Map.add "traverse1" (box ((fun (dictApply: obj) -> (let map = (sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (dictApply))))) (box (Prim_undefined)))))) in (fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, Data_Tuple_Tupleusd_Ctor(x, y)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (map)) (box ((fun (usd__arg1: obj) -> (box (Data_Tuple_Tupleusd_Ctor(x, usd__arg1))))))))) (box ((sharpurs_apply (box (f1)) (box (y))))))))))))))) (Map.add "sequence1" (box ((fun (dictApply: obj) -> (let map = (sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (dictApply))))) (box (Prim_undefined)))))) in (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(x, y) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (map)) (box ((fun (usd__arg1: obj) -> (box (Data_Tuple_Tupleusd_Ctor(x, usd__arg1))))))))) (box (y))))))))))) (Map.add "Foldable10" (box ((fun (_: obj) -> Data_Semigroup_Foldable_foldableTuple))) (Map.add "Traversable1" (box ((fun (_: obj) -> Data_Traversable_traversableTuple))) Map.empty)))))))

let Data_Semigroup_Traversable_traversableIdentity  = (sharpurs_apply (box (Data_Semigroup_Traversable_Traversable1usd_Dict)) (box ((Map.add "traverse1" (box ((fun (dictApply: obj) -> (let map = (sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (dictApply))))) (box (Prim_undefined)))))) in (fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, x) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (map)) (box (Data_Identity_Identity))))) (box ((sharpurs_apply (box (f1)) (box (x))))))))))))))) (Map.add "sequence1" (box ((fun (dictApply: obj) -> (let map = (sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (dictApply))))) (box (Prim_undefined)))))) in (fun (v: obj) -> (match ((unbox (v))) with | x -> (box ((sharpurs_apply (box ((sharpurs_apply (box (map)) (box (Data_Identity_Identity))))) (box (x))))))))))) (Map.add "Foldable10" (box ((fun (_: obj) -> Data_Semigroup_Foldable_foldableIdentity))) (Map.add "Traversable1" (box ((fun (_: obj) -> Data_Traversable_traversableIdentity))) Map.empty)))))))

let Data_Semigroup_Traversable_sequence1Default  = (fun (dictTraversable1: obj) -> (let traverse11 = (sharpurs_apply (box (Data_Semigroup_Traversable_traverse1)) (box (dictTraversable1))) in (fun (dictApply: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (traverse11)) (box (dictApply))))) (box (Data_Semigroup_Traversable_identity))))))

let rec Data_Semigroup_Traversable_traversableDual  = (sharpurs_apply (box (Data_Semigroup_Traversable_Traversable1usd_Dict)) (box ((Map.add "traverse1" (box ((fun (dictApply: obj) -> (let map = (sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (dictApply))))) (box (Prim_undefined)))))) in (fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, x) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (map)) (box (Data_Monoid_Dual_Dual))))) (box ((sharpurs_apply (box (f1)) (box (x))))))))))))))) (Map.add "sequence1" (box ((fun (dictApply: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Semigroup_Traversable_sequence1Default)) (box (Data_Semigroup_Traversable_traversableDual))))) (box (dictApply)))))) (Map.add "Foldable10" (box ((fun (_: obj) -> Data_Semigroup_Foldable_foldableDual))) (Map.add "Traversable1" (box ((fun (_: obj) -> Data_Traversable_traversableDual))) Map.empty)))))))

let rec Data_Semigroup_Traversable_traversableMultiplicative  = (sharpurs_apply (box (Data_Semigroup_Traversable_Traversable1usd_Dict)) (box ((Map.add "traverse1" (box ((fun (dictApply: obj) -> (let map = (sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (dictApply))))) (box (Prim_undefined)))))) in (fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, x) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (map)) (box (Data_Monoid_Multiplicative_Multiplicative))))) (box ((sharpurs_apply (box (f1)) (box (x))))))))))))))) (Map.add "sequence1" (box ((fun (dictApply: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Semigroup_Traversable_sequence1Default)) (box (Data_Semigroup_Traversable_traversableMultiplicative))))) (box (dictApply)))))) (Map.add "Foldable10" (box ((fun (_: obj) -> Data_Semigroup_Foldable_foldableMultiplicative))) (Map.add "Traversable1" (box ((fun (_: obj) -> Data_Traversable_traversableMultiplicative))) Map.empty)))))))

let Data_Semigroup_Traversable_sequence1  = (fun (dict: obj) -> (match ((unbox (dict))) with | v -> (box ((Map.find "sequence1" (unbox<Map<string, obj>> (v)))))))

let Data_Semigroup_Traversable_traverse1Default  = (fun (dictTraversable1: obj) -> (let sequence11 = (sharpurs_apply (box (Data_Semigroup_Traversable_sequence1)) (box (dictTraversable1))) in let map = (sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Traversable1" (unbox<Map<string, obj>> (dictTraversable1))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))) in (fun (dictApply: obj) -> (let sequence12 = (sharpurs_apply (box (sequence11)) (box (dictApply))) in (fun (f: obj) -> (fun (ta: obj) -> (sharpurs_apply (box (sequence12)) (box ((sharpurs_apply (box ((sharpurs_apply (box (map)) (box (f))))) (box (ta))))))))))))
