[<AutoOpen>]
module PureScript_Data_Tuple_Nested

open System
open System.Collections.Generic

let Data_Tuple_Nested_uncurry9  = (fun (f_prime: obj) -> (fun (v: obj) -> (match (((unbox (f_prime)), (unbox (v)))) with | (f_prime1, Data_Tuple_Tupleusd_Ctor(a, Unbox(Data_Tuple_Tupleusd_Ctor(b, Unbox(Data_Tuple_Tupleusd_Ctor(c, Unbox(Data_Tuple_Tupleusd_Ctor(d, Unbox(Data_Tuple_Tupleusd_Ctor(e, Unbox(Data_Tuple_Tupleusd_Ctor(f, Unbox(Data_Tuple_Tupleusd_Ctor(g, Unbox(Data_Tuple_Tupleusd_Ctor(h, Unbox(Data_Tuple_Tupleusd_Ctor(i, _)))))))))))))))))) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (f_prime1)) (box (a))))) (box (b))))) (box (c))))) (box (d))))) (box (e))))) (box (f))))) (box (g))))) (box (h))))) (box (i))))))))

let Data_Tuple_Nested_uncurry8  = (fun (f_prime: obj) -> (fun (v: obj) -> (match (((unbox (f_prime)), (unbox (v)))) with | (f_prime1, Data_Tuple_Tupleusd_Ctor(a, Unbox(Data_Tuple_Tupleusd_Ctor(b, Unbox(Data_Tuple_Tupleusd_Ctor(c, Unbox(Data_Tuple_Tupleusd_Ctor(d, Unbox(Data_Tuple_Tupleusd_Ctor(e, Unbox(Data_Tuple_Tupleusd_Ctor(f, Unbox(Data_Tuple_Tupleusd_Ctor(g, Unbox(Data_Tuple_Tupleusd_Ctor(h, _)))))))))))))))) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (f_prime1)) (box (a))))) (box (b))))) (box (c))))) (box (d))))) (box (e))))) (box (f))))) (box (g))))) (box (h))))))))

let Data_Tuple_Nested_uncurry7  = (fun (f_prime: obj) -> (fun (v: obj) -> (match (((unbox (f_prime)), (unbox (v)))) with | (f_prime1, Data_Tuple_Tupleusd_Ctor(a, Unbox(Data_Tuple_Tupleusd_Ctor(b, Unbox(Data_Tuple_Tupleusd_Ctor(c, Unbox(Data_Tuple_Tupleusd_Ctor(d, Unbox(Data_Tuple_Tupleusd_Ctor(e, Unbox(Data_Tuple_Tupleusd_Ctor(f, Unbox(Data_Tuple_Tupleusd_Ctor(g, _)))))))))))))) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (f_prime1)) (box (a))))) (box (b))))) (box (c))))) (box (d))))) (box (e))))) (box (f))))) (box (g))))))))

let Data_Tuple_Nested_uncurry6  = (fun (f_prime: obj) -> (fun (v: obj) -> (match (((unbox (f_prime)), (unbox (v)))) with | (f_prime1, Data_Tuple_Tupleusd_Ctor(a, Unbox(Data_Tuple_Tupleusd_Ctor(b, Unbox(Data_Tuple_Tupleusd_Ctor(c, Unbox(Data_Tuple_Tupleusd_Ctor(d, Unbox(Data_Tuple_Tupleusd_Ctor(e, Unbox(Data_Tuple_Tupleusd_Ctor(f, _)))))))))))) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (f_prime1)) (box (a))))) (box (b))))) (box (c))))) (box (d))))) (box (e))))) (box (f))))))))

let Data_Tuple_Nested_uncurry5  = (fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, Data_Tuple_Tupleusd_Ctor(a, Unbox(Data_Tuple_Tupleusd_Ctor(b, Unbox(Data_Tuple_Tupleusd_Ctor(c, Unbox(Data_Tuple_Tupleusd_Ctor(d, Unbox(Data_Tuple_Tupleusd_Ctor(e, _)))))))))) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (f1)) (box (a))))) (box (b))))) (box (c))))) (box (d))))) (box (e))))))))

let Data_Tuple_Nested_uncurry4  = (fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, Data_Tuple_Tupleusd_Ctor(a, Unbox(Data_Tuple_Tupleusd_Ctor(b, Unbox(Data_Tuple_Tupleusd_Ctor(c, Unbox(Data_Tuple_Tupleusd_Ctor(d, _)))))))) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (f1)) (box (a))))) (box (b))))) (box (c))))) (box (d))))))))

let Data_Tuple_Nested_uncurry3  = (fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, Data_Tuple_Tupleusd_Ctor(a, Unbox(Data_Tuple_Tupleusd_Ctor(b, Unbox(Data_Tuple_Tupleusd_Ctor(c, _)))))) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (f1)) (box (a))))) (box (b))))) (box (c))))))))

let Data_Tuple_Nested_uncurry2  = (fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, Data_Tuple_Tupleusd_Ctor(a, Unbox(Data_Tuple_Tupleusd_Ctor(b, _)))) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (f1)) (box (a))))) (box (b))))))))

let Data_Tuple_Nested_uncurry10  = (fun (f_prime: obj) -> (fun (v: obj) -> (match (((unbox (f_prime)), (unbox (v)))) with | (f_prime1, Data_Tuple_Tupleusd_Ctor(a, Unbox(Data_Tuple_Tupleusd_Ctor(b, Unbox(Data_Tuple_Tupleusd_Ctor(c, Unbox(Data_Tuple_Tupleusd_Ctor(d, Unbox(Data_Tuple_Tupleusd_Ctor(e, Unbox(Data_Tuple_Tupleusd_Ctor(f, Unbox(Data_Tuple_Tupleusd_Ctor(g, Unbox(Data_Tuple_Tupleusd_Ctor(h, Unbox(Data_Tuple_Tupleusd_Ctor(i, Unbox(Data_Tuple_Tupleusd_Ctor(j, _)))))))))))))))))))) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (f_prime1)) (box (a))))) (box (b))))) (box (c))))) (box (d))))) (box (e))))) (box (f))))) (box (g))))) (box (h))))) (box (i))))) (box (j))))))))

let Data_Tuple_Nested_uncurry1  = (fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, Data_Tuple_Tupleusd_Ctor(a, _)) -> (box ((sharpurs_apply (box (f1)) (box (a))))))))

let Data_Tuple_Nested_tuple9  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (fun (g: obj) -> (fun (h: obj) -> (fun (i: obj) -> (box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor(c, (box (Data_Tuple_Tupleusd_Ctor(d, (box (Data_Tuple_Tupleusd_Ctor(e, (box (Data_Tuple_Tupleusd_Ctor(f, (box (Data_Tuple_Tupleusd_Ctor(g, (box (Data_Tuple_Tupleusd_Ctor(h, (box (Data_Tuple_Tupleusd_Ctor(i, Data_Unit_unit))))))))))))))))))))))))))))))))))))

let Data_Tuple_Nested_tuple8  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (fun (g: obj) -> (fun (h: obj) -> (box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor(c, (box (Data_Tuple_Tupleusd_Ctor(d, (box (Data_Tuple_Tupleusd_Ctor(e, (box (Data_Tuple_Tupleusd_Ctor(f, (box (Data_Tuple_Tupleusd_Ctor(g, (box (Data_Tuple_Tupleusd_Ctor(h, Data_Unit_unit))))))))))))))))))))))))))))))))

let Data_Tuple_Nested_tuple7  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (fun (g: obj) -> (box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor(c, (box (Data_Tuple_Tupleusd_Ctor(d, (box (Data_Tuple_Tupleusd_Ctor(e, (box (Data_Tuple_Tupleusd_Ctor(f, (box (Data_Tuple_Tupleusd_Ctor(g, Data_Unit_unit))))))))))))))))))))))))))))

let Data_Tuple_Nested_tuple6  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor(c, (box (Data_Tuple_Tupleusd_Ctor(d, (box (Data_Tuple_Tupleusd_Ctor(e, (box (Data_Tuple_Tupleusd_Ctor(f, Data_Unit_unit))))))))))))))))))))))))

let Data_Tuple_Nested_tuple5  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor(c, (box (Data_Tuple_Tupleusd_Ctor(d, (box (Data_Tuple_Tupleusd_Ctor(e, Data_Unit_unit))))))))))))))))))))

let Data_Tuple_Nested_tuple4  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor(c, (box (Data_Tuple_Tupleusd_Ctor(d, Data_Unit_unit))))))))))))))))

let Data_Tuple_Nested_tuple3  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor(c, Data_Unit_unit))))))))))))

let Data_Tuple_Nested_tuple2  = (fun (a: obj) -> (fun (b: obj) -> (box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, Data_Unit_unit))))))))

let Data_Tuple_Nested_tuple10  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (fun (g: obj) -> (fun (h: obj) -> (fun (i: obj) -> (fun (j: obj) -> (box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor(c, (box (Data_Tuple_Tupleusd_Ctor(d, (box (Data_Tuple_Tupleusd_Ctor(e, (box (Data_Tuple_Tupleusd_Ctor(f, (box (Data_Tuple_Tupleusd_Ctor(g, (box (Data_Tuple_Tupleusd_Ctor(h, (box (Data_Tuple_Tupleusd_Ctor(i, (box (Data_Tuple_Tupleusd_Ctor(j, Data_Unit_unit))))))))))))))))))))))))))))))))))))))))

let Data_Tuple_Nested_tuple1  = (fun (a: obj) -> (box (Data_Tuple_Tupleusd_Ctor(a, Data_Unit_unit))))

let Data_Tuple_Nested_over9  = (fun (o: obj) -> (fun (v: obj) -> (match (((unbox (o)), (unbox (v)))) with | (o1, Data_Tuple_Tupleusd_Ctor(a, Unbox(Data_Tuple_Tupleusd_Ctor(b, Unbox(Data_Tuple_Tupleusd_Ctor(c, Unbox(Data_Tuple_Tupleusd_Ctor(d, Unbox(Data_Tuple_Tupleusd_Ctor(e, Unbox(Data_Tuple_Tupleusd_Ctor(f, Unbox(Data_Tuple_Tupleusd_Ctor(g, Unbox(Data_Tuple_Tupleusd_Ctor(h, Unbox(Data_Tuple_Tupleusd_Ctor(i, z)))))))))))))))))) -> (box ((box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor(c, (box (Data_Tuple_Tupleusd_Ctor(d, (box (Data_Tuple_Tupleusd_Ctor(e, (box (Data_Tuple_Tupleusd_Ctor(f, (box (Data_Tuple_Tupleusd_Ctor(g, (box (Data_Tuple_Tupleusd_Ctor(h, (box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box (o1)) (box (i))), z))))))))))))))))))))))))))))))))

let Data_Tuple_Nested_over8  = (fun (o: obj) -> (fun (v: obj) -> (match (((unbox (o)), (unbox (v)))) with | (o1, Data_Tuple_Tupleusd_Ctor(a, Unbox(Data_Tuple_Tupleusd_Ctor(b, Unbox(Data_Tuple_Tupleusd_Ctor(c, Unbox(Data_Tuple_Tupleusd_Ctor(d, Unbox(Data_Tuple_Tupleusd_Ctor(e, Unbox(Data_Tuple_Tupleusd_Ctor(f, Unbox(Data_Tuple_Tupleusd_Ctor(g, Unbox(Data_Tuple_Tupleusd_Ctor(h, z)))))))))))))))) -> (box ((box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor(c, (box (Data_Tuple_Tupleusd_Ctor(d, (box (Data_Tuple_Tupleusd_Ctor(e, (box (Data_Tuple_Tupleusd_Ctor(f, (box (Data_Tuple_Tupleusd_Ctor(g, (box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box (o1)) (box (h))), z)))))))))))))))))))))))))))))

let Data_Tuple_Nested_over7  = (fun (o: obj) -> (fun (v: obj) -> (match (((unbox (o)), (unbox (v)))) with | (o1, Data_Tuple_Tupleusd_Ctor(a, Unbox(Data_Tuple_Tupleusd_Ctor(b, Unbox(Data_Tuple_Tupleusd_Ctor(c, Unbox(Data_Tuple_Tupleusd_Ctor(d, Unbox(Data_Tuple_Tupleusd_Ctor(e, Unbox(Data_Tuple_Tupleusd_Ctor(f, Unbox(Data_Tuple_Tupleusd_Ctor(g, z)))))))))))))) -> (box ((box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor(c, (box (Data_Tuple_Tupleusd_Ctor(d, (box (Data_Tuple_Tupleusd_Ctor(e, (box (Data_Tuple_Tupleusd_Ctor(f, (box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box (o1)) (box (g))), z))))))))))))))))))))))))))

let Data_Tuple_Nested_over6  = (fun (o: obj) -> (fun (v: obj) -> (match (((unbox (o)), (unbox (v)))) with | (o1, Data_Tuple_Tupleusd_Ctor(a, Unbox(Data_Tuple_Tupleusd_Ctor(b, Unbox(Data_Tuple_Tupleusd_Ctor(c, Unbox(Data_Tuple_Tupleusd_Ctor(d, Unbox(Data_Tuple_Tupleusd_Ctor(e, Unbox(Data_Tuple_Tupleusd_Ctor(f, z)))))))))))) -> (box ((box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor(c, (box (Data_Tuple_Tupleusd_Ctor(d, (box (Data_Tuple_Tupleusd_Ctor(e, (box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box (o1)) (box (f))), z)))))))))))))))))))))))

let Data_Tuple_Nested_over5  = (fun (o: obj) -> (fun (v: obj) -> (match (((unbox (o)), (unbox (v)))) with | (o1, Data_Tuple_Tupleusd_Ctor(a, Unbox(Data_Tuple_Tupleusd_Ctor(b, Unbox(Data_Tuple_Tupleusd_Ctor(c, Unbox(Data_Tuple_Tupleusd_Ctor(d, Unbox(Data_Tuple_Tupleusd_Ctor(e, z)))))))))) -> (box ((box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor(c, (box (Data_Tuple_Tupleusd_Ctor(d, (box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box (o1)) (box (e))), z))))))))))))))))))))

let Data_Tuple_Nested_over4  = (fun (o: obj) -> (fun (v: obj) -> (match (((unbox (o)), (unbox (v)))) with | (o1, Data_Tuple_Tupleusd_Ctor(a, Unbox(Data_Tuple_Tupleusd_Ctor(b, Unbox(Data_Tuple_Tupleusd_Ctor(c, Unbox(Data_Tuple_Tupleusd_Ctor(d, z)))))))) -> (box ((box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor(c, (box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box (o1)) (box (d))), z)))))))))))))))))

let Data_Tuple_Nested_over3  = (fun (o: obj) -> (fun (v: obj) -> (match (((unbox (o)), (unbox (v)))) with | (o1, Data_Tuple_Tupleusd_Ctor(a, Unbox(Data_Tuple_Tupleusd_Ctor(b, Unbox(Data_Tuple_Tupleusd_Ctor(c, z)))))) -> (box ((box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box (o1)) (box (c))), z))))))))))))))

let Data_Tuple_Nested_over2  = (fun (o: obj) -> (fun (v: obj) -> (match (((unbox (o)), (unbox (v)))) with | (o1, Data_Tuple_Tupleusd_Ctor(a, Unbox(Data_Tuple_Tupleusd_Ctor(b, z)))) -> (box ((box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box (o1)) (box (b))), z)))))))))))

let Data_Tuple_Nested_over10  = (fun (o: obj) -> (fun (v: obj) -> (match (((unbox (o)), (unbox (v)))) with | (o1, Data_Tuple_Tupleusd_Ctor(a, Unbox(Data_Tuple_Tupleusd_Ctor(b, Unbox(Data_Tuple_Tupleusd_Ctor(c, Unbox(Data_Tuple_Tupleusd_Ctor(d, Unbox(Data_Tuple_Tupleusd_Ctor(e, Unbox(Data_Tuple_Tupleusd_Ctor(f, Unbox(Data_Tuple_Tupleusd_Ctor(g, Unbox(Data_Tuple_Tupleusd_Ctor(h, Unbox(Data_Tuple_Tupleusd_Ctor(i, Unbox(Data_Tuple_Tupleusd_Ctor(j, z)))))))))))))))))))) -> (box ((box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor(c, (box (Data_Tuple_Tupleusd_Ctor(d, (box (Data_Tuple_Tupleusd_Ctor(e, (box (Data_Tuple_Tupleusd_Ctor(f, (box (Data_Tuple_Tupleusd_Ctor(g, (box (Data_Tuple_Tupleusd_Ctor(h, (box (Data_Tuple_Tupleusd_Ctor(i, (box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box (o1)) (box (j))), z)))))))))))))))))))))))))))))))))))

let Data_Tuple_Nested_over1  = (fun (o: obj) -> (fun (v: obj) -> (match (((unbox (o)), (unbox (v)))) with | (o1, Data_Tuple_Tupleusd_Ctor(a, z)) -> (box ((box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box (o1)) (box (a))), z))))))))

let Data_Tuple_Nested_get9  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(i, _))))))))))))))))) -> (box (i))))

let Data_Tuple_Nested_get8  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(h, _))))))))))))))) -> (box (h))))

let Data_Tuple_Nested_get7  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(g, _))))))))))))) -> (box (g))))

let Data_Tuple_Nested_get6  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(f, _))))))))))) -> (box (f))))

let Data_Tuple_Nested_get5  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(e, _))))))))) -> (box (e))))

let Data_Tuple_Nested_get4  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(d, _))))))) -> (box (d))))

let Data_Tuple_Nested_get3  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(c, _))))) -> (box (c))))

let Data_Tuple_Nested_get2  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(b, _))) -> (box (b))))

let Data_Tuple_Nested_get10  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(j, _))))))))))))))))))) -> (box (j))))

let Data_Tuple_Nested_get1  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(a, _) -> (box (a))))

let Data_Tuple_Nested_curry9  = (fun (z: obj) -> (fun (f_prime: obj) -> (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (fun (g: obj) -> (fun (h: obj) -> (fun (i: obj) -> (sharpurs_apply (box (f_prime)) (box ((box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor(c, (box (Data_Tuple_Tupleusd_Ctor(d, (box (Data_Tuple_Tupleusd_Ctor(e, (box (Data_Tuple_Tupleusd_Ctor(f, (box (Data_Tuple_Tupleusd_Ctor(g, (box (Data_Tuple_Tupleusd_Ctor(h, (box (Data_Tuple_Tupleusd_Ctor(i, z)))))))))))))))))))))))))))))))))))))))))

let Data_Tuple_Nested_curry8  = (fun (z: obj) -> (fun (f_prime: obj) -> (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (fun (g: obj) -> (fun (h: obj) -> (sharpurs_apply (box (f_prime)) (box ((box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor(c, (box (Data_Tuple_Tupleusd_Ctor(d, (box (Data_Tuple_Tupleusd_Ctor(e, (box (Data_Tuple_Tupleusd_Ctor(f, (box (Data_Tuple_Tupleusd_Ctor(g, (box (Data_Tuple_Tupleusd_Ctor(h, z)))))))))))))))))))))))))))))))))))))

let Data_Tuple_Nested_curry7  = (fun (z: obj) -> (fun (f_prime: obj) -> (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (fun (g: obj) -> (sharpurs_apply (box (f_prime)) (box ((box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor(c, (box (Data_Tuple_Tupleusd_Ctor(d, (box (Data_Tuple_Tupleusd_Ctor(e, (box (Data_Tuple_Tupleusd_Ctor(f, (box (Data_Tuple_Tupleusd_Ctor(g, z)))))))))))))))))))))))))))))))))

let Data_Tuple_Nested_curry6  = (fun (z: obj) -> (fun (f_prime: obj) -> (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (sharpurs_apply (box (f_prime)) (box ((box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor(c, (box (Data_Tuple_Tupleusd_Ctor(d, (box (Data_Tuple_Tupleusd_Ctor(e, (box (Data_Tuple_Tupleusd_Ctor(f, z)))))))))))))))))))))))))))))

let Data_Tuple_Nested_curry5  = (fun (z: obj) -> (fun (f: obj) -> (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (sharpurs_apply (box (f)) (box ((box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor(c, (box (Data_Tuple_Tupleusd_Ctor(d, (box (Data_Tuple_Tupleusd_Ctor(e, z)))))))))))))))))))))))))

let Data_Tuple_Nested_curry4  = (fun (z: obj) -> (fun (f: obj) -> (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (sharpurs_apply (box (f)) (box ((box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor(c, (box (Data_Tuple_Tupleusd_Ctor(d, z)))))))))))))))))))))

let Data_Tuple_Nested_curry3  = (fun (z: obj) -> (fun (f: obj) -> (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (sharpurs_apply (box (f)) (box ((box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor(c, z)))))))))))))))))

let Data_Tuple_Nested_curry2  = (fun (z: obj) -> (fun (f: obj) -> (fun (a: obj) -> (fun (b: obj) -> (sharpurs_apply (box (f)) (box ((box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, z)))))))))))))

let Data_Tuple_Nested_curry10  = (fun (z: obj) -> (fun (f_prime: obj) -> (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (fun (g: obj) -> (fun (h: obj) -> (fun (i: obj) -> (fun (j: obj) -> (sharpurs_apply (box (f_prime)) (box ((box (Data_Tuple_Tupleusd_Ctor(a, (box (Data_Tuple_Tupleusd_Ctor(b, (box (Data_Tuple_Tupleusd_Ctor(c, (box (Data_Tuple_Tupleusd_Ctor(d, (box (Data_Tuple_Tupleusd_Ctor(e, (box (Data_Tuple_Tupleusd_Ctor(f, (box (Data_Tuple_Tupleusd_Ctor(g, (box (Data_Tuple_Tupleusd_Ctor(h, (box (Data_Tuple_Tupleusd_Ctor(i, (box (Data_Tuple_Tupleusd_Ctor(j, z)))))))))))))))))))))))))))))))))))))))))))))

let Data_Tuple_Nested_curry1  = (fun (z: obj) -> (fun (f: obj) -> (fun (a: obj) -> (sharpurs_apply (box (f)) (box ((box (Data_Tuple_Tupleusd_Ctor(a, z)))))))))
