[<AutoOpen>]
module PureScript_Data_Functor_Product2

open System
open System.Collections.Generic

type Data_Functor_Product2_Product2 =
  | Data_Functor_Product2_Product2usd_Ctor of obj * obj

let Data_Functor_Product2_append  = (sharpurs_apply (box (Data_Semigroup_append)) (box (Data_Semigroup_semigroupString)))

let Data_Functor_Product2_conj  = (sharpurs_apply (box (Data_HeytingAlgebra_conj)) (box (Data_HeytingAlgebra_heytingAlgebraBoolean)))

let Data_Functor_Product2_Product2  = (fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Functor_Product2_Product2usd_Ctor(usd__arg1, usd__arg2)))))

let Data_Functor_Product2_showProduct2  = (fun (dictShow: obj) -> (let show = (sharpurs_apply (box (Data_Show_show)) (box (dictShow))) in (fun (dictShow1: obj) -> (let show1 = (sharpurs_apply (box (Data_Show_show)) (box (dictShow1))) in (sharpurs_apply (box (Data_Show_Showusd_Dict)) (box ((Map.add "show" (box ((fun (v: obj) -> (match ((unbox (v))) with | Data_Functor_Product2_Product2usd_Ctor(x, y) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product2_append)) (box ((box "(Product2 ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product2_append)) (box ((sharpurs_apply (box (show)) (box (x)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product2_append)) (box ((box " ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product2_append)) (box ((sharpurs_apply (box (show1)) (box (y)))))))) (box ((box ")"))))))))))))))))))) Map.empty))))))))

let Data_Functor_Product2_profunctorProduct2  = (fun (dictProfunctor: obj) -> (let dimap = (sharpurs_apply (box (Data_Profunctor_dimap)) (box (dictProfunctor))) in (fun (dictProfunctor1: obj) -> (let dimap1 = (sharpurs_apply (box (Data_Profunctor_dimap)) (box (dictProfunctor1))) in (sharpurs_apply (box (Data_Profunctor_Profunctorusd_Dict)) (box ((Map.add "dimap" (box ((fun (f: obj) -> (fun (g: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (g)), (unbox (v)))) with | (f1, g1, Data_Functor_Product2_Product2usd_Ctor(x, y)) -> (box ((box (Data_Functor_Product2_Product2usd_Ctor((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (dimap)) (box (f1))))) (box (g1))))) (box (x))), (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (dimap1)) (box (f1))))) (box (g1))))) (box (y)))))))))))))) Map.empty))))))))

let Data_Functor_Product2_functorProduct2  = (fun (dictFunctor: obj) -> (let map = (sharpurs_apply (box (Data_Functor_map)) (box (dictFunctor))) in (fun (dictFunctor1: obj) -> (let map1 = (sharpurs_apply (box (Data_Functor_map)) (box (dictFunctor1))) in (sharpurs_apply (box (Data_Functor_Functorusd_Dict)) (box ((Map.add "map" (box ((fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, Data_Functor_Product2_Product2usd_Ctor(x, y)) -> (box ((box (Data_Functor_Product2_Product2usd_Ctor((sharpurs_apply (box ((sharpurs_apply (box (map)) (box (f1))))) (box (x))), (sharpurs_apply (box ((sharpurs_apply (box (map1)) (box (f1))))) (box (y))))))))))))) Map.empty))))))))

let Data_Functor_Product2_eqProduct2  = (fun (dictEq: obj) -> (let eq = (sharpurs_apply (box (Data_Eq_eq)) (box (dictEq))) in (fun (dictEq1: obj) -> (let eq1 = (sharpurs_apply (box (Data_Eq_eq)) (box (dictEq1))) in (sharpurs_apply (box (Data_Eq_Equsd_Dict)) (box ((Map.add "eq" (box ((fun (x: obj) -> (fun (y: obj) -> (match (((unbox (x)), (unbox (y)))) with | (Data_Functor_Product2_Product2usd_Ctor(l, l1), Data_Functor_Product2_Product2usd_Ctor(r, r1)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product2_conj)) (box ((sharpurs_apply (box ((sharpurs_apply (box (eq)) (box (l))))) (box (r)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (eq1)) (box (l1))))) (box (r1))))))))))))) Map.empty))))))))

let Data_Functor_Product2_ordProduct2  = (fun (dictOrd: obj) -> (let compare = (sharpurs_apply (box (Data_Ord_compare)) (box (dictOrd))) in let eqProduct21 = (sharpurs_apply (box (Data_Functor_Product2_eqProduct2)) (box ((sharpurs_apply (box ((Map.find "Eq0" (unbox<Map<string, obj>> (dictOrd))))) (box (Prim_undefined)))))) in (fun (dictOrd1: obj) -> (let compare1 = (sharpurs_apply (box (Data_Ord_compare)) (box (dictOrd1))) in let eqProduct22 = (sharpurs_apply (box (eqProduct21)) (box ((sharpurs_apply (box ((Map.find "Eq0" (unbox<Map<string, obj>> (dictOrd1))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Ord_Ordusd_Dict)) (box ((Map.add "compare" (box ((fun (x: obj) -> (fun (y: obj) -> (match (((unbox (x)), (unbox (y)))) with | (Data_Functor_Product2_Product2usd_Ctor(l, l1), Data_Functor_Product2_Product2usd_Ctor(r, r1)) -> (box ((let v = (sharpurs_apply (box ((sharpurs_apply (box (compare)) (box (l))))) (box (r))) in (match ((unbox (v))) with | Data_Ordering_LTusd_Ctor -> (box ((box Data_Ordering_LTusd_Ctor))) | Data_Ordering_GTusd_Ctor -> (box ((box Data_Ordering_GTusd_Ctor))) | _ -> (box ((sharpurs_apply (box ((sharpurs_apply (box (compare1)) (box (l1))))) (box (r1)))))))))))))) (Map.add "Eq0" (box ((fun (_: obj) -> eqProduct22))) Map.empty)))))))))

let Data_Functor_Product2_bifunctorProduct2  = (fun (dictBifunctor: obj) -> (let bimap = (sharpurs_apply (box (Data_Bifunctor_bimap)) (box (dictBifunctor))) in (fun (dictBifunctor1: obj) -> (let bimap1 = (sharpurs_apply (box (Data_Bifunctor_bimap)) (box (dictBifunctor1))) in (sharpurs_apply (box (Data_Bifunctor_Bifunctorusd_Dict)) (box ((Map.add "bimap" (box ((fun (f: obj) -> (fun (g: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (g)), (unbox (v)))) with | (f1, g1, Data_Functor_Product2_Product2usd_Ctor(x, y)) -> (box ((box (Data_Functor_Product2_Product2usd_Ctor((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (bimap)) (box (f1))))) (box (g1))))) (box (x))), (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (bimap1)) (box (f1))))) (box (g1))))) (box (y)))))))))))))) Map.empty))))))))

let Data_Functor_Product2_biapplyProduct2  = (fun (dictBiapply: obj) -> (let biapply = (sharpurs_apply (box (Control_Biapply_biapply)) (box (dictBiapply))) in let bifunctorProduct21 = (sharpurs_apply (box (Data_Functor_Product2_bifunctorProduct2)) (box ((sharpurs_apply (box ((Map.find "Bifunctor0" (unbox<Map<string, obj>> (dictBiapply))))) (box (Prim_undefined)))))) in (fun (dictBiapply1: obj) -> (let biapply1 = (sharpurs_apply (box (Control_Biapply_biapply)) (box (dictBiapply1))) in let bifunctorProduct22 = (sharpurs_apply (box (bifunctorProduct21)) (box ((sharpurs_apply (box ((Map.find "Bifunctor0" (unbox<Map<string, obj>> (dictBiapply1))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Control_Biapply_Biapplyusd_Dict)) (box ((Map.add "biapply" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (Data_Functor_Product2_Product2usd_Ctor(w, x), Data_Functor_Product2_Product2usd_Ctor(y, z)) -> (box ((box (Data_Functor_Product2_Product2usd_Ctor((sharpurs_apply (box ((sharpurs_apply (box (biapply)) (box (w))))) (box (y))), (sharpurs_apply (box ((sharpurs_apply (box (biapply1)) (box (x))))) (box (z))))))))))))) (Map.add "Bifunctor0" (box ((fun (_: obj) -> bifunctorProduct22))) Map.empty)))))))))

let Data_Functor_Product2_biapplicativeProduct2  = (fun (dictBiapplicative: obj) -> (let bipure = (sharpurs_apply (box (Control_Biapplicative_bipure)) (box (dictBiapplicative))) in let biapplyProduct21 = (sharpurs_apply (box (Data_Functor_Product2_biapplyProduct2)) (box ((sharpurs_apply (box ((Map.find "Biapply0" (unbox<Map<string, obj>> (dictBiapplicative))))) (box (Prim_undefined)))))) in (fun (dictBiapplicative1: obj) -> (let bipure1 = (sharpurs_apply (box (Control_Biapplicative_bipure)) (box (dictBiapplicative1))) in let biapplyProduct22 = (sharpurs_apply (box (biapplyProduct21)) (box ((sharpurs_apply (box ((Map.find "Biapply0" (unbox<Map<string, obj>> (dictBiapplicative1))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Control_Biapplicative_Biapplicativeusd_Dict)) (box ((Map.add "bipure" (box ((fun (a: obj) -> (fun (b: obj) -> (box (Data_Functor_Product2_Product2usd_Ctor((sharpurs_apply (box ((sharpurs_apply (box (bipure)) (box (a))))) (box (b))), (sharpurs_apply (box ((sharpurs_apply (box (bipure1)) (box (a))))) (box (b)))))))))) (Map.add "Biapply0" (box ((fun (_: obj) -> biapplyProduct22))) Map.empty)))))))))
