[<AutoOpen>]
module PureScript_Data_NonEmpty

open System
open System.Collections.Generic

type Data_NonEmpty_NonEmpty =
  | Data_NonEmpty_NonEmptyusd_Ctor of obj * obj

let Data_NonEmpty_map  = (sharpurs_apply (box (Data_Functor_map)) (box (Data_Tuple_functorTuple)))

let Data_NonEmpty_map1  = (sharpurs_apply (box (Data_Functor_map)) (box (Data_Maybe_functorMaybe)))

let Data_NonEmpty_append  = (sharpurs_apply (box (Data_Semigroup_append)) (box (Data_Semigroup_semigroupString)))

let Data_NonEmpty_compose  = (sharpurs_apply (box (Control_Semigroupoid_compose)) (box (Control_Semigroupoid_semigroupoidFn)))

let Data_NonEmpty_conj  = (sharpurs_apply (box (Data_HeytingAlgebra_conj)) (box (Data_HeytingAlgebra_heytingAlgebraBoolean)))

let Data_NonEmpty_NonEmpty  = (fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2)))))

let Data_NonEmpty_unfoldable1NonEmpty  = (fun (dictUnfoldable: obj) -> (let unfoldr = (sharpurs_apply (box (Data_Unfoldable_unfoldr)) (box (dictUnfoldable))) in (sharpurs_apply (box (Data_Unfoldable1_Unfoldable1usd_Dict)) (box ((Map.add "unfoldr1" (box ((fun (f: obj) -> (fun (b: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Tuple_uncurry)) (box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2)))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_NonEmpty_map)) (box ((sharpurs_apply (box (unfoldr)) (box ((sharpurs_apply (box (Data_NonEmpty_map1)) (box (f))))))))))) (box ((sharpurs_apply (box (f)) (box (b))))))))))))) Map.empty))))))

let Data_NonEmpty_tail  = (fun (v: obj) -> (match ((unbox (v))) with | Data_NonEmpty_NonEmptyusd_Ctor(_, xs) -> (box (xs))))

let Data_NonEmpty_singleton  = (fun (dictPlus: obj) -> (let empty = (sharpurs_apply (box (Control_Plus_empty)) (box (dictPlus))) in (fun (a: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(a, empty))))))

let Data_NonEmpty_showNonEmpty  = (fun (dictShow: obj) -> (let show = (sharpurs_apply (box (Data_Show_show)) (box (dictShow))) in (fun (dictShow1: obj) -> (let show1 = (sharpurs_apply (box (Data_Show_show)) (box (dictShow1))) in (sharpurs_apply (box (Data_Show_Showusd_Dict)) (box ((Map.add "show" (box ((fun (v: obj) -> (match ((unbox (v))) with | Data_NonEmpty_NonEmptyusd_Ctor(a, fa) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_NonEmpty_append)) (box ((box "(NonEmpty ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_NonEmpty_append)) (box ((sharpurs_apply (box (show)) (box (a)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_NonEmpty_append)) (box ((box " ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_NonEmpty_append)) (box ((sharpurs_apply (box (show1)) (box (fa)))))))) (box ((box ")"))))))))))))))))))) Map.empty))))))))

let Data_NonEmpty_semigroupNonEmpty  = (fun (dictApplicative: obj) -> (let pure_ = (sharpurs_apply (box (Control_Applicative_pure)) (box (dictApplicative))) in (fun (dictSemigroup: obj) -> (let append1 = (sharpurs_apply (box (Data_Semigroup_append)) (box (dictSemigroup))) in (sharpurs_apply (box (Data_Semigroup_Semigroupusd_Dict)) (box ((Map.add "append" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (Data_NonEmpty_NonEmptyusd_Ctor(a1, f1), Data_NonEmpty_NonEmptyusd_Ctor(a2, f2)) -> (box ((box (Data_NonEmpty_NonEmptyusd_Ctor(a1, (sharpurs_apply (box ((sharpurs_apply (box (append1)) (box (f1))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (append1)) (box ((sharpurs_apply (box (pure_)) (box (a2)))))))) (box (f2)))))))))))))))) Map.empty))))))))

let Data_NonEmpty_oneOf  = (fun (dictAlternative: obj) -> (let alt = (sharpurs_apply (box (Control_Alt_alt)) (box ((sharpurs_apply (box ((Map.find "Alt0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Plus1" (unbox<Map<string, obj>> (dictAlternative))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))) in let pure_ = (sharpurs_apply (box (Control_Applicative_pure)) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> (dictAlternative))))) (box (Prim_undefined)))))) in (fun (v: obj) -> (match ((unbox (v))) with | Data_NonEmpty_NonEmptyusd_Ctor(a, fa) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (alt)) (box ((sharpurs_apply (box (pure_)) (box (a)))))))) (box (fa)))))))))

let Data_NonEmpty_head  = (fun (v: obj) -> (match ((unbox (v))) with | Data_NonEmpty_NonEmptyusd_Ctor(x, _) -> (box (x))))

let Data_NonEmpty_functorNonEmpty  = (fun (dictFunctor: obj) -> (let map2 = (sharpurs_apply (box (Data_Functor_map)) (box (dictFunctor))) in (sharpurs_apply (box (Data_Functor_Functorusd_Dict)) (box ((Map.add "map" (box ((fun (f: obj) -> (fun (m: obj) -> (match ((unbox (m))) with | Data_NonEmpty_NonEmptyusd_Ctor(v, v1) -> (box ((box (Data_NonEmpty_NonEmptyusd_Ctor((sharpurs_apply (box (f)) (box (v))), (sharpurs_apply (box ((sharpurs_apply (box (map2)) (box (f))))) (box (v1))))))))))))) Map.empty))))))

let Data_NonEmpty_functorWithIndex  = (fun (dictFunctorWithIndex: obj) -> (let mapWithIndex = (sharpurs_apply (box (Data_FunctorWithIndex_mapWithIndex)) (box (dictFunctorWithIndex))) in let functorNonEmpty1 = (sharpurs_apply (box (Data_NonEmpty_functorNonEmpty)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (dictFunctorWithIndex))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_FunctorWithIndex_FunctorWithIndexusd_Dict)) (box ((Map.add "mapWithIndex" (box ((fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, Data_NonEmpty_NonEmptyusd_Ctor(a, fa)) -> (box ((box (Data_NonEmpty_NonEmptyusd_Ctor((sharpurs_apply (box ((sharpurs_apply (box (f1)) (box ((box Data_Maybe_Nothingusd_Ctor)))))) (box (a))), (sharpurs_apply (box ((sharpurs_apply (box (mapWithIndex)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_NonEmpty_compose)) (box (f1))))) (box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))))))) (box (fa))))))))))))) (Map.add "Functor0" (box ((fun (_: obj) -> functorNonEmpty1))) Map.empty)))))))

let Data_NonEmpty_fromNonEmpty  = (fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, Data_NonEmpty_NonEmptyusd_Ctor(a, fa)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (f1)) (box (a))))) (box (fa))))))))

let Data_NonEmpty_foldableNonEmpty  = (fun (dictFoldable: obj) -> (let foldMap = (sharpurs_apply (box (Data_Foldable_foldMap)) (box (dictFoldable))) in let foldl = (sharpurs_apply (box (Data_Foldable_foldl)) (box (dictFoldable))) in let foldr = (sharpurs_apply (box (Data_Foldable_foldr)) (box (dictFoldable))) in (sharpurs_apply (box (Data_Foldable_Foldableusd_Dict)) (box ((Map.add "foldMap" (box ((fun (dictMonoid: obj) -> (let append1 = (sharpurs_apply (box (Data_Semigroup_append)) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> (dictMonoid))))) (box (Prim_undefined)))))) in let foldMap1 = (sharpurs_apply (box (foldMap)) (box (dictMonoid))) in (fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, Data_NonEmpty_NonEmptyusd_Ctor(a, fa)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (append1)) (box ((sharpurs_apply (box (f1)) (box (a)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (foldMap1)) (box (f1))))) (box (fa))))))))))))))) (Map.add "foldl" (box ((fun (f: obj) -> (fun (b: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (b)), (unbox (v)))) with | (f1, b1, Data_NonEmpty_NonEmptyusd_Ctor(a, fa)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (foldl)) (box (f1))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (f1)) (box (b1))))) (box (a)))))))) (box (fa))))))))))) (Map.add "foldr" (box ((fun (f: obj) -> (fun (b: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (b)), (unbox (v)))) with | (f1, b1, Data_NonEmpty_NonEmptyusd_Ctor(a, fa)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (f1)) (box (a))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (foldr)) (box (f1))))) (box (b1))))) (box (fa)))))))))))))) Map.empty))))))))

let Data_NonEmpty_foldableWithIndexNonEmpty  = (fun (dictFoldableWithIndex: obj) -> (let foldMapWithIndex = (sharpurs_apply (box (Data_FoldableWithIndex_foldMapWithIndex)) (box (dictFoldableWithIndex))) in let foldlWithIndex = (sharpurs_apply (box (Data_FoldableWithIndex_foldlWithIndex)) (box (dictFoldableWithIndex))) in let foldrWithIndex = (sharpurs_apply (box (Data_FoldableWithIndex_foldrWithIndex)) (box (dictFoldableWithIndex))) in let foldableNonEmpty1 = (sharpurs_apply (box (Data_NonEmpty_foldableNonEmpty)) (box ((sharpurs_apply (box ((Map.find "Foldable0" (unbox<Map<string, obj>> (dictFoldableWithIndex))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_FoldableWithIndex_FoldableWithIndexusd_Dict)) (box ((Map.add "foldMapWithIndex" (box ((fun (dictMonoid: obj) -> (let append1 = (sharpurs_apply (box (Data_Semigroup_append)) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> (dictMonoid))))) (box (Prim_undefined)))))) in let foldMapWithIndex1 = (sharpurs_apply (box (foldMapWithIndex)) (box (dictMonoid))) in (fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, Data_NonEmpty_NonEmptyusd_Ctor(a, fa)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (append1)) (box ((sharpurs_apply (box ((sharpurs_apply (box (f1)) (box ((box Data_Maybe_Nothingusd_Ctor)))))) (box (a)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (foldMapWithIndex1)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_NonEmpty_compose)) (box (f1))))) (box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))))))) (box (fa))))))))))))))) (Map.add "foldlWithIndex" (box ((fun (f: obj) -> (fun (b: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (b)), (unbox (v)))) with | (f1, b1, Data_NonEmpty_NonEmptyusd_Ctor(a, fa)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (foldlWithIndex)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_NonEmpty_compose)) (box (f1))))) (box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (f1)) (box ((box Data_Maybe_Nothingusd_Ctor)))))) (box (b1))))) (box (a)))))))) (box (fa))))))))))) (Map.add "foldrWithIndex" (box ((fun (f: obj) -> (fun (b: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (b)), (unbox (v)))) with | (f1, b1, Data_NonEmpty_NonEmptyusd_Ctor(a, fa)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (f1)) (box ((box Data_Maybe_Nothingusd_Ctor)))))) (box (a))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (foldrWithIndex)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_NonEmpty_compose)) (box (f1))))) (box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))))))) (box (b1))))) (box (fa)))))))))))))) (Map.add "Foldable0" (box ((fun (_: obj) -> foldableNonEmpty1))) Map.empty)))))))))

let Data_NonEmpty_traversableNonEmpty  = (fun (dictTraversable: obj) -> (let sequence = (sharpurs_apply (box (Data_Traversable_sequence)) (box (dictTraversable))) in let traverse = (sharpurs_apply (box (Data_Traversable_traverse)) (box (dictTraversable))) in let functorNonEmpty1 = (sharpurs_apply (box (Data_NonEmpty_functorNonEmpty)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (dictTraversable))))) (box (Prim_undefined)))))) in let foldableNonEmpty1 = (sharpurs_apply (box (Data_NonEmpty_foldableNonEmpty)) (box ((sharpurs_apply (box ((Map.find "Foldable1" (unbox<Map<string, obj>> (dictTraversable))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Traversable_Traversableusd_Dict)) (box ((Map.add "sequence" (box ((fun (dictApplicative: obj) -> (let Apply0 = (sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> (dictApplicative))))) (box (Prim_undefined))) in let apply = (sharpurs_apply (box (Control_Apply_apply)) (box (Apply0))) in let map2 = (sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (Apply0))))) (box (Prim_undefined)))))) in let sequence1 = (sharpurs_apply (box (sequence)) (box (dictApplicative))) in (fun (v: obj) -> (match ((unbox (v))) with | Data_NonEmpty_NonEmptyusd_Ctor(a, fa) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (apply)) (box ((sharpurs_apply (box ((sharpurs_apply (box (map2)) (box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2)))))))))) (box (a)))))))) (box ((sharpurs_apply (box (sequence1)) (box (fa)))))))))))))) (Map.add "traverse" (box ((fun (dictApplicative: obj) -> (let Apply0 = (sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> (dictApplicative))))) (box (Prim_undefined))) in let apply = (sharpurs_apply (box (Control_Apply_apply)) (box (Apply0))) in let map2 = (sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (Apply0))))) (box (Prim_undefined)))))) in let traverse1 = (sharpurs_apply (box (traverse)) (box (dictApplicative))) in (fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, Data_NonEmpty_NonEmptyusd_Ctor(a, fa)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (apply)) (box ((sharpurs_apply (box ((sharpurs_apply (box (map2)) (box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2)))))))))) (box ((sharpurs_apply (box (f1)) (box (a))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (traverse1)) (box (f1))))) (box (fa))))))))))))))) (Map.add "Functor0" (box ((fun (_: obj) -> functorNonEmpty1))) (Map.add "Foldable1" (box ((fun (_: obj) -> foldableNonEmpty1))) Map.empty)))))))))

let Data_NonEmpty_traversableWithIndexNonEmpty  = (fun (dictTraversableWithIndex: obj) -> (let traverseWithIndex = (sharpurs_apply (box (Data_TraversableWithIndex_traverseWithIndex)) (box (dictTraversableWithIndex))) in let functorWithIndex1 = (sharpurs_apply (box (Data_NonEmpty_functorWithIndex)) (box ((sharpurs_apply (box ((Map.find "FunctorWithIndex0" (unbox<Map<string, obj>> (dictTraversableWithIndex))))) (box (Prim_undefined)))))) in let foldableWithIndexNonEmpty1 = (sharpurs_apply (box (Data_NonEmpty_foldableWithIndexNonEmpty)) (box ((sharpurs_apply (box ((Map.find "FoldableWithIndex1" (unbox<Map<string, obj>> (dictTraversableWithIndex))))) (box (Prim_undefined)))))) in let traversableNonEmpty1 = (sharpurs_apply (box (Data_NonEmpty_traversableNonEmpty)) (box ((sharpurs_apply (box ((Map.find "Traversable2" (unbox<Map<string, obj>> (dictTraversableWithIndex))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_TraversableWithIndex_TraversableWithIndexusd_Dict)) (box ((Map.add "traverseWithIndex" (box ((fun (dictApplicative: obj) -> (let Apply0 = (sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> (dictApplicative))))) (box (Prim_undefined))) in let apply = (sharpurs_apply (box (Control_Apply_apply)) (box (Apply0))) in let map2 = (sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (Apply0))))) (box (Prim_undefined)))))) in let traverseWithIndex1 = (sharpurs_apply (box (traverseWithIndex)) (box (dictApplicative))) in (fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, Data_NonEmpty_NonEmptyusd_Ctor(a, fa)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (apply)) (box ((sharpurs_apply (box ((sharpurs_apply (box (map2)) (box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2)))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (f1)) (box ((box Data_Maybe_Nothingusd_Ctor)))))) (box (a))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (traverseWithIndex1)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_NonEmpty_compose)) (box (f1))))) (box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))))))) (box (fa))))))))))))))) (Map.add "FunctorWithIndex0" (box ((fun (_: obj) -> functorWithIndex1))) (Map.add "FoldableWithIndex1" (box ((fun (_: obj) -> foldableWithIndexNonEmpty1))) (Map.add "Traversable2" (box ((fun (_: obj) -> traversableNonEmpty1))) Map.empty)))))))))

let Data_NonEmpty_foldable1NonEmpty  = (fun (dictFoldable: obj) -> (let foldl = (sharpurs_apply (box (Data_Foldable_foldl)) (box (dictFoldable))) in let foldr = (sharpurs_apply (box (Data_Foldable_foldr)) (box (dictFoldable))) in let foldableNonEmpty1 = (sharpurs_apply (box (Data_NonEmpty_foldableNonEmpty)) (box (dictFoldable))) in (sharpurs_apply (box (Data_Semigroup_Foldable_Foldable1usd_Dict)) (box ((Map.add "foldMap1" (box ((fun (dictSemigroup: obj) -> (let append1 = (sharpurs_apply (box (Data_Semigroup_append)) (box (dictSemigroup))) in (fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, Data_NonEmpty_NonEmptyusd_Ctor(a, fa)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (foldl)) (box ((fun (s: obj) -> (fun (a1: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (append1)) (box (s))))) (box ((sharpurs_apply (box (f1)) (box (a1))))))))))))) (box ((sharpurs_apply (box (f1)) (box (a)))))))) (box (fa)))))))))))) (Map.add "foldr1" (box ((fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, Data_NonEmpty_NonEmptyusd_Ctor(a, fa)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Maybe_maybe)) (box (a))))) (box ((sharpurs_apply (box (f1)) (box (a)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (foldr)) (box ((fun (a1: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_NonEmpty_compose)) (box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Maybe_maybe)) (box (a1))))) (box ((sharpurs_apply (box (f1)) (box (a1))))))))))))))) (box ((box Data_Maybe_Nothingusd_Ctor)))))) (box (fa))))))))))))) (Map.add "foldl1" (box ((fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, Data_NonEmpty_NonEmptyusd_Ctor(a, fa)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (foldl)) (box (f1))))) (box (a))))) (box (fa)))))))))) (Map.add "Foldable0" (box ((fun (_: obj) -> foldableNonEmpty1))) Map.empty)))))))))

let Data_NonEmpty_foldl1  = (fun (dictFoldable: obj) -> (sharpurs_apply (box (Data_Semigroup_Foldable_foldl1)) (box ((sharpurs_apply (box (Data_NonEmpty_foldable1NonEmpty)) (box (dictFoldable)))))))

let Data_NonEmpty_eqNonEmpty  = (fun (dictEq1: obj) -> (let eq1 = (sharpurs_apply (box (Data_Eq_eq1)) (box (dictEq1))) in (fun (dictEq: obj) -> (let eq = (sharpurs_apply (box (Data_Eq_eq)) (box (dictEq))) in let eq11 = (sharpurs_apply (box (eq1)) (box (dictEq))) in (sharpurs_apply (box (Data_Eq_Equsd_Dict)) (box ((Map.add "eq" (box ((fun (x: obj) -> (fun (y: obj) -> (match (((unbox (x)), (unbox (y)))) with | (Data_NonEmpty_NonEmptyusd_Ctor(l, l1), Data_NonEmpty_NonEmptyusd_Ctor(r, r1)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_NonEmpty_conj)) (box ((sharpurs_apply (box ((sharpurs_apply (box (eq)) (box (l))))) (box (r)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (eq11)) (box (l1))))) (box (r1))))))))))))) Map.empty))))))))

let Data_NonEmpty_ordNonEmpty  = (fun (dictOrd1: obj) -> (let compare1 = (sharpurs_apply (box (Data_Ord_compare1)) (box (dictOrd1))) in let eqNonEmpty1 = (sharpurs_apply (box (Data_NonEmpty_eqNonEmpty)) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> (dictOrd1))))) (box (Prim_undefined)))))) in (fun (dictOrd: obj) -> (let compare = (sharpurs_apply (box (Data_Ord_compare)) (box (dictOrd))) in let compare11 = (sharpurs_apply (box (compare1)) (box (dictOrd))) in let eqNonEmpty2 = (sharpurs_apply (box (eqNonEmpty1)) (box ((sharpurs_apply (box ((Map.find "Eq0" (unbox<Map<string, obj>> (dictOrd))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Ord_Ordusd_Dict)) (box ((Map.add "compare" (box ((fun (x: obj) -> (fun (y: obj) -> (match (((unbox (x)), (unbox (y)))) with | (Data_NonEmpty_NonEmptyusd_Ctor(l, l1), Data_NonEmpty_NonEmptyusd_Ctor(r, r1)) -> (box ((let v = (sharpurs_apply (box ((sharpurs_apply (box (compare)) (box (l))))) (box (r))) in (match ((unbox (v))) with | Data_Ordering_LTusd_Ctor -> (box ((box Data_Ordering_LTusd_Ctor))) | Data_Ordering_GTusd_Ctor -> (box ((box Data_Ordering_GTusd_Ctor))) | _ -> (box ((sharpurs_apply (box ((sharpurs_apply (box (compare11)) (box (l1))))) (box (r1)))))))))))))) (Map.add "Eq0" (box ((fun (_: obj) -> eqNonEmpty2))) Map.empty)))))))))

let Data_NonEmpty_eq1NonEmpty  = (fun (dictEq1: obj) -> (let eqNonEmpty1 = (sharpurs_apply (box (Data_NonEmpty_eqNonEmpty)) (box (dictEq1))) in (sharpurs_apply (box (Data_Eq_Eq1usd_Dict)) (box ((Map.add "eq1" (box ((fun (dictEq: obj) -> (sharpurs_apply (box (Data_Eq_eq)) (box ((sharpurs_apply (box (eqNonEmpty1)) (box (dictEq))))))))) Map.empty))))))

let Data_NonEmpty_ord1NonEmpty  = (fun (dictOrd1: obj) -> (let ordNonEmpty1 = (sharpurs_apply (box (Data_NonEmpty_ordNonEmpty)) (box (dictOrd1))) in let eq1NonEmpty1 = (sharpurs_apply (box (Data_NonEmpty_eq1NonEmpty)) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> (dictOrd1))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Ord_Ord1usd_Dict)) (box ((Map.add "compare1" (box ((fun (dictOrd: obj) -> (sharpurs_apply (box (Data_Ord_compare)) (box ((sharpurs_apply (box (ordNonEmpty1)) (box (dictOrd))))))))) (Map.add "Eq10" (box ((fun (_: obj) -> eq1NonEmpty1))) Map.empty)))))))
