[<AutoOpen>]
module PureScript_Data_Functor_Compose

open System
open System.Collections.Generic

let Data_Functor_Compose_append  = (sharpurs_apply (box (Data_Semigroup_append)) (box (Data_Semigroup_semigroupString)))

let Data_Functor_Compose_compose  = (sharpurs_apply (box (Control_Semigroupoid_compose)) (box (Control_Semigroupoid_semigroupoidFn)))

let Data_Functor_Compose_Compose  = (fun (x: obj) -> x)

let Data_Functor_Compose_showCompose  = (fun (dictShow: obj) -> (let show = (sharpurs_apply (box (Data_Show_show)) (box (dictShow))) in (sharpurs_apply (box (Data_Show_Showusd_Dict)) (box ((Map.add "show" (box ((fun (v: obj) -> (match ((unbox (v))) with | fga -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Compose_append)) (box ((box "(Compose ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Compose_append)) (box ((sharpurs_apply (box (show)) (box (fga)))))))) (box ((box ")"))))))))))))) Map.empty))))))

let Data_Functor_Compose_newtypeCompose  = (sharpurs_apply (box (Data_Newtype_Newtypeusd_Dict)) (box ((Map.add "Coercible0" (box ((fun (_: obj) -> Prim_undefined))) Map.empty))))

let Data_Functor_Compose_functorCompose  = (fun (dictFunctor: obj) -> (let map = (sharpurs_apply (box (Data_Functor_map)) (box (dictFunctor))) in (fun (dictFunctor1: obj) -> (let map1 = (sharpurs_apply (box (Data_Functor_map)) (box (dictFunctor1))) in (sharpurs_apply (box (Data_Functor_Functorusd_Dict)) (box ((Map.add "map" (box ((fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, fga) -> (box ((sharpurs_apply (box (Data_Functor_Compose_Compose)) (box ((sharpurs_apply (box ((sharpurs_apply (box (map)) (box ((sharpurs_apply (box (map1)) (box (f1)))))))) (box (fga))))))))))))) Map.empty))))))))

let Data_Functor_Compose_eqCompose  = (fun (dictEq1: obj) -> (let eq1 = (sharpurs_apply (box (Data_Eq_eq1)) (box (dictEq1))) in (fun (dictEq11: obj) -> (let eqApp = (sharpurs_apply (box (Data_Functor_App_eqApp)) (box (dictEq11))) in (fun (dictEq: obj) -> (let eq11 = (sharpurs_apply (box (eq1)) (box ((sharpurs_apply (box (eqApp)) (box (dictEq)))))) in (sharpurs_apply (box (Data_Eq_Equsd_Dict)) (box ((Map.add "eq" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (fga1, fga2) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (eq11)) (box ((sharpurs_apply (box (Data_Functor_App_hoistLiftApp)) (box (fga1)))))))) (box ((sharpurs_apply (box (Data_Functor_App_hoistLiftApp)) (box (fga2))))))))))))) Map.empty))))))))))

let Data_Functor_Compose_ordCompose  = (fun (dictOrd1: obj) -> (let compare1 = (sharpurs_apply (box (Data_Ord_compare1)) (box (dictOrd1))) in let eqCompose1 = (sharpurs_apply (box (Data_Functor_Compose_eqCompose)) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> (dictOrd1))))) (box (Prim_undefined)))))) in (fun (dictOrd11: obj) -> (let ordApp = (sharpurs_apply (box (Data_Functor_App_ordApp)) (box (dictOrd11))) in let eqCompose2 = (sharpurs_apply (box (eqCompose1)) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> (dictOrd11))))) (box (Prim_undefined)))))) in (fun (dictOrd: obj) -> (let compare11 = (sharpurs_apply (box (compare1)) (box ((sharpurs_apply (box (ordApp)) (box (dictOrd)))))) in let eqCompose3 = (sharpurs_apply (box (eqCompose2)) (box ((sharpurs_apply (box ((Map.find "Eq0" (unbox<Map<string, obj>> (dictOrd))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Ord_Ordusd_Dict)) (box ((Map.add "compare" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (fga1, fga2) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (compare11)) (box ((sharpurs_apply (box (Data_Functor_App_hoistLiftApp)) (box (fga1)))))))) (box ((sharpurs_apply (box (Data_Functor_App_hoistLiftApp)) (box (fga2))))))))))))) (Map.add "Eq0" (box ((fun (_: obj) -> eqCompose3))) Map.empty)))))))))))

let Data_Functor_Compose_eq1Compose  = (fun (dictEq1: obj) -> (let eqCompose1 = (sharpurs_apply (box (Data_Functor_Compose_eqCompose)) (box (dictEq1))) in (fun (dictEq11: obj) -> (let eqCompose2 = (sharpurs_apply (box (eqCompose1)) (box (dictEq11))) in (sharpurs_apply (box (Data_Eq_Eq1usd_Dict)) (box ((Map.add "eq1" (box ((fun (dictEq: obj) -> (sharpurs_apply (box (Data_Eq_eq)) (box ((sharpurs_apply (box (eqCompose2)) (box (dictEq))))))))) Map.empty))))))))

let Data_Functor_Compose_ord1Compose  = (fun (dictOrd1: obj) -> (let ordCompose1 = (sharpurs_apply (box (Data_Functor_Compose_ordCompose)) (box (dictOrd1))) in let eq1Compose1 = (sharpurs_apply (box (Data_Functor_Compose_eq1Compose)) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> (dictOrd1))))) (box (Prim_undefined)))))) in (fun (dictOrd11: obj) -> (let ordCompose2 = (sharpurs_apply (box (ordCompose1)) (box (dictOrd11))) in let eq1Compose2 = (sharpurs_apply (box (eq1Compose1)) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> (dictOrd11))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Ord_Ord1usd_Dict)) (box ((Map.add "compare1" (box ((fun (dictOrd: obj) -> (sharpurs_apply (box (Data_Ord_compare)) (box ((sharpurs_apply (box (ordCompose2)) (box (dictOrd))))))))) (Map.add "Eq10" (box ((fun (_: obj) -> eq1Compose2))) Map.empty)))))))))

let Data_Functor_Compose_bihoistCompose  = (fun (dictFunctor: obj) -> (let map = (sharpurs_apply (box (Data_Functor_map)) (box (dictFunctor))) in (fun (natF: obj) -> (fun (natG: obj) -> (fun (v: obj) -> (match (((unbox (natF)), (unbox (natG)), (unbox (v)))) with | (natF1, natG1, fga) -> (box ((sharpurs_apply (box (Data_Functor_Compose_Compose)) (box ((sharpurs_apply (box (natF1)) (box ((sharpurs_apply (box ((sharpurs_apply (box (map)) (box (natG1))))) (box (fga)))))))))))))))))

let Data_Functor_Compose_applyCompose  = (fun (dictApply: obj) -> (let apply = (sharpurs_apply (box (Control_Apply_apply)) (box (dictApply))) in let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (dictApply))))) (box (Prim_undefined))) in let map = (sharpurs_apply (box (Data_Functor_map)) (box (Functor0))) in let functorCompose1 = (sharpurs_apply (box (Data_Functor_Compose_functorCompose)) (box (Functor0))) in (fun (dictApply1: obj) -> (let apply1 = (sharpurs_apply (box (Control_Apply_apply)) (box (dictApply1))) in let functorCompose2 = (sharpurs_apply (box (functorCompose1)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (dictApply1))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Control_Apply_Applyusd_Dict)) (box ((Map.add "apply" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (f, x) -> (box ((sharpurs_apply (box (Data_Functor_Compose_Compose)) (box ((sharpurs_apply (box ((sharpurs_apply (box (apply)) (box ((sharpurs_apply (box ((sharpurs_apply (box (map)) (box (apply1))))) (box (f)))))))) (box (x))))))))))))) (Map.add "Functor0" (box ((fun (_: obj) -> functorCompose2))) Map.empty)))))))))

let Data_Functor_Compose_applicativeCompose  = (fun (dictApplicative: obj) -> (let pure_ = (sharpurs_apply (box (Control_Applicative_pure)) (box (dictApplicative))) in let applyCompose1 = (sharpurs_apply (box (Data_Functor_Compose_applyCompose)) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> (dictApplicative))))) (box (Prim_undefined)))))) in (fun (dictApplicative1: obj) -> (let applyCompose2 = (sharpurs_apply (box (applyCompose1)) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> (dictApplicative1))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Control_Applicative_Applicativeusd_Dict)) (box ((Map.add "pure" (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Compose_compose)) (box (Data_Functor_Compose_Compose))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Compose_compose)) (box (pure_))))) (box ((sharpurs_apply (box (Control_Applicative_pure)) (box (dictApplicative1))))))))))) (Map.add "Apply0" (box ((fun (_: obj) -> applyCompose2))) Map.empty)))))))))

let Data_Functor_Compose_altCompose  = (fun (dictAlt: obj) -> (let alt = (sharpurs_apply (box (Control_Alt_alt)) (box (dictAlt))) in let functorCompose1 = (sharpurs_apply (box (Data_Functor_Compose_functorCompose)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (dictAlt))))) (box (Prim_undefined)))))) in (fun (dictFunctor: obj) -> (let functorCompose2 = (sharpurs_apply (box (functorCompose1)) (box (dictFunctor))) in (sharpurs_apply (box (Control_Alt_Altusd_Dict)) (box ((Map.add "alt" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (a, b) -> (box ((sharpurs_apply (box (Data_Functor_Compose_Compose)) (box ((sharpurs_apply (box ((sharpurs_apply (box (alt)) (box (a))))) (box (b))))))))))))) (Map.add "Functor0" (box ((fun (_: obj) -> functorCompose2))) Map.empty)))))))))

let Data_Functor_Compose_plusCompose  = (fun (dictPlus: obj) -> (let empty = (sharpurs_apply (box (Control_Plus_empty)) (box (dictPlus))) in let altCompose1 = (sharpurs_apply (box (Data_Functor_Compose_altCompose)) (box ((sharpurs_apply (box ((Map.find "Alt0" (unbox<Map<string, obj>> (dictPlus))))) (box (Prim_undefined)))))) in (fun (dictFunctor: obj) -> (let altCompose2 = (sharpurs_apply (box (altCompose1)) (box (dictFunctor))) in (sharpurs_apply (box (Control_Plus_Plususd_Dict)) (box ((Map.add "empty" (box ((sharpurs_apply (box (Data_Functor_Compose_Compose)) (box (empty))))) (Map.add "Alt0" (box ((fun (_: obj) -> altCompose2))) Map.empty)))))))))

let Data_Functor_Compose_alternativeCompose  = (fun (dictAlternative: obj) -> (let applicativeCompose1 = (sharpurs_apply (box (Data_Functor_Compose_applicativeCompose)) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> (dictAlternative))))) (box (Prim_undefined)))))) in let plusCompose1 = (sharpurs_apply (box (Data_Functor_Compose_plusCompose)) (box ((sharpurs_apply (box ((Map.find "Plus1" (unbox<Map<string, obj>> (dictAlternative))))) (box (Prim_undefined)))))) in (fun (dictApplicative: obj) -> (let applicativeCompose2 = (sharpurs_apply (box (applicativeCompose1)) (box (dictApplicative))) in let plusCompose2 = (sharpurs_apply (box (plusCompose1)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> (dictApplicative))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Control_Alternative_Alternativeusd_Dict)) (box ((Map.add "Applicative0" (box ((fun (_: obj) -> applicativeCompose2))) (Map.add "Plus1" (box ((fun (_: obj) -> plusCompose2))) Map.empty)))))))))
