[<AutoOpen>]
module PureScript_Data_Char_Gen

open System
open System.Collections.Generic

let Data_Char_Gen_toEnumWithDefaults  = (sharpurs_apply (box (Data_Enum_toEnumWithDefaults)) (box (Data_Enum_boundedEnumChar)))

let Data_Char_Gen_bottom  = (sharpurs_apply (box (Data_Bounded_bottom)) (box (Data_Bounded_boundedChar)))

let Data_Char_Gen_top  = (sharpurs_apply (box (Data_Bounded_top)) (box (Data_Bounded_boundedChar)))

let Data_Char_Gen_foldable1NonEmpty  = (sharpurs_apply (box (Data_NonEmpty_foldable1NonEmpty)) (box (Data_Foldable_foldableArray)))

let Data_Char_Gen_genUnicodeChar  = (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> (dictMonadGen))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Char_Gen_toEnumWithDefaults)) (box (Data_Char_Gen_bottom))))) (box (Data_Char_Gen_top)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_Class_chooseInt)) (box (dictMonadGen))))) (box ((box 0)))))) (box ((box 65536))))))))

let Data_Char_Gen_genDigitChar  = (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> (dictMonadGen))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Char_Gen_toEnumWithDefaults)) (box (Data_Char_Gen_bottom))))) (box (Data_Char_Gen_top)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_Class_chooseInt)) (box (dictMonadGen))))) (box ((box 48)))))) (box ((box 57))))))))

let Data_Char_Gen_genAsciiChar_prime  = (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> (dictMonadGen))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Char_Gen_toEnumWithDefaults)) (box (Data_Char_Gen_bottom))))) (box (Data_Char_Gen_top)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_Class_chooseInt)) (box (dictMonadGen))))) (box ((box 0)))))) (box ((box 127))))))))

let Data_Char_Gen_genAsciiChar  = (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> (dictMonadGen))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Char_Gen_toEnumWithDefaults)) (box (Data_Char_Gen_bottom))))) (box (Data_Char_Gen_top)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_Class_chooseInt)) (box (dictMonadGen))))) (box ((box 32)))))) (box ((box 127))))))))

let Data_Char_Gen_genAlphaUppercase  = (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> (dictMonadGen))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Char_Gen_toEnumWithDefaults)) (box (Data_Char_Gen_bottom))))) (box (Data_Char_Gen_top)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_Class_chooseInt)) (box (dictMonadGen))))) (box ((box 65)))))) (box ((box 90))))))))

let Data_Char_Gen_genAlphaLowercase  = (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> (dictMonadGen))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Char_Gen_toEnumWithDefaults)) (box (Data_Char_Gen_bottom))))) (box (Data_Char_Gen_top)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_Class_chooseInt)) (box (dictMonadGen))))) (box ((box 97)))))) (box ((box 122))))))))

let Data_Char_Gen_genAlpha  = (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Control_Monad_Gen_oneOf)) (box (dictMonadGen))))) (box (Data_Char_Gen_foldable1NonEmpty))))) (box ((box (Data_NonEmpty_NonEmptyusd_Ctor((sharpurs_apply (box (Data_Char_Gen_genAlphaLowercase)) (box (dictMonadGen))), (box [|(sharpurs_apply (box (Data_Char_Gen_genAlphaUppercase)) (box (dictMonadGen)))|]))))))))
