[<AutoOpen>]
module PureScript_Data_List_Lazy

open System
open System.Collections.Generic

let Data_List_Lazy_apply  = (sharpurs_apply (box (Control_Apply_apply)) (box (Data_Lazy_applyLazy)))

let Data_List_Lazy_map  = (sharpurs_apply (box (Data_Functor_map)) (box (Data_Lazy_functorLazy)))

let Data_List_Lazy_unwrap  = (sharpurs_apply (box (Data_Newtype_unwrap)) (box (Prim_undefined)))

let Data_List_Lazy_sequence  = (sharpurs_apply (box (Data_Traversable_sequence)) (box (Data_List_Lazy_Types_traversableList)))

let Data_List_Lazy_sub  = (sharpurs_apply (box (Data_Ring_sub)) (box (Data_Ring_ringInt)))

let Data_List_Lazy_foldr  = (sharpurs_apply (box (Data_Foldable_foldr)) (box (Data_List_Lazy_Types_foldableList)))

let Data_List_Lazy_map1  = (sharpurs_apply (box (Data_Functor_map)) (box (Data_Maybe_functorMaybe)))

let Data_List_Lazy_compose  = (sharpurs_apply (box (Control_Semigroupoid_compose)) (box (Control_Semigroupoid_semigroupoidFn)))

let Data_List_Lazy_lessThanOrEq  = (sharpurs_apply (box (Data_Ord_lessThanOrEq)) (box (Data_Ord_ordInt)))

let Data_List_Lazy_tailRecM2  = (sharpurs_apply (box (Control_Monad_Rec_Class_tailRecM2)) (box (Control_Monad_Rec_Class_monadRecMaybe)))

let Data_List_Lazy_append  = (sharpurs_apply (box (Data_Semigroup_append)) (box (Data_Semigroup_semigroupString)))

let Data_List_Lazy_defer  = (sharpurs_apply (box (Control_Lazy_defer)) (box (Data_List_Lazy_Types_lazyList)))

let Data_List_Lazy_foldl  = (sharpurs_apply (box (Data_Foldable_foldl)) (box (Data_List_Lazy_Types_foldableList)))

let Data_List_Lazy_lessThan  = (sharpurs_apply (box (Data_Ord_lessThan)) (box (Data_Ord_ordInt)))

let Data_List_Lazy_one  = (sharpurs_apply (box (Data_Semiring_one)) (box (Data_Semiring_semiringInt)))

let Data_List_Lazy_fix  = (sharpurs_apply (box (Control_Lazy_fix)) (box (Data_List_Lazy_Types_lazyList)))

let Data_List_Lazy_greaterThan  = (sharpurs_apply (box (Data_Ord_greaterThan)) (box (Data_Ord_ordInt)))

let Data_List_Lazy_greaterThanOrEq  = (sharpurs_apply (box (Data_Ord_greaterThanOrEq)) (box (Data_Ord_ordInt)))

let Data_List_Lazy_unfoldr  = (sharpurs_apply (box (Data_Unfoldable_unfoldr)) (box (Data_List_Lazy_Types_unfoldableList)))

let Data_List_Lazy_add  = (sharpurs_apply (box (Data_Semiring_add)) (box (Data_Semiring_semiringInt)))

let Data_List_Lazy_map2  = (sharpurs_apply (box (Data_Functor_map)) (box (Data_List_Lazy_Types_functorList)))

let Data_List_Lazy_bind  = (sharpurs_apply (box (Control_Bind_bind)) (box (Data_Maybe_bindMaybe)))

let Data_List_Lazy_pure  = (sharpurs_apply (box (Control_Applicative_pure)) (box (Data_Maybe_applicativeMaybe)))

let Data_List_Lazy_any  = (sharpurs_apply (box ((sharpurs_apply (box (Data_Foldable_any)) (box (Data_List_Lazy_Types_foldableList))))) (box (Data_HeytingAlgebra_heytingAlgebraBoolean)))

let Data_List_Lazy_not  = (sharpurs_apply (box (Data_HeytingAlgebra_not)) (box (Data_HeytingAlgebra_heytingAlgebraBoolean)))

let Data_List_Lazy_append1  = (sharpurs_apply (box (Data_Semigroup_append)) (box (Data_List_Lazy_Types_semigroupList)))

let Data_List_Lazy_bind1  = (sharpurs_apply (box (Control_Bind_bind)) (box (Data_List_Lazy_Types_bindList)))

let Data_List_Lazy_identity  = (sharpurs_apply (box (Control_Category_identity)) (box (Control_Category_categoryFn)))

let Data_List_Lazy_Pattern  = (fun (x: obj) -> x)

let rec Data_List_Lazy_zipWith  = (fun (f: obj) -> (fun (xs: obj) -> (fun (ys: obj) -> (let go = (fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (Data_List_Lazy_Types_Nilusd_Ctor, _) -> (box ((box Data_List_Lazy_Types_Nilusd_Ctor))) | (_, Data_List_Lazy_Types_Nilusd_Ctor) -> (box ((box Data_List_Lazy_Types_Nilusd_Ctor))) | (Data_List_Lazy_Types_Consusd_Ctor(a, as_), Data_List_Lazy_Types_Consusd_Ctor(b, bs)) -> (box ((box (Data_List_Lazy_Types_Consusd_Ctor((sharpurs_apply (box ((sharpurs_apply (box (f)) (box (a))))) (box (b))), (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_zipWith)) (box (f))))) (box (as_))))) (box (bs))))))))))) in (sharpurs_apply (box (Data_List_Lazy_Types_List)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_apply)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_map)) (box (go))))) (box ((sharpurs_apply (box (Data_List_Lazy_unwrap)) (box (xs))))))))))) (box ((sharpurs_apply (box (Data_List_Lazy_unwrap)) (box (ys)))))))))))))

let Data_List_Lazy_zipWithA  = (fun (dictApplicative: obj) -> (let sequence1 = (sharpurs_apply (box (Data_List_Lazy_sequence)) (box (dictApplicative))) in (fun (f: obj) -> (fun (xs: obj) -> (fun (ys: obj) -> (sharpurs_apply (box (sequence1)) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_zipWith)) (box (f))))) (box (xs))))) (box (ys)))))))))))

let Data_List_Lazy_zip  = (sharpurs_apply (box (Data_List_Lazy_zipWith)) (box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2))))))))

let rec Data_List_Lazy_updateAt  = (fun (n: obj) -> (fun (x: obj) -> (fun (xs: obj) -> (let go = (fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (_, Data_List_Lazy_Types_Nilusd_Ctor) -> (box ((box Data_List_Lazy_Types_Nilusd_Ctor))) | (LitInt 0 (), Data_List_Lazy_Types_Consusd_Ctor(_, ys)) -> (box ((box (Data_List_Lazy_Types_Consusd_Ctor(x, ys))))) | (n_prime, Data_List_Lazy_Types_Consusd_Ctor(y, ys)) -> (box ((box (Data_List_Lazy_Types_Consusd_Ctor(y, (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_updateAt)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_sub)) (box (n_prime))))) (box ((box 1))))))))) (box (x))))) (box (ys))))))))))) in (sharpurs_apply (box (Data_List_Lazy_Types_List)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_map)) (box ((sharpurs_apply (box (go)) (box (n)))))))) (box ((sharpurs_apply (box (Data_List_Lazy_unwrap)) (box (xs)))))))))))))

let Data_List_Lazy_unzip  = (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_foldr)) (box ((fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(a, b) -> (box ((fun (v1: obj) -> (match ((unbox (v1))) with | Data_Tuple_Tupleusd_Ctor(as_, bs) -> (box ((box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_Types_cons)) (box (a))))) (box (as_))), (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_Types_cons)) (box (b))))) (box (bs))))))))))))))))))) (box ((box (Data_Tuple_Tupleusd_Ctor(Data_List_Lazy_Types_nil, Data_List_Lazy_Types_nil))))))

let Data_List_Lazy_uncons  = (fun (xs: obj) -> (let v = (sharpurs_apply (box (Data_List_Lazy_Types_step)) (box (xs))) in (match ((unbox (v))) with | Data_List_Lazy_Types_Nilusd_Ctor -> (box ((box Data_Maybe_Nothingusd_Ctor))) | Data_List_Lazy_Types_Consusd_Ctor(x, xs_prime) -> (box ((box (Data_Maybe_Justusd_Ctor((Map.add "head" (box (x)) (Map.add "tail" (box (xs_prime)) Map.empty))))))))))

let Data_List_Lazy_toUnfoldable  = (fun (dictUnfoldable: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Unfoldable_unfoldr)) (box (dictUnfoldable))))) (box ((fun (xs: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_map1)) (box ((fun (rec_: obj) -> (box (Data_Tuple_Tupleusd_Ctor((Map.find "head" (unbox<Map<string, obj>> (rec_))), (Map.find "tail" (unbox<Map<string, obj>> (rec_)))))))))))) (box ((sharpurs_apply (box (Data_List_Lazy_uncons)) (box (xs)))))))))))

let rec Data_List_Lazy_takeWhile  = (fun (p: obj) -> (let go = (fun (v: obj) -> (match ((unbox (v))) with | Data_List_Lazy_Types_Consusd_Ctor(x, xs) when (unbox (sharpurs_apply (box (p)) (box (x)))) -> (box ((box (Data_List_Lazy_Types_Consusd_Ctor(x, (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_takeWhile)) (box (p))))) (box (xs)))))))) | _ -> (box ((box Data_List_Lazy_Types_Nilusd_Ctor))))) in (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_compose)) (box (Data_List_Lazy_Types_List))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_compose)) (box ((sharpurs_apply (box (Data_List_Lazy_map)) (box (go)))))))) (box (Data_List_Lazy_unwrap))))))))

let rec Data_List_Lazy_take  = (fun (n: obj) -> (let go = (fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (_, Data_List_Lazy_Types_Nilusd_Ctor) -> (box ((box Data_List_Lazy_Types_Nilusd_Ctor))) | (n_prime, Data_List_Lazy_Types_Consusd_Ctor(x, xs)) -> (box ((box (Data_List_Lazy_Types_Consusd_Ctor(x, (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_take)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_sub)) (box (n_prime))))) (box ((box 1))))))))) (box (xs))))))))))) in (match ((unbox ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_lessThanOrEq)) (box (n))))) (box ((box 0))))))) with | LitBool true () -> (box ((sharpurs_apply (box (Data_Function_const)) (box (Data_List_Lazy_Types_nil))))) | _ -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_compose)) (box (Data_List_Lazy_Types_List))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_compose)) (box ((sharpurs_apply (box (Data_List_Lazy_map)) (box ((sharpurs_apply (box (go)) (box (n))))))))))) (box (Data_List_Lazy_unwrap)))))))))))

let Data_List_Lazy_tail  = (fun (xs: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_map1)) (box ((fun (v: obj) -> (Map.find "tail" (unbox<Map<string, obj>> (v))))))))) (box ((sharpurs_apply (box (Data_List_Lazy_uncons)) (box (xs)))))))

let Data_List_Lazy_stripPrefix  = (fun (dictEq: obj) -> (let eq = (sharpurs_apply (box (Data_Eq_eq)) (box (dictEq))) in (fun (v: obj) -> (fun (s: obj) -> (match (((unbox (v)), (unbox (s)))) with | (p_prime, s1) -> (box ((let go = (fun (prefix: obj) -> (fun (input: obj) -> (let v1 = (sharpurs_apply (box (Data_List_Lazy_Types_step)) (box (prefix))) in (match ((unbox (v1))) with | Data_List_Lazy_Types_Nilusd_Ctor -> (box ((box (Data_Maybe_Justusd_Ctor((box (Control_Monad_Rec_Class_Doneusd_Ctor(input)))))))) | Data_List_Lazy_Types_Consusd_Ctor(p, ps) -> (box ((let v2 = (sharpurs_apply (box (Data_List_Lazy_Types_step)) (box (input))) in (match ((unbox (v2))) with | Data_List_Lazy_Types_Consusd_Ctor(i, is) when (unbox (sharpurs_apply (box ((sharpurs_apply (box (eq)) (box (p))))) (box (i)))) -> (box ((box (Data_Maybe_Justusd_Ctor((box (Control_Monad_Rec_Class_Loopusd_Ctor((Map.add "a" (box (ps)) (Map.add "b" (box (is)) Map.empty)))))))))) | _ -> (box ((box Data_Maybe_Nothingusd_Ctor))))))))))) in (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_tailRecM2)) (box (go))))) (box (p_prime))))) (box (s1)))))))))))

let rec Data_List_Lazy_span  = (fun (p: obj) -> (fun (xs: obj) -> (let v = (sharpurs_apply (box (Data_List_Lazy_uncons)) (box (xs))) in (match ((unbox (v))) with | Data_Maybe_Justusd_Ctor(Unbox((HasProp "head" (x) & HasProp "tail" (xs_prime)))) when (unbox (sharpurs_apply (box (p)) (box (x)))) -> (box ((let v1 = (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_span)) (box (p))))) (box (xs_prime))) in (match ((unbox (v1))) with | (HasProp "init" (ys) & HasProp "rest" (zs)) -> (box ((Map.add "init" (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_Types_cons)) (box (x))))) (box (ys))))) (Map.add "rest" (box (zs)) Map.empty)))))))) | _ -> (box ((Map.add "init" (box (Data_List_Lazy_Types_nil)) (Map.add "rest" (box (xs)) Map.empty))))))))

let Data_List_Lazy_snoc  = (fun (xs: obj) -> (fun (x: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_foldr)) (box (Data_List_Lazy_Types_cons))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_Types_cons)) (box (x))))) (box (Data_List_Lazy_Types_nil)))))))) (box (xs)))))

let Data_List_Lazy_singleton  = (fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_Types_cons)) (box (a))))) (box (Data_List_Lazy_Types_nil))))

let Data_List_Lazy_showPattern  = (fun (dictShow: obj) -> (let show = (sharpurs_apply (box (Data_Show_show)) (box ((sharpurs_apply (box (Data_List_Lazy_Types_showList)) (box (dictShow)))))) in (sharpurs_apply (box (Data_Show_Showusd_Dict)) (box ((Map.add "show" (box ((fun (v: obj) -> (match ((unbox (v))) with | s -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_append)) (box ((box "(Pattern ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_append)) (box ((sharpurs_apply (box (show)) (box (s)))))))) (box ((box ")"))))))))))))) Map.empty))))))

let rec Data_List_Lazy_scanlLazy  = (fun (f: obj) -> (fun (acc: obj) -> (fun (xs: obj) -> (let go = (fun (v: obj) -> (match ((unbox (v))) with | Data_List_Lazy_Types_Nilusd_Ctor -> (box ((box Data_List_Lazy_Types_Nilusd_Ctor))) | Data_List_Lazy_Types_Consusd_Ctor(x, xs_prime) -> (box ((let acc_prime = (sharpurs_apply (box ((sharpurs_apply (box (f)) (box (acc))))) (box (x))) in (box (Data_List_Lazy_Types_Consusd_Ctor(acc_prime, (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_scanlLazy)) (box (f))))) (box (acc_prime))))) (box (xs_prime))))))))))) in (sharpurs_apply (box (Data_List_Lazy_Types_List)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_map)) (box (go))))) (box ((sharpurs_apply (box (Data_List_Lazy_unwrap)) (box (xs)))))))))))))

let Data_List_Lazy_reverse  = (fun (xs: obj) -> (sharpurs_apply (box (Data_List_Lazy_defer)) (box ((fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_foldl)) (box ((sharpurs_apply (box (Data_Function_flip)) (box (Data_List_Lazy_Types_cons)))))))) (box (Data_List_Lazy_Types_nil))))) (box (xs))))))))

let rec Data_List_Lazy_replicateM  = (fun (dictMonad: obj) -> (let pure1 = (sharpurs_apply (box (Control_Applicative_pure)) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> (dictMonad))))) (box (Prim_undefined)))))) in let bind2 = (sharpurs_apply (box (Control_Bind_bind)) (box ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> (dictMonad))))) (box (Prim_undefined)))))) in (fun (n: obj) -> (fun (m: obj) -> (match (((unbox (n)), (unbox (m)))) with | (n1, m1) when (unbox (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_lessThan)) (box (n1))))) (box (Data_List_Lazy_one)))) -> (box ((sharpurs_apply (box (pure1)) (box (Data_List_Lazy_Types_nil))))) | (n1, m1) when (unbox Data_Boolean_otherwise) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (bind2)) (box (m1))))) (box ((fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (bind2)) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_replicateM)) (box (dictMonad))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_sub)) (box (n1))))) (box (Data_List_Lazy_one)))))))) (box (m1)))))))) (box ((fun (as_: obj) -> (sharpurs_apply (box (pure1)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_Types_cons)) (box (a))))) (box (as_)))))))))))))))))))))

let Data_List_Lazy_repeat  = (fun (x: obj) -> (sharpurs_apply (box (Data_List_Lazy_fix)) (box ((fun (xs: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_Types_cons)) (box (x))))) (box (xs))))))))

let Data_List_Lazy_replicate  = (fun (i: obj) -> (fun (xs: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_take)) (box (i))))) (box ((sharpurs_apply (box (Data_List_Lazy_repeat)) (box (xs))))))))

let Data_List_Lazy_range  = (fun (start: obj) -> (fun (end_: obj) -> (match (((unbox (start)), (unbox (end_)))) with | (start1, end1) when (unbox (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_greaterThan)) (box (start1))))) (box (end1)))) -> (box ((let g = (fun (x: obj) -> (match ((unbox (x))) with | x1 when (unbox (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_greaterThanOrEq)) (box (x1))))) (box (end1)))) -> (box ((box (Data_Maybe_Justusd_Ctor((box (Data_Tuple_Tupleusd_Ctor(x1, (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_sub)) (box (x1))))) (box ((box 1)))))))))))) | x1 when (unbox Data_Boolean_otherwise) -> (box ((box Data_Maybe_Nothingusd_Ctor))))) in (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_unfoldr)) (box (g))))) (box (start1)))))) | (start1, end1) when (unbox Data_Boolean_otherwise) -> (box ((let f = (fun (x: obj) -> (match ((unbox (x))) with | x1 when (unbox (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_lessThanOrEq)) (box (x1))))) (box (end1)))) -> (box ((box (Data_Maybe_Justusd_Ctor((box (Data_Tuple_Tupleusd_Ctor(x1, (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_add)) (box (x1))))) (box ((box 1)))))))))))) | x1 when (unbox Data_Boolean_otherwise) -> (box ((box Data_Maybe_Nothingusd_Ctor))))) in (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_unfoldr)) (box (f))))) (box (start1)))))))))

let Data_List_Lazy_partition  = (fun (f: obj) -> (let go = (fun (x: obj) -> (fun (v: obj) -> (match (((unbox (x)), (unbox (v)))) with | (x1, (HasProp "yes" (ys) & HasProp "no" (ns))) -> (box ((match ((unbox ((sharpurs_apply (box (f)) (box (x1)))))) with | LitBool true () -> (box ((Map.add "yes" (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_Types_cons)) (box (x1))))) (box (ys))))) (Map.add "no" (box (ns)) Map.empty)))) | _ -> (box ((Map.add "yes" (box (ys)) (Map.add "no" (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_Types_cons)) (box (x1))))) (box (ns))))) Map.empty)))))))))) in (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_foldr)) (box (go))))) (box ((Map.add "yes" (box (Data_List_Lazy_Types_nil)) (Map.add "no" (box (Data_List_Lazy_Types_nil)) Map.empty)))))))

let Data_List_Lazy_null  = (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_compose)) (box (Data_Maybe_isNothing))))) (box (Data_List_Lazy_uncons)))

let Data_List_Lazy_nubBy  = (fun (p: obj) -> (let mutable goStep : obj = null in let mutable go : obj = null in goStep <- (fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (_, Data_List_Lazy_Types_Nilusd_Ctor) -> (box ((box Data_List_Lazy_Types_Nilusd_Ctor))) | (s, Data_List_Lazy_Types_Consusd_Ctor(a, as_)) -> (box ((let v2 = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Internal_insertAndLookupBy)) (box (p))))) (box (a))))) (box (s))) in (match ((unbox (v2))) with | (HasProp "found" (found) & HasProp "result" (s_prime)) -> (box ((match ((unbox (found))) with | LitBool true () -> (box ((sharpurs_apply (box (Data_List_Lazy_Types_step)) (box ((sharpurs_apply (box ((sharpurs_apply (box (go)) (box (s_prime))))) (box (as_)))))))) | _ -> (box ((box (Data_List_Lazy_Types_Consusd_Ctor(a, (sharpurs_apply (box ((sharpurs_apply (box (go)) (box (s_prime))))) (box (as_)))))))))))))))))); go <- (fun (s: obj) -> (fun (v: obj) -> (match (((unbox (s)), (unbox (v)))) with | (s1, l) -> (box ((sharpurs_apply (box (Data_List_Lazy_Types_List)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_map)) (box ((sharpurs_apply (box (goStep)) (box (s1)))))))) (box (l))))))))))); (sharpurs_apply (box (go)) (box (Data_List_Internal_emptySet)))))

let Data_List_Lazy_nub  = (fun (dictOrd: obj) -> (sharpurs_apply (box (Data_List_Lazy_nubBy)) (box ((sharpurs_apply (box (Data_Ord_compare)) (box (dictOrd)))))))

let Data_List_Lazy_newtypePattern  = (sharpurs_apply (box (Data_Newtype_Newtypeusd_Dict)) (box ((Map.add "Coercible0" (box ((fun (_: obj) -> Prim_undefined))) Map.empty))))

let rec Data_List_Lazy_mapMaybe  = (fun (f: obj) -> (let mutable go : obj = null in go <- (fun (v: obj) -> (match ((unbox (v))) with | Data_List_Lazy_Types_Nilusd_Ctor -> (box ((box Data_List_Lazy_Types_Nilusd_Ctor))) | Data_List_Lazy_Types_Consusd_Ctor(x, xs) -> (box ((let v1 = (sharpurs_apply (box (f)) (box (x))) in (match ((unbox (v1))) with | Data_Maybe_Nothingusd_Ctor -> (box ((sharpurs_apply (box (go)) (box ((sharpurs_apply (box (Data_List_Lazy_Types_step)) (box (xs)))))))) | Data_Maybe_Justusd_Ctor(y) -> (box ((box (Data_List_Lazy_Types_Consusd_Ctor(y, (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_mapMaybe)) (box (f))))) (box (xs)))))))))))))); (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_compose)) (box (Data_List_Lazy_Types_List))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_compose)) (box ((sharpurs_apply (box (Data_List_Lazy_map)) (box (go)))))))) (box (Data_List_Lazy_unwrap))))))))

let rec Data_List_Lazy_some  = (fun (dictAlternative: obj) -> (let apply1 = (sharpurs_apply (box (Control_Apply_apply)) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> (dictAlternative))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))) in let map3 = (sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Alt0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Plus1" (unbox<Map<string, obj>> (dictAlternative))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))) in (fun (dictLazy: obj) -> (let defer1 = (sharpurs_apply (box (Control_Lazy_defer)) (box (dictLazy))) in (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (apply1)) (box ((sharpurs_apply (box ((sharpurs_apply (box (map3)) (box (Data_List_Lazy_Types_cons))))) (box (v)))))))) (box ((sharpurs_apply (box (defer1)) (box ((fun (v1: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_many)) (box (dictAlternative))))) (box (dictLazy))))) (box (v)))))))))))))))
and Data_List_Lazy_many  = (fun (dictAlternative: obj) -> (let alt = (sharpurs_apply (box (Control_Alt_alt)) (box ((sharpurs_apply (box ((Map.find "Alt0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Plus1" (unbox<Map<string, obj>> (dictAlternative))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))) in let pure1 = (sharpurs_apply (box (Control_Applicative_pure)) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> (dictAlternative))))) (box (Prim_undefined)))))) in (fun (dictLazy: obj) -> (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (alt)) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_some)) (box (dictAlternative))))) (box (dictLazy))))) (box (v)))))))) (box ((sharpurs_apply (box (pure1)) (box (Data_List_Lazy_Types_nil))))))))))

let Data_List_Lazy_length  = (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_foldl)) (box ((fun (l: obj) -> (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_add)) (box (l))))) (box ((box 1))))))))))) (box ((box 0))))

let Data_List_Lazy_last  = (let mutable go : obj = null in go <- (fun (v: obj) -> (match ((unbox (v))) with | Data_List_Lazy_Types_Consusd_Ctor(x, xs) when (unbox (sharpurs_apply (box (Data_List_Lazy_null)) (box (xs)))) -> (box ((box (Data_Maybe_Justusd_Ctor(x))))) | Data_List_Lazy_Types_Consusd_Ctor(x, xs) when (unbox Data_Boolean_otherwise) -> (box ((sharpurs_apply (box (go)) (box ((sharpurs_apply (box (Data_List_Lazy_Types_step)) (box (xs)))))))) | _ -> (box ((box Data_Maybe_Nothingusd_Ctor))))); (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_compose)) (box (go))))) (box (Data_List_Lazy_Types_step))))

let Data_List_Lazy_iterate  = (fun (f: obj) -> (fun (x: obj) -> (sharpurs_apply (box (Data_List_Lazy_fix)) (box ((fun (xs: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_Types_cons)) (box (x))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_map2)) (box (f))))) (box (xs))))))))))))

let rec Data_List_Lazy_insertAt  = (fun (v: obj) -> (fun (v1: obj) -> (fun (v2: obj) -> (match (((unbox (v)), (unbox (v1)), (unbox (v2)))) with | (LitInt 0 (), x, xs) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_Types_cons)) (box (x))))) (box (xs))))) | (n, x, xs) -> (box ((let go = (fun (v3: obj) -> (match ((unbox (v3))) with | Data_List_Lazy_Types_Nilusd_Ctor -> (box ((box (Data_List_Lazy_Types_Consusd_Ctor(x, Data_List_Lazy_Types_nil))))) | Data_List_Lazy_Types_Consusd_Ctor(y, ys) -> (box ((box (Data_List_Lazy_Types_Consusd_Ctor(y, (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_insertAt)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_sub)) (box (n))))) (box ((box 1))))))))) (box (x))))) (box (ys)))))))))) in (sharpurs_apply (box (Data_List_Lazy_Types_List)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_map)) (box (go))))) (box ((sharpurs_apply (box (Data_List_Lazy_unwrap)) (box (xs))))))))))))))))

let Data_List_Lazy_init  = (let mutable go : obj = null in go <- (fun (v: obj) -> (match ((unbox (v))) with | Data_List_Lazy_Types_Consusd_Ctor(x, xs) when (unbox (sharpurs_apply (box (Data_List_Lazy_null)) (box (xs)))) -> (box ((box (Data_Maybe_Justusd_Ctor(Data_List_Lazy_Types_nil))))) | Data_List_Lazy_Types_Consusd_Ctor(x, xs) when (unbox Data_Boolean_otherwise) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_map1)) (box ((sharpurs_apply (box (Data_List_Lazy_Types_cons)) (box (x)))))))) (box ((sharpurs_apply (box (go)) (box ((sharpurs_apply (box (Data_List_Lazy_Types_step)) (box (xs))))))))))) | _ -> (box ((box Data_Maybe_Nothingusd_Ctor))))); (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_compose)) (box (go))))) (box (Data_List_Lazy_Types_step))))

let Data_List_Lazy_index  = (fun (xs: obj) -> (let mutable go : obj = null in go <- (fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (Data_List_Lazy_Types_Nilusd_Ctor, _) -> (box ((box Data_Maybe_Nothingusd_Ctor))) | (Data_List_Lazy_Types_Consusd_Ctor(a, _), LitInt 0 ()) -> (box ((box (Data_Maybe_Justusd_Ctor(a))))) | (Data_List_Lazy_Types_Consusd_Ctor(_, as_), i) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (go)) (box ((sharpurs_apply (box (Data_List_Lazy_Types_step)) (box (as_)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_sub)) (box (i))))) (box ((box 1)))))))))))); (sharpurs_apply (box (go)) (box ((sharpurs_apply (box (Data_List_Lazy_Types_step)) (box (xs))))))))

let Data_List_Lazy_head  = (fun (xs: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_map1)) (box ((fun (v: obj) -> (Map.find "head" (unbox<Map<string, obj>> (v))))))))) (box ((sharpurs_apply (box (Data_List_Lazy_uncons)) (box (xs)))))))

let rec Data_List_Lazy_transpose  = (fun (xs: obj) -> (let v = (sharpurs_apply (box (Data_List_Lazy_uncons)) (box (xs))) in (match ((unbox (v))) with | Data_Maybe_Nothingusd_Ctor -> (box (xs)) | Data_Maybe_Justusd_Ctor(Unbox((HasProp "head" (h) & HasProp "tail" (xss)))) -> (box ((let v1 = (sharpurs_apply (box (Data_List_Lazy_uncons)) (box (h))) in (match ((unbox (v1))) with | Data_Maybe_Nothingusd_Ctor -> (box ((sharpurs_apply (box (Data_List_Lazy_transpose)) (box (xss))))) | Data_Maybe_Justusd_Ctor(Unbox((HasProp "head" (x) & HasProp "tail" (xs_prime)))) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_Types_cons)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_Types_cons)) (box (x))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_mapMaybe)) (box (Data_List_Lazy_head))))) (box (xss))))))))))) (box ((sharpurs_apply (box (Data_List_Lazy_transpose)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_Types_cons)) (box (xs_prime))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_mapMaybe)) (box (Data_List_Lazy_tail))))) (box (xss)))))))))))))))))))))

let rec Data_List_Lazy_groupBy  = (fun (eq: obj) -> (let go = (fun (v: obj) -> (match ((unbox (v))) with | Data_List_Lazy_Types_Nilusd_Ctor -> (box ((box Data_List_Lazy_Types_Nilusd_Ctor))) | Data_List_Lazy_Types_Consusd_Ctor(x, xs) -> (box ((let v1 = (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_span)) (box ((sharpurs_apply (box (eq)) (box (x)))))))) (box (xs))) in (match ((unbox (v1))) with | (HasProp "init" (ys) & HasProp "rest" (zs)) -> (box ((box (Data_List_Lazy_Types_Consusd_Ctor((sharpurs_apply (box (Data_List_Lazy_Types_NonEmptyList)) (box ((sharpurs_apply (box (Data_Lazy_defer)) (box ((fun (v2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(x, ys)))))))))), (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_groupBy)) (box (eq))))) (box (zs)))))))))))))) in (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_compose)) (box (Data_List_Lazy_Types_List))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_compose)) (box ((sharpurs_apply (box (Data_List_Lazy_map)) (box (go)))))))) (box (Data_List_Lazy_unwrap))))))))

let Data_List_Lazy_group  = (fun (dictEq: obj) -> (sharpurs_apply (box (Data_List_Lazy_groupBy)) (box ((sharpurs_apply (box (Data_Eq_eq)) (box (dictEq)))))))

let Data_List_Lazy_fromStep  = (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_compose)) (box (Data_List_Lazy_Types_List))))) (box ((sharpurs_apply (box (Control_Applicative_pure)) (box (Data_Lazy_applicativeLazy))))))

let rec Data_List_Lazy_insertBy  = (fun (cmp: obj) -> (fun (x: obj) -> (fun (xs: obj) -> (let go = (fun (v: obj) -> (match ((unbox (v))) with | Data_List_Lazy_Types_Nilusd_Ctor -> (box ((box (Data_List_Lazy_Types_Consusd_Ctor(x, Data_List_Lazy_Types_nil))))) | (Data_List_Lazy_Types_Consusd_Ctor(y, ys_prime) as ys) -> (box ((let v1 = (sharpurs_apply (box ((sharpurs_apply (box (cmp)) (box (x))))) (box (y))) in (match ((unbox (v1))) with | Data_Ordering_GTusd_Ctor -> (box ((box (Data_List_Lazy_Types_Consusd_Ctor(y, (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_insertBy)) (box (cmp))))) (box (x))))) (box (ys_prime)))))))) | _ -> (box ((box (Data_List_Lazy_Types_Consusd_Ctor(x, (sharpurs_apply (box (Data_List_Lazy_fromStep)) (box (ys)))))))))))))) in (sharpurs_apply (box (Data_List_Lazy_Types_List)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_map)) (box (go))))) (box ((sharpurs_apply (box (Data_List_Lazy_unwrap)) (box (xs)))))))))))))

let Data_List_Lazy_insert  = (fun (dictOrd: obj) -> (sharpurs_apply (box (Data_List_Lazy_insertBy)) (box ((sharpurs_apply (box (Data_Ord_compare)) (box (dictOrd)))))))

let Data_List_Lazy_fromFoldable  = (fun (dictFoldable: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Foldable_foldr)) (box (dictFoldable))))) (box (Data_List_Lazy_Types_cons))))) (box (Data_List_Lazy_Types_nil))))

let Data_List_Lazy_foldrLazy  = (fun (dictLazy: obj) -> (let defer1 = (sharpurs_apply (box (Control_Lazy_defer)) (box (dictLazy))) in (fun (op: obj) -> (fun (z: obj) -> (let mutable go : obj = null in go <- (fun (xs: obj) -> (let v = (sharpurs_apply (box (Data_List_Lazy_Types_step)) (box (xs))) in (match ((unbox (v))) with | Data_List_Lazy_Types_Consusd_Ctor(x, xs_prime) -> (box ((sharpurs_apply (box (defer1)) (box ((fun (v1: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (op)) (box (x))))) (box ((sharpurs_apply (box (go)) (box (xs_prime)))))))))))) | Data_List_Lazy_Types_Nilusd_Ctor -> (box (z))))); go)))))

let rec Data_List_Lazy_foldM  = (fun (dictMonad: obj) -> (let pure1 = (sharpurs_apply (box (Control_Applicative_pure)) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> (dictMonad))))) (box (Prim_undefined)))))) in let bind2 = (sharpurs_apply (box (Control_Bind_bind)) (box ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> (dictMonad))))) (box (Prim_undefined)))))) in (fun (f: obj) -> (fun (b: obj) -> (fun (xs: obj) -> (let v = (sharpurs_apply (box (Data_List_Lazy_uncons)) (box (xs))) in (match ((unbox (v))) with | Data_Maybe_Nothingusd_Ctor -> (box ((sharpurs_apply (box (pure1)) (box (b))))) | Data_Maybe_Justusd_Ctor(Unbox((HasProp "head" (a) & HasProp "tail" (as_)))) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (bind2)) (box ((sharpurs_apply (box ((sharpurs_apply (box (f)) (box (b))))) (box (a)))))))) (box ((fun (b_prime: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_foldM)) (box (dictMonad))))) (box (f))))) (box (b_prime))))) (box (as_))))))))))))))))

let Data_List_Lazy_findIndex  = (fun (fn: obj) -> (let mutable go : obj = null in go <- (fun (n: obj) -> (fun (list: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_bind)) (box ((sharpurs_apply (box (Data_List_Lazy_uncons)) (box (list)))))))) (box ((fun (o: obj) -> (match ((unbox ((sharpurs_apply (box (fn)) (box ((Map.find "head" (unbox<Map<string, obj>> (o))))))))) with | LitBool true () -> (box ((sharpurs_apply (box (Data_List_Lazy_pure)) (box (n))))) | _ -> (box ((sharpurs_apply (box ((sharpurs_apply (box (go)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_add)) (box (n))))) (box ((box 1))))))))) (box ((Map.find "tail" (unbox<Map<string, obj>> (o))))))))))))))); (sharpurs_apply (box (go)) (box ((box 0))))))

let Data_List_Lazy_findLastIndex  = (fun (fn: obj) -> (fun (xs: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_map1)) (box ((fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_sub)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_sub)) (box ((sharpurs_apply (box (Data_List_Lazy_length)) (box (xs)))))))) (box ((box 1))))))))) (box (v))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_findIndex)) (box (fn))))) (box ((sharpurs_apply (box (Data_List_Lazy_reverse)) (box (xs)))))))))))

let rec Data_List_Lazy_filterM  = (fun (dictMonad: obj) -> (let pure1 = (sharpurs_apply (box (Control_Applicative_pure)) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> (dictMonad))))) (box (Prim_undefined)))))) in let bind2 = (sharpurs_apply (box (Control_Bind_bind)) (box ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> (dictMonad))))) (box (Prim_undefined)))))) in (fun (p: obj) -> (fun (list: obj) -> (let v = (sharpurs_apply (box (Data_List_Lazy_uncons)) (box (list))) in (match ((unbox (v))) with | Data_Maybe_Nothingusd_Ctor -> (box ((sharpurs_apply (box (pure1)) (box (Data_List_Lazy_Types_nil))))) | Data_Maybe_Justusd_Ctor(Unbox((HasProp "head" (x) & HasProp "tail" (xs)))) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (bind2)) (box ((sharpurs_apply (box (p)) (box (x)))))))) (box ((fun (b: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (bind2)) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_filterM)) (box (dictMonad))))) (box (p))))) (box (xs)))))))) (box ((fun (xs_prime: obj) -> (sharpurs_apply (box (pure1)) (box ((match ((unbox (b))) with | LitBool true () -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_Types_cons)) (box (x))))) (box (xs_prime))))) | _ -> (box (xs_prime))))))))))))))))))))))

let rec Data_List_Lazy_filter  = (fun (p: obj) -> (let mutable go : obj = null in go <- (fun (v: obj) -> (match ((unbox (v))) with | Data_List_Lazy_Types_Nilusd_Ctor -> (box ((box Data_List_Lazy_Types_Nilusd_Ctor))) | Data_List_Lazy_Types_Consusd_Ctor(x, xs) when (unbox (sharpurs_apply (box (p)) (box (x)))) -> (box ((box (Data_List_Lazy_Types_Consusd_Ctor(x, (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_filter)) (box (p))))) (box (xs)))))))) | Data_List_Lazy_Types_Consusd_Ctor(x, xs) when (unbox Data_Boolean_otherwise) -> (box ((sharpurs_apply (box (go)) (box ((sharpurs_apply (box (Data_List_Lazy_Types_step)) (box (xs)))))))))); (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_compose)) (box (Data_List_Lazy_Types_List))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_compose)) (box ((sharpurs_apply (box (Data_List_Lazy_map)) (box (go)))))))) (box (Data_List_Lazy_unwrap))))))))

let Data_List_Lazy_intersectBy  = (fun (eq: obj) -> (fun (xs: obj) -> (fun (ys: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_filter)) (box ((fun (x: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_any)) (box ((sharpurs_apply (box (eq)) (box (x)))))))) (box (ys))))))))) (box (xs))))))

let Data_List_Lazy_intersect  = (fun (dictEq: obj) -> (sharpurs_apply (box (Data_List_Lazy_intersectBy)) (box ((sharpurs_apply (box (Data_Eq_eq)) (box (dictEq)))))))

let rec Data_List_Lazy_nubByEq  = (fun (eq: obj) -> (let go = (fun (v: obj) -> (match ((unbox (v))) with | Data_List_Lazy_Types_Nilusd_Ctor -> (box ((box Data_List_Lazy_Types_Nilusd_Ctor))) | Data_List_Lazy_Types_Consusd_Ctor(x, xs) -> (box ((box (Data_List_Lazy_Types_Consusd_Ctor(x, (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_nubByEq)) (box (eq))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_filter)) (box ((fun (y: obj) -> (sharpurs_apply (box (Data_List_Lazy_not)) (box ((sharpurs_apply (box ((sharpurs_apply (box (eq)) (box (x))))) (box (y)))))))))))) (box (xs))))))))))))) in (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_compose)) (box (Data_List_Lazy_Types_List))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_compose)) (box ((sharpurs_apply (box (Data_List_Lazy_map)) (box (go)))))))) (box (Data_List_Lazy_unwrap))))))))

let Data_List_Lazy_nubEq  = (fun (dictEq: obj) -> (sharpurs_apply (box (Data_List_Lazy_nubByEq)) (box ((sharpurs_apply (box (Data_Eq_eq)) (box (dictEq)))))))

let Data_List_Lazy_eqPattern  = (fun (dictEq: obj) -> (let eq = (sharpurs_apply (box (Data_Eq_eq)) (box ((sharpurs_apply (box (Data_List_Lazy_Types_eqList)) (box (dictEq)))))) in (sharpurs_apply (box (Data_Eq_Equsd_Dict)) (box ((Map.add "eq" (box ((fun (x: obj) -> (fun (y: obj) -> (match (((unbox (x)), (unbox (y)))) with | (l, r) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (eq)) (box (l))))) (box (r)))))))))) Map.empty))))))

let Data_List_Lazy_ordPattern  = (fun (dictOrd: obj) -> (let compare = (sharpurs_apply (box (Data_Ord_compare)) (box ((sharpurs_apply (box (Data_List_Lazy_Types_ordList)) (box (dictOrd)))))) in let eqPattern1 = (sharpurs_apply (box (Data_List_Lazy_eqPattern)) (box ((sharpurs_apply (box ((Map.find "Eq0" (unbox<Map<string, obj>> (dictOrd))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Ord_Ordusd_Dict)) (box ((Map.add "compare" (box ((fun (x: obj) -> (fun (y: obj) -> (match (((unbox (x)), (unbox (y)))) with | (l, r) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (compare)) (box (l))))) (box (r)))))))))) (Map.add "Eq0" (box ((fun (_: obj) -> eqPattern1))) Map.empty)))))))

let Data_List_Lazy_elemLastIndex  = (fun (dictEq: obj) -> (let eq = (sharpurs_apply (box (Data_Eq_eq)) (box (dictEq))) in (fun (x: obj) -> (sharpurs_apply (box (Data_List_Lazy_findLastIndex)) (box ((fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (eq)) (box (v))))) (box (x))))))))))

let Data_List_Lazy_elemIndex  = (fun (dictEq: obj) -> (let eq = (sharpurs_apply (box (Data_Eq_eq)) (box (dictEq))) in (fun (x: obj) -> (sharpurs_apply (box (Data_List_Lazy_findIndex)) (box ((fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (eq)) (box (v))))) (box (x))))))))))

let Data_List_Lazy_dropWhile  = (fun (p: obj) -> (let mutable go : obj = null in go <- (fun (v: obj) -> (match ((unbox (v))) with | Data_List_Lazy_Types_Consusd_Ctor(x, xs) when (unbox (sharpurs_apply (box (p)) (box (x)))) -> (box ((sharpurs_apply (box (go)) (box ((sharpurs_apply (box (Data_List_Lazy_Types_step)) (box (xs)))))))) | xs -> (box ((sharpurs_apply (box (Data_List_Lazy_fromStep)) (box (xs))))))); (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_compose)) (box (go))))) (box (Data_List_Lazy_Types_step)))))

let Data_List_Lazy_drop  = (fun (n: obj) -> (let mutable go : obj = null in go <- (fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (LitInt 0 (), xs) -> (box (xs)) | (_, Data_List_Lazy_Types_Nilusd_Ctor) -> (box ((box Data_List_Lazy_Types_Nilusd_Ctor))) | (n_prime, Data_List_Lazy_Types_Consusd_Ctor(_, xs)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (go)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_sub)) (box (n_prime))))) (box ((box 1))))))))) (box ((sharpurs_apply (box (Data_List_Lazy_Types_step)) (box (xs))))))))))); (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_compose)) (box (Data_List_Lazy_Types_List))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_compose)) (box ((sharpurs_apply (box (Data_List_Lazy_map)) (box ((sharpurs_apply (box (go)) (box (n))))))))))) (box (Data_List_Lazy_unwrap))))))))

let Data_List_Lazy_slice  = (fun (start: obj) -> (fun (end_: obj) -> (fun (xs: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_take)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_sub)) (box (end_))))) (box (start)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_drop)) (box (start))))) (box (xs)))))))))

let rec Data_List_Lazy_deleteBy  = (fun (eq: obj) -> (fun (x: obj) -> (fun (xs: obj) -> (let go = (fun (v: obj) -> (match ((unbox (v))) with | Data_List_Lazy_Types_Nilusd_Ctor -> (box ((box Data_List_Lazy_Types_Nilusd_Ctor))) | Data_List_Lazy_Types_Consusd_Ctor(y, ys) when (unbox (sharpurs_apply (box ((sharpurs_apply (box (eq)) (box (x))))) (box (y)))) -> (box ((sharpurs_apply (box (Data_List_Lazy_Types_step)) (box (ys))))) | Data_List_Lazy_Types_Consusd_Ctor(y, ys) when (unbox Data_Boolean_otherwise) -> (box ((box (Data_List_Lazy_Types_Consusd_Ctor(y, (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_deleteBy)) (box (eq))))) (box (x))))) (box (ys)))))))))) in (sharpurs_apply (box (Data_List_Lazy_Types_List)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_map)) (box (go))))) (box ((sharpurs_apply (box (Data_List_Lazy_unwrap)) (box (xs)))))))))))))

let Data_List_Lazy_unionBy  = (fun (eq: obj) -> (fun (xs: obj) -> (fun (ys: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_append1)) (box (xs))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_foldl)) (box ((sharpurs_apply (box (Data_Function_flip)) (box ((sharpurs_apply (box (Data_List_Lazy_deleteBy)) (box (eq))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_nubByEq)) (box (eq))))) (box (ys)))))))) (box (xs)))))))))

let Data_List_Lazy_union  = (fun (dictEq: obj) -> (sharpurs_apply (box (Data_List_Lazy_unionBy)) (box ((sharpurs_apply (box (Data_Eq_eq)) (box (dictEq)))))))

let rec Data_List_Lazy_deleteAt  = (fun (n: obj) -> (fun (xs: obj) -> (let go = (fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (_, Data_List_Lazy_Types_Nilusd_Ctor) -> (box ((box Data_List_Lazy_Types_Nilusd_Ctor))) | (LitInt 0 (), Data_List_Lazy_Types_Consusd_Ctor(_, ys)) -> (box ((sharpurs_apply (box (Data_List_Lazy_Types_step)) (box (ys))))) | (n_prime, Data_List_Lazy_Types_Consusd_Ctor(y, ys)) -> (box ((box (Data_List_Lazy_Types_Consusd_Ctor(y, (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_deleteAt)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_sub)) (box (n_prime))))) (box ((box 1))))))))) (box (ys))))))))))) in (sharpurs_apply (box (Data_List_Lazy_Types_List)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_map)) (box ((sharpurs_apply (box (go)) (box (n)))))))) (box ((sharpurs_apply (box (Data_List_Lazy_unwrap)) (box (xs))))))))))))

let Data_List_Lazy_delete  = (fun (dictEq: obj) -> (sharpurs_apply (box (Data_List_Lazy_deleteBy)) (box ((sharpurs_apply (box (Data_Eq_eq)) (box (dictEq)))))))

let Data_List_Lazy_difference  = (fun (dictEq: obj) -> (sharpurs_apply (box (Data_List_Lazy_foldl)) (box ((sharpurs_apply (box (Data_Function_flip)) (box ((sharpurs_apply (box (Data_List_Lazy_delete)) (box (dictEq))))))))))

let Data_List_Lazy_cycle  = (fun (xs: obj) -> (sharpurs_apply (box (Data_List_Lazy_fix)) (box ((fun (ys: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_append1)) (box (xs))))) (box (ys))))))))

let Data_List_Lazy_concatMap  = (sharpurs_apply (box (Data_Function_flip)) (box (Data_List_Lazy_bind1)))

let Data_List_Lazy_concat  = (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_bind1)) (box (v))))) (box (Data_List_Lazy_identity))))

let Data_List_Lazy_catMaybes  = (sharpurs_apply (box (Data_List_Lazy_mapMaybe)) (box (Data_List_Lazy_identity)))

let rec Data_List_Lazy_alterAt  = (fun (n: obj) -> (fun (f: obj) -> (fun (xs: obj) -> (let go = (fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (_, Data_List_Lazy_Types_Nilusd_Ctor) -> (box ((box Data_List_Lazy_Types_Nilusd_Ctor))) | (LitInt 0 (), Data_List_Lazy_Types_Consusd_Ctor(y, ys)) -> (box ((let v2 = (sharpurs_apply (box (f)) (box (y))) in (match ((unbox (v2))) with | Data_Maybe_Nothingusd_Ctor -> (box ((sharpurs_apply (box (Data_List_Lazy_Types_step)) (box (ys))))) | Data_Maybe_Justusd_Ctor(y_prime) -> (box ((box (Data_List_Lazy_Types_Consusd_Ctor(y_prime, ys))))))))) | (n_prime, Data_List_Lazy_Types_Consusd_Ctor(y, ys)) -> (box ((box (Data_List_Lazy_Types_Consusd_Ctor(y, (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_alterAt)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_sub)) (box (n_prime))))) (box ((box 1))))))))) (box (f))))) (box (ys))))))))))) in (sharpurs_apply (box (Data_List_Lazy_Types_List)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_map)) (box ((sharpurs_apply (box (go)) (box (n)))))))) (box ((sharpurs_apply (box (Data_List_Lazy_unwrap)) (box (xs)))))))))))))

let Data_List_Lazy_modifyAt  = (fun (n: obj) -> (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_alterAt)) (box (n))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Lazy_compose)) (box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1))))))))) (box (f))))))))
