[<AutoOpen>]
module PureScript_Data_Tuple

open System
open System.Collections.Generic

type Data_Tuple_Tuple =
  | Data_Tuple_Tupleusd_Ctor of obj * obj

let Data_Tuple_append  = (sharpurs_apply (box (Data_Semigroup_append)) (box (Data_Semigroup_semigroupString)))

let Data_Tuple_conj  = (sharpurs_apply (box (Data_HeytingAlgebra_conj)) (box (Data_HeytingAlgebra_heytingAlgebraBoolean)))

let Data_Tuple_Tuple  = (fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2)))))

let Data_Tuple_uncurry  = (fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, Data_Tuple_Tupleusd_Ctor(a, b)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (f1)) (box (a))))) (box (b))))))))

let Data_Tuple_swap  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(a, b) -> (box ((box (Data_Tuple_Tupleusd_Ctor(b, a)))))))

let Data_Tuple_snd  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(_, b) -> (box (b))))

let Data_Tuple_showTuple  = (fun (dictShow: obj) -> (let show = (sharpurs_apply (box (Data_Show_show)) (box (dictShow))) in (fun (dictShow1: obj) -> (let show1 = (sharpurs_apply (box (Data_Show_show)) (box (dictShow1))) in (sharpurs_apply (box (Data_Show_Showusd_Dict)) (box ((Map.add "show" (box ((fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(a, b) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Tuple_append)) (box ((box "(Tuple ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Tuple_append)) (box ((sharpurs_apply (box (show)) (box (a)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Tuple_append)) (box ((box " ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Tuple_append)) (box ((sharpurs_apply (box (show1)) (box (b)))))))) (box ((box ")"))))))))))))))))))) Map.empty))))))))

let Data_Tuple_semiringTuple  = (fun (dictSemiring: obj) -> (let add = (sharpurs_apply (box (Data_Semiring_add)) (box (dictSemiring))) in let one = (sharpurs_apply (box (Data_Semiring_one)) (box (dictSemiring))) in let mul = (sharpurs_apply (box (Data_Semiring_mul)) (box (dictSemiring))) in let zero = (sharpurs_apply (box (Data_Semiring_zero)) (box (dictSemiring))) in (fun (dictSemiring1: obj) -> (let add1 = (sharpurs_apply (box (Data_Semiring_add)) (box (dictSemiring1))) in let mul1 = (sharpurs_apply (box (Data_Semiring_mul)) (box (dictSemiring1))) in (sharpurs_apply (box (Data_Semiring_Semiringusd_Dict)) (box ((Map.add "add" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (Data_Tuple_Tupleusd_Ctor(x1, y1), Data_Tuple_Tupleusd_Ctor(x2, y2)) -> (box ((box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box ((sharpurs_apply (box (add)) (box (x1))))) (box (x2))), (sharpurs_apply (box ((sharpurs_apply (box (add1)) (box (y1))))) (box (y2))))))))))))) (Map.add "one" (box ((box (Data_Tuple_Tupleusd_Ctor(one, (sharpurs_apply (box (Data_Semiring_one)) (box (dictSemiring1)))))))) (Map.add "mul" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (Data_Tuple_Tupleusd_Ctor(x1, y1), Data_Tuple_Tupleusd_Ctor(x2, y2)) -> (box ((box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box ((sharpurs_apply (box (mul)) (box (x1))))) (box (x2))), (sharpurs_apply (box ((sharpurs_apply (box (mul1)) (box (y1))))) (box (y2))))))))))))) (Map.add "zero" (box ((box (Data_Tuple_Tupleusd_Ctor(zero, (sharpurs_apply (box (Data_Semiring_zero)) (box (dictSemiring1)))))))) Map.empty)))))))))))

let Data_Tuple_semigroupoidTuple  = (sharpurs_apply (box (Control_Semigroupoid_Semigroupoidusd_Dict)) (box ((Map.add "compose" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (Data_Tuple_Tupleusd_Ctor(_, c), Data_Tuple_Tupleusd_Ctor(a, _)) -> (box ((box (Data_Tuple_Tupleusd_Ctor(a, c)))))))))) Map.empty))))

let Data_Tuple_semigroupTuple  = (fun (dictSemigroup: obj) -> (let append1 = (sharpurs_apply (box (Data_Semigroup_append)) (box (dictSemigroup))) in (fun (dictSemigroup1: obj) -> (let append2 = (sharpurs_apply (box (Data_Semigroup_append)) (box (dictSemigroup1))) in (sharpurs_apply (box (Data_Semigroup_Semigroupusd_Dict)) (box ((Map.add "append" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (Data_Tuple_Tupleusd_Ctor(a1, b1), Data_Tuple_Tupleusd_Ctor(a2, b2)) -> (box ((box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box ((sharpurs_apply (box (append1)) (box (a1))))) (box (a2))), (sharpurs_apply (box ((sharpurs_apply (box (append2)) (box (b1))))) (box (b2))))))))))))) Map.empty))))))))

let Data_Tuple_ringTuple  = (fun (dictRing: obj) -> (let sub = (sharpurs_apply (box (Data_Ring_sub)) (box (dictRing))) in let semiringTuple1 = (sharpurs_apply (box (Data_Tuple_semiringTuple)) (box ((sharpurs_apply (box ((Map.find "Semiring0" (unbox<Map<string, obj>> (dictRing))))) (box (Prim_undefined)))))) in (fun (dictRing1: obj) -> (let sub1 = (sharpurs_apply (box (Data_Ring_sub)) (box (dictRing1))) in let semiringTuple2 = (sharpurs_apply (box (semiringTuple1)) (box ((sharpurs_apply (box ((Map.find "Semiring0" (unbox<Map<string, obj>> (dictRing1))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Ring_Ringusd_Dict)) (box ((Map.add "sub" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (Data_Tuple_Tupleusd_Ctor(x1, y1), Data_Tuple_Tupleusd_Ctor(x2, y2)) -> (box ((box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box ((sharpurs_apply (box (sub)) (box (x1))))) (box (x2))), (sharpurs_apply (box ((sharpurs_apply (box (sub1)) (box (y1))))) (box (y2))))))))))))) (Map.add "Semiring0" (box ((fun (_: obj) -> semiringTuple2))) Map.empty)))))))))

let Data_Tuple_monoidTuple  = (fun (dictMonoid: obj) -> (let mempty = (sharpurs_apply (box (Data_Monoid_mempty)) (box (dictMonoid))) in let semigroupTuple1 = (sharpurs_apply (box (Data_Tuple_semigroupTuple)) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> (dictMonoid))))) (box (Prim_undefined)))))) in (fun (dictMonoid1: obj) -> (let semigroupTuple2 = (sharpurs_apply (box (semigroupTuple1)) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> (dictMonoid1))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Monoid_Monoidusd_Dict)) (box ((Map.add "mempty" (box ((box (Data_Tuple_Tupleusd_Ctor(mempty, (sharpurs_apply (box (Data_Monoid_mempty)) (box (dictMonoid1)))))))) (Map.add "Semigroup0" (box ((fun (_: obj) -> semigroupTuple2))) Map.empty)))))))))

let Data_Tuple_heytingAlgebraTuple  = (fun (dictHeytingAlgebra: obj) -> (let tt = (sharpurs_apply (box (Data_HeytingAlgebra_tt)) (box (dictHeytingAlgebra))) in let ff = (sharpurs_apply (box (Data_HeytingAlgebra_ff)) (box (dictHeytingAlgebra))) in let implies = (sharpurs_apply (box (Data_HeytingAlgebra_implies)) (box (dictHeytingAlgebra))) in let conj1 = (sharpurs_apply (box (Data_HeytingAlgebra_conj)) (box (dictHeytingAlgebra))) in let disj = (sharpurs_apply (box (Data_HeytingAlgebra_disj)) (box (dictHeytingAlgebra))) in let not_ = (sharpurs_apply (box (Data_HeytingAlgebra_not)) (box (dictHeytingAlgebra))) in (fun (dictHeytingAlgebra1: obj) -> (let implies1 = (sharpurs_apply (box (Data_HeytingAlgebra_implies)) (box (dictHeytingAlgebra1))) in let conj2 = (sharpurs_apply (box (Data_HeytingAlgebra_conj)) (box (dictHeytingAlgebra1))) in let disj1 = (sharpurs_apply (box (Data_HeytingAlgebra_disj)) (box (dictHeytingAlgebra1))) in let not1 = (sharpurs_apply (box (Data_HeytingAlgebra_not)) (box (dictHeytingAlgebra1))) in (sharpurs_apply (box (Data_HeytingAlgebra_HeytingAlgebrausd_Dict)) (box ((Map.add "tt" (box ((box (Data_Tuple_Tupleusd_Ctor(tt, (sharpurs_apply (box (Data_HeytingAlgebra_tt)) (box (dictHeytingAlgebra1)))))))) (Map.add "ff" (box ((box (Data_Tuple_Tupleusd_Ctor(ff, (sharpurs_apply (box (Data_HeytingAlgebra_ff)) (box (dictHeytingAlgebra1)))))))) (Map.add "implies" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (Data_Tuple_Tupleusd_Ctor(x1, y1), Data_Tuple_Tupleusd_Ctor(x2, y2)) -> (box ((box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box ((sharpurs_apply (box (implies)) (box (x1))))) (box (x2))), (sharpurs_apply (box ((sharpurs_apply (box (implies1)) (box (y1))))) (box (y2))))))))))))) (Map.add "conj" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (Data_Tuple_Tupleusd_Ctor(x1, y1), Data_Tuple_Tupleusd_Ctor(x2, y2)) -> (box ((box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box ((sharpurs_apply (box (conj1)) (box (x1))))) (box (x2))), (sharpurs_apply (box ((sharpurs_apply (box (conj2)) (box (y1))))) (box (y2))))))))))))) (Map.add "disj" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (Data_Tuple_Tupleusd_Ctor(x1, y1), Data_Tuple_Tupleusd_Ctor(x2, y2)) -> (box ((box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box ((sharpurs_apply (box (disj)) (box (x1))))) (box (x2))), (sharpurs_apply (box ((sharpurs_apply (box (disj1)) (box (y1))))) (box (y2))))))))))))) (Map.add "not" (box ((fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(x, y) -> (box ((box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box (not_)) (box (x))), (sharpurs_apply (box (not1)) (box (y)))))))))))) Map.empty)))))))))))))

let Data_Tuple_genericTuple  = (sharpurs_apply (box (Data_Generic_Rep_Genericusd_Dict)) (box ((Map.add "to" (box ((fun (x: obj) -> (match ((unbox (x))) with | Data_Generic_Rep_Productusd_Ctor(arg, arg1) -> (box ((box (Data_Tuple_Tupleusd_Ctor(arg, arg1))))))))) (Map.add "from" (box ((fun (x: obj) -> (match ((unbox (x))) with | Data_Tuple_Tupleusd_Ctor(arg, arg1) -> (box ((sharpurs_apply (box (Data_Generic_Rep_Constructor)) (box ((box (Data_Generic_Rep_Productusd_Ctor((sharpurs_apply (box (Data_Generic_Rep_Argument)) (box (arg))), (sharpurs_apply (box (Data_Generic_Rep_Argument)) (box (arg1))))))))))))))) Map.empty)))))

let Data_Tuple_functorTuple  = (sharpurs_apply (box (Data_Functor_Functorusd_Dict)) (box ((Map.add "map" (box ((fun (f: obj) -> (fun (m: obj) -> (match ((unbox (m))) with | Data_Tuple_Tupleusd_Ctor(v, v1) -> (box ((box (Data_Tuple_Tupleusd_Ctor(v, (sharpurs_apply (box (f)) (box (v1))))))))))))) Map.empty))))

let Data_Tuple_invariantTuple  = (sharpurs_apply (box (Data_Functor_Invariant_Invariantusd_Dict)) (box ((Map.add "imap" (box ((sharpurs_apply (box (Data_Functor_Invariant_imapF)) (box (Data_Tuple_functorTuple))))) Map.empty))))

let Data_Tuple_fst  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(a, _) -> (box (a))))

let Data_Tuple_lazyTuple  = (fun (dictLazy: obj) -> (let defer = (sharpurs_apply (box (Control_Lazy_defer)) (box (dictLazy))) in (fun (dictLazy1: obj) -> (let defer1 = (sharpurs_apply (box (Control_Lazy_defer)) (box (dictLazy1))) in (sharpurs_apply (box (Control_Lazy_Lazyusd_Dict)) (box ((Map.add "defer" (box ((fun (f: obj) -> (box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box (defer)) (box ((fun (v: obj) -> (sharpurs_apply (box (Data_Tuple_fst)) (box ((sharpurs_apply (box (f)) (box (Data_Unit_unit)))))))))), (sharpurs_apply (box (defer1)) (box ((fun (v: obj) -> (sharpurs_apply (box (Data_Tuple_snd)) (box ((sharpurs_apply (box (f)) (box (Data_Unit_unit)))))))))))))))) Map.empty))))))))

let Data_Tuple_extendTuple  = (sharpurs_apply (box (Control_Extend_Extendusd_Dict)) (box ((Map.add "extend" (box ((fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, (Data_Tuple_Tupleusd_Ctor(a, _) as t)) -> (box ((box (Data_Tuple_Tupleusd_Ctor(a, (sharpurs_apply (box (f1)) (box (t))))))))))))) (Map.add "Functor0" (box ((fun (_: obj) -> Data_Tuple_functorTuple))) Map.empty)))))

let Data_Tuple_eqTuple  = (fun (dictEq: obj) -> (let eq = (sharpurs_apply (box (Data_Eq_eq)) (box (dictEq))) in (fun (dictEq1: obj) -> (let eq1 = (sharpurs_apply (box (Data_Eq_eq)) (box (dictEq1))) in (sharpurs_apply (box (Data_Eq_Equsd_Dict)) (box ((Map.add "eq" (box ((fun (x: obj) -> (fun (y: obj) -> (match (((unbox (x)), (unbox (y)))) with | (Data_Tuple_Tupleusd_Ctor(l, l1), Data_Tuple_Tupleusd_Ctor(r, r1)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Tuple_conj)) (box ((sharpurs_apply (box ((sharpurs_apply (box (eq)) (box (l))))) (box (r)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (eq1)) (box (l1))))) (box (r1))))))))))))) Map.empty))))))))

let Data_Tuple_ordTuple  = (fun (dictOrd: obj) -> (let compare = (sharpurs_apply (box (Data_Ord_compare)) (box (dictOrd))) in let eqTuple1 = (sharpurs_apply (box (Data_Tuple_eqTuple)) (box ((sharpurs_apply (box ((Map.find "Eq0" (unbox<Map<string, obj>> (dictOrd))))) (box (Prim_undefined)))))) in (fun (dictOrd1: obj) -> (let compare1 = (sharpurs_apply (box (Data_Ord_compare)) (box (dictOrd1))) in let eqTuple2 = (sharpurs_apply (box (eqTuple1)) (box ((sharpurs_apply (box ((Map.find "Eq0" (unbox<Map<string, obj>> (dictOrd1))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Ord_Ordusd_Dict)) (box ((Map.add "compare" (box ((fun (x: obj) -> (fun (y: obj) -> (match (((unbox (x)), (unbox (y)))) with | (Data_Tuple_Tupleusd_Ctor(l, l1), Data_Tuple_Tupleusd_Ctor(r, r1)) -> (box ((let v = (sharpurs_apply (box ((sharpurs_apply (box (compare)) (box (l))))) (box (r))) in (match ((unbox (v))) with | Data_Ordering_LTusd_Ctor -> (box ((box Data_Ordering_LTusd_Ctor))) | Data_Ordering_GTusd_Ctor -> (box ((box Data_Ordering_GTusd_Ctor))) | _ -> (box ((sharpurs_apply (box ((sharpurs_apply (box (compare1)) (box (l1))))) (box (r1)))))))))))))) (Map.add "Eq0" (box ((fun (_: obj) -> eqTuple2))) Map.empty)))))))))

let Data_Tuple_eq1Tuple  = (fun (dictEq: obj) -> (let eqTuple1 = (sharpurs_apply (box (Data_Tuple_eqTuple)) (box (dictEq))) in (sharpurs_apply (box (Data_Eq_Eq1usd_Dict)) (box ((Map.add "eq1" (box ((fun (dictEq1: obj) -> (sharpurs_apply (box (Data_Eq_eq)) (box ((sharpurs_apply (box (eqTuple1)) (box (dictEq1))))))))) Map.empty))))))

let Data_Tuple_ord1Tuple  = (fun (dictOrd: obj) -> (let ordTuple1 = (sharpurs_apply (box (Data_Tuple_ordTuple)) (box (dictOrd))) in let eq1Tuple1 = (sharpurs_apply (box (Data_Tuple_eq1Tuple)) (box ((sharpurs_apply (box ((Map.find "Eq0" (unbox<Map<string, obj>> (dictOrd))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Ord_Ord1usd_Dict)) (box ((Map.add "compare1" (box ((fun (dictOrd1: obj) -> (sharpurs_apply (box (Data_Ord_compare)) (box ((sharpurs_apply (box (ordTuple1)) (box (dictOrd1))))))))) (Map.add "Eq10" (box ((fun (_: obj) -> eq1Tuple1))) Map.empty)))))))

let Data_Tuple_curry  = (fun (f: obj) -> (fun (a: obj) -> (fun (b: obj) -> (sharpurs_apply (box (f)) (box ((box (Data_Tuple_Tupleusd_Ctor(a, b)))))))))

let Data_Tuple_comonadTuple  = (sharpurs_apply (box (Control_Comonad_Comonadusd_Dict)) (box ((Map.add "extract" (box (Data_Tuple_snd)) (Map.add "Extend0" (box ((fun (_: obj) -> Data_Tuple_extendTuple))) Map.empty)))))

let Data_Tuple_commutativeRingTuple  = (fun (dictCommutativeRing: obj) -> (let ringTuple1 = (sharpurs_apply (box (Data_Tuple_ringTuple)) (box ((sharpurs_apply (box ((Map.find "Ring0" (unbox<Map<string, obj>> (dictCommutativeRing))))) (box (Prim_undefined)))))) in (fun (dictCommutativeRing1: obj) -> (let ringTuple2 = (sharpurs_apply (box (ringTuple1)) (box ((sharpurs_apply (box ((Map.find "Ring0" (unbox<Map<string, obj>> (dictCommutativeRing1))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_CommutativeRing_CommutativeRingusd_Dict)) (box ((Map.add "Ring0" (box ((fun (_: obj) -> ringTuple2))) Map.empty))))))))

let Data_Tuple_boundedTuple  = (fun (dictBounded: obj) -> (let top = (sharpurs_apply (box (Data_Bounded_top)) (box (dictBounded))) in let bottom = (sharpurs_apply (box (Data_Bounded_bottom)) (box (dictBounded))) in let ordTuple1 = (sharpurs_apply (box (Data_Tuple_ordTuple)) (box ((sharpurs_apply (box ((Map.find "Ord0" (unbox<Map<string, obj>> (dictBounded))))) (box (Prim_undefined)))))) in (fun (dictBounded1: obj) -> (let ordTuple2 = (sharpurs_apply (box (ordTuple1)) (box ((sharpurs_apply (box ((Map.find "Ord0" (unbox<Map<string, obj>> (dictBounded1))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Bounded_Boundedusd_Dict)) (box ((Map.add "top" (box ((box (Data_Tuple_Tupleusd_Ctor(top, (sharpurs_apply (box (Data_Bounded_top)) (box (dictBounded1)))))))) (Map.add "bottom" (box ((box (Data_Tuple_Tupleusd_Ctor(bottom, (sharpurs_apply (box (Data_Bounded_bottom)) (box (dictBounded1)))))))) (Map.add "Ord0" (box ((fun (_: obj) -> ordTuple2))) Map.empty))))))))))

let Data_Tuple_booleanAlgebraTuple  = (fun (dictBooleanAlgebra: obj) -> (let heytingAlgebraTuple1 = (sharpurs_apply (box (Data_Tuple_heytingAlgebraTuple)) (box ((sharpurs_apply (box ((Map.find "HeytingAlgebra0" (unbox<Map<string, obj>> (dictBooleanAlgebra))))) (box (Prim_undefined)))))) in (fun (dictBooleanAlgebra1: obj) -> (let heytingAlgebraTuple2 = (sharpurs_apply (box (heytingAlgebraTuple1)) (box ((sharpurs_apply (box ((Map.find "HeytingAlgebra0" (unbox<Map<string, obj>> (dictBooleanAlgebra1))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_BooleanAlgebra_BooleanAlgebrausd_Dict)) (box ((Map.add "HeytingAlgebra0" (box ((fun (_: obj) -> heytingAlgebraTuple2))) Map.empty))))))))

let Data_Tuple_applyTuple  = (fun (dictSemigroup: obj) -> (let append1 = (sharpurs_apply (box (Data_Semigroup_append)) (box (dictSemigroup))) in (sharpurs_apply (box (Control_Apply_Applyusd_Dict)) (box ((Map.add "apply" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (Data_Tuple_Tupleusd_Ctor(a1, f), Data_Tuple_Tupleusd_Ctor(a2, x)) -> (box ((box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box ((sharpurs_apply (box (append1)) (box (a1))))) (box (a2))), (sharpurs_apply (box (f)) (box (x))))))))))))) (Map.add "Functor0" (box ((fun (_: obj) -> Data_Tuple_functorTuple))) Map.empty)))))))

let Data_Tuple_bindTuple  = (fun (dictSemigroup: obj) -> (let append1 = (sharpurs_apply (box (Data_Semigroup_append)) (box (dictSemigroup))) in let applyTuple1 = (sharpurs_apply (box (Data_Tuple_applyTuple)) (box (dictSemigroup))) in (sharpurs_apply (box (Control_Bind_Bindusd_Dict)) (box ((Map.add "bind" (box ((fun (v: obj) -> (fun (f: obj) -> (match (((unbox (v)), (unbox (f)))) with | (Data_Tuple_Tupleusd_Ctor(a1, b), f1) -> (box ((let v1 = (sharpurs_apply (box (f1)) (box (b))) in (match ((unbox (v1))) with | Data_Tuple_Tupleusd_Ctor(a2, c) -> (box ((box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box ((sharpurs_apply (box (append1)) (box (a1))))) (box (a2))), c)))))))))))))) (Map.add "Apply0" (box ((fun (_: obj) -> applyTuple1))) Map.empty)))))))

let Data_Tuple_applicativeTuple  = (fun (dictMonoid: obj) -> (let applyTuple1 = (sharpurs_apply (box (Data_Tuple_applyTuple)) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> (dictMonoid))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Control_Applicative_Applicativeusd_Dict)) (box ((Map.add "pure" (box ((fun (usd__arg1: obj) -> (box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box (Data_Monoid_mempty)) (box (dictMonoid))), usd__arg1)))))) (Map.add "Apply0" (box ((fun (_: obj) -> applyTuple1))) Map.empty)))))))

let Data_Tuple_monadTuple  = (fun (dictMonoid: obj) -> (let applicativeTuple1 = (sharpurs_apply (box (Data_Tuple_applicativeTuple)) (box (dictMonoid))) in let bindTuple1 = (sharpurs_apply (box (Data_Tuple_bindTuple)) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> (dictMonoid))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Control_Monad_Monadusd_Dict)) (box ((Map.add "Applicative0" (box ((fun (_: obj) -> applicativeTuple1))) (Map.add "Bind1" (box ((fun (_: obj) -> bindTuple1))) Map.empty)))))))
