[<AutoOpen>]
module PureScript_Data_Functor_Costar

open System
open System.Collections.Generic

let Data_Functor_Costar_composeFlipped  = (sharpurs_apply (box (Control_Semigroupoid_composeFlipped)) (box (Control_Semigroupoid_semigroupoidFn)))

let Data_Functor_Costar_lcmap  = (sharpurs_apply (box (Data_Profunctor_lcmap)) (box (Data_Profunctor_profunctorFn)))

let Data_Functor_Costar_compose  = (sharpurs_apply (box (Control_Semigroupoid_compose)) (box (Control_Semigroupoid_semigroupoidFn)))

let Data_Functor_Costar_Costar  = (fun (x: obj) -> x)

let Data_Functor_Costar_semigroupoidCostar  = (fun (dictExtend: obj) -> (let composeCoKleisliFlipped = (sharpurs_apply (box (Control_Extend_composeCoKleisliFlipped)) (box (dictExtend))) in (sharpurs_apply (box (Control_Semigroupoid_Semigroupoidusd_Dict)) (box ((Map.add "compose" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (f, g) -> (box ((sharpurs_apply (box (Data_Functor_Costar_Costar)) (box ((sharpurs_apply (box ((sharpurs_apply (box (composeCoKleisliFlipped)) (box (f))))) (box (g))))))))))))) Map.empty))))))

let Data_Functor_Costar_profunctorCostar  = (fun (dictFunctor: obj) -> (let map = (sharpurs_apply (box (Data_Functor_map)) (box (dictFunctor))) in (sharpurs_apply (box (Data_Profunctor_Profunctorusd_Dict)) (box ((Map.add "dimap" (box ((fun (f: obj) -> (fun (g: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (g)), (unbox (v)))) with | (f1, g1, h) -> (box ((sharpurs_apply (box (Data_Functor_Costar_Costar)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Costar_composeFlipped)) (box ((sharpurs_apply (box (map)) (box (f1)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Costar_composeFlipped)) (box (h))))) (box (g1))))))))))))))))) Map.empty))))))

let Data_Functor_Costar_strongCostar  = (fun (dictComonad: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Extend0" (unbox<Map<string, obj>> (dictComonad))))) (box (Prim_undefined)))))))) (box (Prim_undefined))) in let map = (sharpurs_apply (box (Data_Functor_map)) (box (Functor0))) in let extract = (sharpurs_apply (box (Control_Comonad_extract)) (box (dictComonad))) in let profunctorCostar1 = (sharpurs_apply (box (Data_Functor_Costar_profunctorCostar)) (box (Functor0))) in (sharpurs_apply (box (Data_Profunctor_Strong_Strongusd_Dict)) (box ((Map.add "first" (box ((fun (v: obj) -> (match ((unbox (v))) with | f -> (box ((sharpurs_apply (box (Data_Functor_Costar_Costar)) (box ((fun (x: obj) -> (box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box (f)) (box ((sharpurs_apply (box ((sharpurs_apply (box (map)) (box (Data_Tuple_fst))))) (box (x)))))), (sharpurs_apply (box (Data_Tuple_snd)) (box ((sharpurs_apply (box (extract)) (box (x))))))))))))))))))) (Map.add "second" (box ((fun (v: obj) -> (match ((unbox (v))) with | f -> (box ((sharpurs_apply (box (Data_Functor_Costar_Costar)) (box ((fun (x: obj) -> (box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box (Data_Tuple_fst)) (box ((sharpurs_apply (box (extract)) (box (x)))))), (sharpurs_apply (box (f)) (box ((sharpurs_apply (box ((sharpurs_apply (box (map)) (box (Data_Tuple_snd))))) (box (x))))))))))))))))))) (Map.add "Profunctor0" (box ((fun (_: obj) -> profunctorCostar1))) Map.empty))))))))

let Data_Functor_Costar_newtypeCostar  = (sharpurs_apply (box (Data_Newtype_Newtypeusd_Dict)) (box ((Map.add "Coercible0" (box ((fun (_: obj) -> Prim_undefined))) Map.empty))))

let Data_Functor_Costar_hoistCostar  = (fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, g) -> (box ((sharpurs_apply (box (Data_Functor_Costar_Costar)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Costar_lcmap)) (box (f1))))) (box (g)))))))))))

let Data_Functor_Costar_functorCostar  = (sharpurs_apply (box (Data_Functor_Functorusd_Dict)) (box ((Map.add "map" (box ((fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, g) -> (box ((sharpurs_apply (box (Data_Functor_Costar_Costar)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Costar_compose)) (box (f1))))) (box (g))))))))))))) Map.empty))))

let Data_Functor_Costar_invariantCostar  = (sharpurs_apply (box (Data_Functor_Invariant_Invariantusd_Dict)) (box ((Map.add "imap" (box ((sharpurs_apply (box (Data_Functor_Invariant_imapF)) (box (Data_Functor_Costar_functorCostar))))) Map.empty))))

let rec Data_Functor_Costar_distributiveCostar  = (sharpurs_apply (box (Data_Distributive_Distributiveusd_Dict)) (box ((Map.add "distribute" (box ((fun (dictFunctor: obj) -> (let map = (sharpurs_apply (box (Data_Functor_map)) (box (dictFunctor))) in (fun (f: obj) -> (sharpurs_apply (box (Data_Functor_Costar_Costar)) (box ((fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (map)) (box ((fun (v: obj) -> (match ((unbox (v))) with | g -> (box ((sharpurs_apply (box (g)) (box (a)))))))))))) (box (f)))))))))))) (Map.add "collect" (box ((fun (dictFunctor: obj) -> (let map = (sharpurs_apply (box (Data_Functor_map)) (box (dictFunctor))) in (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Costar_compose)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Distributive_distribute)) (box (Data_Functor_Costar_distributiveCostar))))) (box (dictFunctor)))))))) (box ((sharpurs_apply (box (map)) (box (f))))))))))) (Map.add "Functor0" (box ((fun (_: obj) -> Data_Functor_Costar_functorCostar))) Map.empty))))))

let Data_Functor_Costar_closedCostar  = (fun (dictFunctor: obj) -> (let map = (sharpurs_apply (box (Data_Functor_map)) (box (dictFunctor))) in let profunctorCostar1 = (sharpurs_apply (box (Data_Functor_Costar_profunctorCostar)) (box (dictFunctor))) in (sharpurs_apply (box (Data_Profunctor_Closed_Closedusd_Dict)) (box ((Map.add "closed" (box ((fun (v: obj) -> (match ((unbox (v))) with | f -> (box ((sharpurs_apply (box (Data_Functor_Costar_Costar)) (box ((fun (g: obj) -> (fun (x: obj) -> (sharpurs_apply (box (f)) (box ((sharpurs_apply (box ((sharpurs_apply (box (map)) (box ((fun (v1: obj) -> (sharpurs_apply (box (v1)) (box (x))))))))) (box (g))))))))))))))))) (Map.add "Profunctor0" (box ((fun (_: obj) -> profunctorCostar1))) Map.empty)))))))

let Data_Functor_Costar_categoryCostar  = (fun (dictComonad: obj) -> (let semigroupoidCostar1 = (sharpurs_apply (box (Data_Functor_Costar_semigroupoidCostar)) (box ((sharpurs_apply (box ((Map.find "Extend0" (unbox<Map<string, obj>> (dictComonad))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Control_Category_Categoryusd_Dict)) (box ((Map.add "identity" (box ((sharpurs_apply (box (Data_Functor_Costar_Costar)) (box ((sharpurs_apply (box (Control_Comonad_extract)) (box (dictComonad)))))))) (Map.add "Semigroupoid0" (box ((fun (_: obj) -> semigroupoidCostar1))) Map.empty)))))))

let Data_Functor_Costar_bifunctorCostar  = (fun (dictContravariant: obj) -> (let cmap = (sharpurs_apply (box (Data_Functor_Contravariant_cmap)) (box (dictContravariant))) in (sharpurs_apply (box (Data_Bifunctor_Bifunctorusd_Dict)) (box ((Map.add "bimap" (box ((fun (f: obj) -> (fun (g: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (g)), (unbox (v)))) with | (f1, g1, h) -> (box ((sharpurs_apply (box (Data_Functor_Costar_Costar)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Costar_composeFlipped)) (box ((sharpurs_apply (box (cmap)) (box (f1)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Costar_composeFlipped)) (box (h))))) (box (g1))))))))))))))))) Map.empty))))))

let Data_Functor_Costar_applyCostar  = (sharpurs_apply (box (Control_Apply_Applyusd_Dict)) (box ((Map.add "apply" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (f, g) -> (box ((sharpurs_apply (box (Data_Functor_Costar_Costar)) (box ((fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (f)) (box (a))))) (box ((sharpurs_apply (box (g)) (box (a))))))))))))))))) (Map.add "Functor0" (box ((fun (_: obj) -> Data_Functor_Costar_functorCostar))) Map.empty)))))

let Data_Functor_Costar_bindCostar  = (sharpurs_apply (box (Control_Bind_Bindusd_Dict)) (box ((Map.add "bind" (box ((fun (v: obj) -> (fun (f: obj) -> (match (((unbox (v)), (unbox (f)))) with | (m, f1) -> (box ((sharpurs_apply (box (Data_Functor_Costar_Costar)) (box ((fun (x: obj) -> (let v1 = (sharpurs_apply (box (f1)) (box ((sharpurs_apply (box (m)) (box (x)))))) in (match ((unbox (v1))) with | g -> (box ((sharpurs_apply (box (g)) (box (x)))))))))))))))))) (Map.add "Apply0" (box ((fun (_: obj) -> Data_Functor_Costar_applyCostar))) Map.empty)))))

let Data_Functor_Costar_applicativeCostar  = (sharpurs_apply (box (Control_Applicative_Applicativeusd_Dict)) (box ((Map.add "pure" (box ((fun (a: obj) -> (sharpurs_apply (box (Data_Functor_Costar_Costar)) (box ((fun (v: obj) -> a))))))) (Map.add "Apply0" (box ((fun (_: obj) -> Data_Functor_Costar_applyCostar))) Map.empty)))))

let Data_Functor_Costar_monadCostar  = (sharpurs_apply (box (Control_Monad_Monadusd_Dict)) (box ((Map.add "Applicative0" (box ((fun (_: obj) -> Data_Functor_Costar_applicativeCostar))) (Map.add "Bind1" (box ((fun (_: obj) -> Data_Functor_Costar_bindCostar))) Map.empty)))))
