[<AutoOpen>]
module PureScript_Data_Enum_Generic

open System
open System.Collections.Generic

let Data_Enum_Generic_compose  = (sharpurs_apply (box (Control_Semigroupoid_compose)) (box (Control_Semigroupoid_semigroupoidFn)))

let Data_Enum_Generic_map  = (sharpurs_apply (box (Data_Functor_map)) (box (Data_Maybe_functorMaybe)))

let Data_Enum_Generic_unwrap  = (sharpurs_apply (box (Data_Newtype_unwrap)) (box (Prim_undefined)))

let Data_Enum_Generic_add  = (sharpurs_apply (box (Data_Semiring_add)) (box (Data_Semiring_semiringInt)))

let Data_Enum_Generic_conj  = (sharpurs_apply (box (Data_HeytingAlgebra_conj)) (box (Data_HeytingAlgebra_heytingAlgebraBoolean)))

let Data_Enum_Generic_greaterThanOrEq  = (sharpurs_apply (box (Data_Ord_greaterThanOrEq)) (box (Data_Ord_ordInt)))

let Data_Enum_Generic_lessThan  = (sharpurs_apply (box (Data_Ord_lessThan)) (box (Data_Ord_ordInt)))

let Data_Enum_Generic_sub  = (sharpurs_apply (box (Data_Ring_sub)) (box (Data_Ring_ringInt)))

let Data_Enum_Generic_mul  = (sharpurs_apply (box (Data_Semiring_mul)) (box (Data_Semiring_semiringInt)))

let Data_Enum_Generic_apply  = (sharpurs_apply (box (Control_Apply_apply)) (box (Data_Maybe_applyMaybe)))

let Data_Enum_Generic_div  = (sharpurs_apply (box (Data_EuclideanRing_div)) (box (Data_EuclideanRing_euclideanRingInt)))

let Data_Enum_Generic_mod  = (sharpurs_apply (box (Data_EuclideanRing_mod)) (box (Data_EuclideanRing_euclideanRingInt)))

let Data_Enum_Generic_eq  = (sharpurs_apply (box (Data_Eq_eq)) (box (Data_Eq_eqInt)))

let Data_Enum_Generic_GenericEnumusd_Dict  = (fun (x: obj) -> x)

let Data_Enum_Generic_GenericBoundedEnumusd_Dict  = (fun (x: obj) -> x)

let Data_Enum_Generic_genericToEnum_prime  = (fun (dict: obj) -> (match ((unbox (dict))) with | v -> (box ((Map.find "genericToEnum'" (unbox<Map<string, obj>> (v)))))))

let Data_Enum_Generic_genericToEnum  = (fun (dictGeneric: obj) -> (let to_ = (sharpurs_apply (box (Data_Generic_Rep_to)) (box (dictGeneric))) in (fun (dictGenericBoundedEnum: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_compose)) (box ((sharpurs_apply (box (Data_Enum_Generic_map)) (box (to_)))))))) (box ((sharpurs_apply (box (Data_Enum_Generic_genericToEnum_prime)) (box (dictGenericBoundedEnum)))))))))

let Data_Enum_Generic_genericSucc_prime  = (fun (dict: obj) -> (match ((unbox (dict))) with | v -> (box ((Map.find "genericSucc'" (unbox<Map<string, obj>> (v)))))))

let Data_Enum_Generic_genericSucc  = (fun (dictGeneric: obj) -> (let to_ = (sharpurs_apply (box (Data_Generic_Rep_to)) (box (dictGeneric))) in let from = (sharpurs_apply (box (Data_Generic_Rep_from)) (box (dictGeneric))) in (fun (dictGenericEnum: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_compose)) (box ((sharpurs_apply (box (Data_Enum_Generic_map)) (box (to_)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_compose)) (box ((sharpurs_apply (box (Data_Enum_Generic_genericSucc_prime)) (box (dictGenericEnum)))))))) (box (from)))))))))

let Data_Enum_Generic_genericPred_prime  = (fun (dict: obj) -> (match ((unbox (dict))) with | v -> (box ((Map.find "genericPred'" (unbox<Map<string, obj>> (v)))))))

let Data_Enum_Generic_genericPred  = (fun (dictGeneric: obj) -> (let to_ = (sharpurs_apply (box (Data_Generic_Rep_to)) (box (dictGeneric))) in let from = (sharpurs_apply (box (Data_Generic_Rep_from)) (box (dictGeneric))) in (fun (dictGenericEnum: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_compose)) (box ((sharpurs_apply (box (Data_Enum_Generic_map)) (box (to_)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_compose)) (box ((sharpurs_apply (box (Data_Enum_Generic_genericPred_prime)) (box (dictGenericEnum)))))))) (box (from)))))))))

let Data_Enum_Generic_genericFromEnum_prime  = (fun (dict: obj) -> (match ((unbox (dict))) with | v -> (box ((Map.find "genericFromEnum'" (unbox<Map<string, obj>> (v)))))))

let Data_Enum_Generic_genericFromEnum  = (fun (dictGeneric: obj) -> (let from = (sharpurs_apply (box (Data_Generic_Rep_from)) (box (dictGeneric))) in (fun (dictGenericBoundedEnum: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_compose)) (box ((sharpurs_apply (box (Data_Enum_Generic_genericFromEnum_prime)) (box (dictGenericBoundedEnum)))))))) (box (from))))))

let Data_Enum_Generic_genericEnumSum  = (fun (dictGenericEnum: obj) -> (let genericPred_prime1 = (sharpurs_apply (box (Data_Enum_Generic_genericPred_prime)) (box (dictGenericEnum))) in let genericSucc_prime1 = (sharpurs_apply (box (Data_Enum_Generic_genericSucc_prime)) (box (dictGenericEnum))) in (fun (dictGenericTop: obj) -> (let genericTop_prime = (sharpurs_apply (box (Data_Bounded_Generic_genericTop_prime)) (box (dictGenericTop))) in (fun (dictGenericEnum1: obj) -> (let genericPred_prime2 = (sharpurs_apply (box (Data_Enum_Generic_genericPred_prime)) (box (dictGenericEnum1))) in let genericSucc_prime2 = (sharpurs_apply (box (Data_Enum_Generic_genericSucc_prime)) (box (dictGenericEnum1))) in (fun (dictGenericBottom: obj) -> (let genericBottom_prime = (sharpurs_apply (box (Data_Bounded_Generic_genericBottom_prime)) (box (dictGenericBottom))) in (sharpurs_apply (box (Data_Enum_Generic_GenericEnumusd_Dict)) (box ((Map.add "genericPred'" (box ((fun (v: obj) -> (match ((unbox (v))) with | Data_Generic_Rep_Inlusd_Ctor(a) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_map)) (box ((fun (usd__arg1: obj) -> (box (Data_Generic_Rep_Inlusd_Ctor(usd__arg1))))))))) (box ((sharpurs_apply (box (genericPred_prime1)) (box (a)))))))) | Data_Generic_Rep_Inrusd_Ctor(b) -> (box ((let v1 = (sharpurs_apply (box (genericPred_prime2)) (box (b))) in (match ((unbox (v1))) with | Data_Maybe_Nothingusd_Ctor -> (box ((box (Data_Maybe_Justusd_Ctor((box (Data_Generic_Rep_Inlusd_Ctor(genericTop_prime)))))))) | Data_Maybe_Justusd_Ctor(b_prime) -> (box ((box (Data_Maybe_Justusd_Ctor((box (Data_Generic_Rep_Inrusd_Ctor(b_prime)))))))))))))))) (Map.add "genericSucc'" (box ((fun (v: obj) -> (match ((unbox (v))) with | Data_Generic_Rep_Inlusd_Ctor(a) -> (box ((let v1 = (sharpurs_apply (box (genericSucc_prime1)) (box (a))) in (match ((unbox (v1))) with | Data_Maybe_Nothingusd_Ctor -> (box ((box (Data_Maybe_Justusd_Ctor((box (Data_Generic_Rep_Inrusd_Ctor(genericBottom_prime)))))))) | Data_Maybe_Justusd_Ctor(a_prime) -> (box ((box (Data_Maybe_Justusd_Ctor((box (Data_Generic_Rep_Inlusd_Ctor(a_prime)))))))))))) | Data_Generic_Rep_Inrusd_Ctor(b) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_map)) (box ((fun (usd__arg1: obj) -> (box (Data_Generic_Rep_Inrusd_Ctor(usd__arg1))))))))) (box ((sharpurs_apply (box (genericSucc_prime2)) (box (b)))))))))))) Map.empty)))))))))))))

let Data_Enum_Generic_genericEnumProduct  = (fun (dictGenericEnum: obj) -> (let genericPred_prime1 = (sharpurs_apply (box (Data_Enum_Generic_genericPred_prime)) (box (dictGenericEnum))) in let genericSucc_prime1 = (sharpurs_apply (box (Data_Enum_Generic_genericSucc_prime)) (box (dictGenericEnum))) in (fun (dictGenericTop: obj) -> (fun (dictGenericBottom: obj) -> (fun (dictGenericEnum1: obj) -> (let genericPred_prime2 = (sharpurs_apply (box (Data_Enum_Generic_genericPred_prime)) (box (dictGenericEnum1))) in let genericSucc_prime2 = (sharpurs_apply (box (Data_Enum_Generic_genericSucc_prime)) (box (dictGenericEnum1))) in (fun (dictGenericTop1: obj) -> (let genericTop_prime = (sharpurs_apply (box (Data_Bounded_Generic_genericTop_prime)) (box (dictGenericTop1))) in (fun (dictGenericBottom1: obj) -> (let genericBottom_prime = (sharpurs_apply (box (Data_Bounded_Generic_genericBottom_prime)) (box (dictGenericBottom1))) in (sharpurs_apply (box (Data_Enum_Generic_GenericEnumusd_Dict)) (box ((Map.add "genericPred'" (box ((fun (v: obj) -> (match ((unbox (v))) with | Data_Generic_Rep_Productusd_Ctor(a, b) -> (box ((let v1 = (sharpurs_apply (box (genericPred_prime2)) (box (b))) in (match ((unbox (v1))) with | Data_Maybe_Justusd_Ctor(p) -> (box ((box (Data_Maybe_Justusd_Ctor((box (Data_Generic_Rep_Productusd_Ctor(a, p)))))))) | Data_Maybe_Nothingusd_Ctor -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_map)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Function_flip)) (box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Generic_Rep_Productusd_Ctor(usd__arg1, usd__arg2)))))))))) (box (genericTop_prime)))))))) (box ((sharpurs_apply (box (genericPred_prime1)) (box (a)))))))))))))))) (Map.add "genericSucc'" (box ((fun (v: obj) -> (match ((unbox (v))) with | Data_Generic_Rep_Productusd_Ctor(a, b) -> (box ((let v1 = (sharpurs_apply (box (genericSucc_prime2)) (box (b))) in (match ((unbox (v1))) with | Data_Maybe_Justusd_Ctor(s) -> (box ((box (Data_Maybe_Justusd_Ctor((box (Data_Generic_Rep_Productusd_Ctor(a, s)))))))) | Data_Maybe_Nothingusd_Ctor -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_map)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Function_flip)) (box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Generic_Rep_Productusd_Ctor(usd__arg1, usd__arg2)))))))))) (box (genericBottom_prime)))))))) (box ((sharpurs_apply (box (genericSucc_prime1)) (box (a)))))))))))))))) Map.empty)))))))))))))))

let Data_Enum_Generic_genericEnumNoArguments  = (sharpurs_apply (box (Data_Enum_Generic_GenericEnumusd_Dict)) (box ((Map.add "genericPred'" (box ((fun (v: obj) -> (box Data_Maybe_Nothingusd_Ctor)))) (Map.add "genericSucc'" (box ((fun (v: obj) -> (box Data_Maybe_Nothingusd_Ctor)))) Map.empty)))))

let Data_Enum_Generic_genericEnumConstructor  = (fun (dictGenericEnum: obj) -> (let genericPred_prime1 = (sharpurs_apply (box (Data_Enum_Generic_genericPred_prime)) (box (dictGenericEnum))) in let genericSucc_prime1 = (sharpurs_apply (box (Data_Enum_Generic_genericSucc_prime)) (box (dictGenericEnum))) in (sharpurs_apply (box (Data_Enum_Generic_GenericEnumusd_Dict)) (box ((Map.add "genericPred'" (box ((fun (v: obj) -> (match ((unbox (v))) with | a -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_map)) (box (Data_Generic_Rep_Constructor))))) (box ((sharpurs_apply (box (genericPred_prime1)) (box (a)))))))))))) (Map.add "genericSucc'" (box ((fun (v: obj) -> (match ((unbox (v))) with | a -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_map)) (box (Data_Generic_Rep_Constructor))))) (box ((sharpurs_apply (box (genericSucc_prime1)) (box (a)))))))))))) Map.empty)))))))

let Data_Enum_Generic_genericEnumArgument  = (fun (dictEnum: obj) -> (let pred = (sharpurs_apply (box (Data_Enum_pred)) (box (dictEnum))) in let succ = (sharpurs_apply (box (Data_Enum_succ)) (box (dictEnum))) in (sharpurs_apply (box (Data_Enum_Generic_GenericEnumusd_Dict)) (box ((Map.add "genericPred'" (box ((fun (v: obj) -> (match ((unbox (v))) with | a -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_map)) (box (Data_Generic_Rep_Argument))))) (box ((sharpurs_apply (box (pred)) (box (a)))))))))))) (Map.add "genericSucc'" (box ((fun (v: obj) -> (match ((unbox (v))) with | a -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_map)) (box (Data_Generic_Rep_Argument))))) (box ((sharpurs_apply (box (succ)) (box (a)))))))))))) Map.empty)))))))

let Data_Enum_Generic_genericCardinality_prime  = (fun (dict: obj) -> (match ((unbox (dict))) with | v -> (box ((Map.find "genericCardinality'" (unbox<Map<string, obj>> (v)))))))

let Data_Enum_Generic_genericCardinality  = (fun (dictGeneric: obj) -> (fun (dictGenericBoundedEnum: obj) -> (sharpurs_apply (box (Data_Enum_Cardinality)) (box ((sharpurs_apply (box (Data_Enum_Generic_unwrap)) (box ((sharpurs_apply (box (Data_Enum_Generic_genericCardinality_prime)) (box (dictGenericBoundedEnum)))))))))))

let Data_Enum_Generic_genericBoundedEnumSum  = (fun (dictGenericBoundedEnum: obj) -> (let genericCardinality_prime1 = (sharpurs_apply (box (Data_Enum_Generic_genericCardinality_prime)) (box (dictGenericBoundedEnum))) in let genericToEnum_prime1 = (sharpurs_apply (box (Data_Enum_Generic_genericToEnum_prime)) (box (dictGenericBoundedEnum))) in let genericFromEnum_prime1 = (sharpurs_apply (box (Data_Enum_Generic_genericFromEnum_prime)) (box (dictGenericBoundedEnum))) in (fun (dictGenericBoundedEnum1: obj) -> (let genericToEnum_prime2 = (sharpurs_apply (box (Data_Enum_Generic_genericToEnum_prime)) (box (dictGenericBoundedEnum1))) in let genericFromEnum_prime2 = (sharpurs_apply (box (Data_Enum_Generic_genericFromEnum_prime)) (box (dictGenericBoundedEnum1))) in (sharpurs_apply (box (Data_Enum_Generic_GenericBoundedEnumusd_Dict)) (box ((Map.add "genericCardinality'" (box ((sharpurs_apply (box (Data_Enum_Cardinality)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_add)) (box ((sharpurs_apply (box (Data_Enum_Generic_unwrap)) (box (genericCardinality_prime1)))))))) (box ((sharpurs_apply (box (Data_Enum_Generic_unwrap)) (box ((sharpurs_apply (box (Data_Enum_Generic_genericCardinality_prime)) (box (dictGenericBoundedEnum1)))))))))))))) (Map.add "genericToEnum'" (box ((fun (n: obj) -> (let to_ = (fun (v: obj) -> (match ((unbox (v))) with | ca when (unbox (sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_conj)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_greaterThanOrEq)) (box (n))))) (box ((box 0))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_lessThan)) (box (n))))) (box (ca))))))) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_map)) (box ((fun (usd__arg1: obj) -> (box (Data_Generic_Rep_Inlusd_Ctor(usd__arg1))))))))) (box ((sharpurs_apply (box (genericToEnum_prime1)) (box (n)))))))) | ca when (unbox Data_Boolean_otherwise) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_map)) (box ((fun (usd__arg1: obj) -> (box (Data_Generic_Rep_Inrusd_Ctor(usd__arg1))))))))) (box ((sharpurs_apply (box (genericToEnum_prime2)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_sub)) (box (n))))) (box (ca))))))))))))) in (sharpurs_apply (box (to_)) (box (genericCardinality_prime1))))))) (Map.add "genericFromEnum'" (box ((fun (v: obj) -> (match ((unbox (v))) with | Data_Generic_Rep_Inlusd_Ctor(a) -> (box ((sharpurs_apply (box (genericFromEnum_prime1)) (box (a))))) | Data_Generic_Rep_Inrusd_Ctor(b) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_add)) (box ((sharpurs_apply (box (genericFromEnum_prime2)) (box (b)))))))) (box ((sharpurs_apply (box (Data_Enum_Generic_unwrap)) (box (genericCardinality_prime1)))))))))))) Map.empty))))))))))

let Data_Enum_Generic_genericBoundedEnumProduct  = (fun (dictGenericBoundedEnum: obj) -> (let genericCardinality_prime1 = (sharpurs_apply (box (Data_Enum_Generic_genericCardinality_prime)) (box (dictGenericBoundedEnum))) in let genericToEnum_prime1 = (sharpurs_apply (box (Data_Enum_Generic_genericToEnum_prime)) (box (dictGenericBoundedEnum))) in let genericFromEnum_prime1 = (sharpurs_apply (box (Data_Enum_Generic_genericFromEnum_prime)) (box (dictGenericBoundedEnum))) in (fun (dictGenericBoundedEnum1: obj) -> (let genericCardinality_prime2 = (sharpurs_apply (box (Data_Enum_Generic_genericCardinality_prime)) (box (dictGenericBoundedEnum1))) in let genericToEnum_prime2 = (sharpurs_apply (box (Data_Enum_Generic_genericToEnum_prime)) (box (dictGenericBoundedEnum1))) in let genericFromEnum_prime2 = (sharpurs_apply (box (Data_Enum_Generic_genericFromEnum_prime)) (box (dictGenericBoundedEnum1))) in (sharpurs_apply (box (Data_Enum_Generic_GenericBoundedEnumusd_Dict)) (box ((Map.add "genericCardinality'" (box ((sharpurs_apply (box (Data_Enum_Cardinality)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_mul)) (box ((sharpurs_apply (box (Data_Enum_Generic_unwrap)) (box (genericCardinality_prime1)))))))) (box ((sharpurs_apply (box (Data_Enum_Generic_unwrap)) (box (genericCardinality_prime2))))))))))) (Map.add "genericToEnum'" (box ((fun (n: obj) -> (let to_ = (fun (v: obj) -> (match ((unbox (v))) with | cb -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_apply)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_map)) (box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Generic_Rep_Productusd_Ctor(usd__arg1, usd__arg2)))))))))) (box ((sharpurs_apply (box (genericToEnum_prime1)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_div)) (box (n))))) (box (cb)))))))))))))) (box ((sharpurs_apply (box (genericToEnum_prime2)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_mod)) (box (n))))) (box (cb))))))))))))) in (sharpurs_apply (box (to_)) (box (genericCardinality_prime2))))))) (Map.add "genericFromEnum'" (box ((let from = (fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (cb, Data_Generic_Rep_Productusd_Ctor(a, b)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_add)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_mul)) (box ((sharpurs_apply (box (genericFromEnum_prime1)) (box (a)))))))) (box (cb)))))))) (box ((sharpurs_apply (box (genericFromEnum_prime2)) (box (b))))))))))) in (sharpurs_apply (box (from)) (box (genericCardinality_prime2)))))) Map.empty))))))))))

let Data_Enum_Generic_genericBoundedEnumNoArguments  = (sharpurs_apply (box (Data_Enum_Generic_GenericBoundedEnumusd_Dict)) (box ((Map.add "genericCardinality'" (box ((sharpurs_apply (box (Data_Enum_Cardinality)) (box ((box 1)))))) (Map.add "genericToEnum'" (box ((fun (i: obj) -> (match ((unbox ((sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_eq)) (box (i))))) (box ((box 0))))))) with | LitBool true () -> (box ((box (Data_Maybe_Justusd_Ctor((box Data_Generic_Rep_NoArgumentsusd_Ctor)))))) | _ -> (box ((box Data_Maybe_Nothingusd_Ctor))))))) (Map.add "genericFromEnum'" (box ((fun (v: obj) -> (box 0)))) Map.empty))))))

let Data_Enum_Generic_genericBoundedEnumConstructor  = (fun (dictGenericBoundedEnum: obj) -> (let genericToEnum_prime1 = (sharpurs_apply (box (Data_Enum_Generic_genericToEnum_prime)) (box (dictGenericBoundedEnum))) in let genericFromEnum_prime1 = (sharpurs_apply (box (Data_Enum_Generic_genericFromEnum_prime)) (box (dictGenericBoundedEnum))) in (sharpurs_apply (box (Data_Enum_Generic_GenericBoundedEnumusd_Dict)) (box ((Map.add "genericCardinality'" (box ((sharpurs_apply (box (Data_Enum_Cardinality)) (box ((sharpurs_apply (box (Data_Enum_Generic_unwrap)) (box ((sharpurs_apply (box (Data_Enum_Generic_genericCardinality_prime)) (box (dictGenericBoundedEnum))))))))))) (Map.add "genericToEnum'" (box ((fun (i: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_map)) (box (Data_Generic_Rep_Constructor))))) (box ((sharpurs_apply (box (genericToEnum_prime1)) (box (i))))))))) (Map.add "genericFromEnum'" (box ((fun (v: obj) -> (match ((unbox (v))) with | a -> (box ((sharpurs_apply (box (genericFromEnum_prime1)) (box (a))))))))) Map.empty))))))))

let Data_Enum_Generic_genericBoundedEnumArgument  = (fun (dictBoundedEnum: obj) -> (let toEnum = (sharpurs_apply (box (Data_Enum_toEnum)) (box (dictBoundedEnum))) in let fromEnum = (sharpurs_apply (box (Data_Enum_fromEnum)) (box (dictBoundedEnum))) in (sharpurs_apply (box (Data_Enum_Generic_GenericBoundedEnumusd_Dict)) (box ((Map.add "genericCardinality'" (box ((sharpurs_apply (box (Data_Enum_Cardinality)) (box ((sharpurs_apply (box (Data_Enum_Generic_unwrap)) (box ((sharpurs_apply (box (Data_Enum_cardinality)) (box (dictBoundedEnum))))))))))) (Map.add "genericToEnum'" (box ((fun (i: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Enum_Generic_map)) (box (Data_Generic_Rep_Argument))))) (box ((sharpurs_apply (box (toEnum)) (box (i))))))))) (Map.add "genericFromEnum'" (box ((fun (v: obj) -> (match ((unbox (v))) with | a -> (box ((sharpurs_apply (box (fromEnum)) (box (a))))))))) Map.empty))))))))
