[<AutoOpen>]
module PureScript_Data_Functor_Product_Nested

open System
open System.Collections.Generic

let Data_Functor_Product_Nested_product9  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (fun (g: obj) -> (fun (h: obj) -> (fun (i: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (a))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (b))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (c))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (d))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (e))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (f))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (g))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (h))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (i))))) (box ((sharpurs_apply (box (Data_Const_Const)) (box (Data_Unit_unit)))))))))))))))))))))))))))))))))))))))

let Data_Functor_Product_Nested_product8  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (fun (g: obj) -> (fun (h: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (a))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (b))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (c))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (d))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (e))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (f))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (g))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (h))))) (box ((sharpurs_apply (box (Data_Const_Const)) (box (Data_Unit_unit)))))))))))))))))))))))))))))))))))

let Data_Functor_Product_Nested_product7  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (fun (g: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (a))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (b))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (c))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (d))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (e))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (f))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (g))))) (box ((sharpurs_apply (box (Data_Const_Const)) (box (Data_Unit_unit)))))))))))))))))))))))))))))))

let Data_Functor_Product_Nested_product6  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (a))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (b))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (c))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (d))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (e))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (f))))) (box ((sharpurs_apply (box (Data_Const_Const)) (box (Data_Unit_unit)))))))))))))))))))))))))))

let Data_Functor_Product_Nested_product5  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (a))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (b))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (c))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (d))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (e))))) (box ((sharpurs_apply (box (Data_Const_Const)) (box (Data_Unit_unit)))))))))))))))))))))))

let Data_Functor_Product_Nested_product4  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (a))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (b))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (c))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (d))))) (box ((sharpurs_apply (box (Data_Const_Const)) (box (Data_Unit_unit)))))))))))))))))))

let Data_Functor_Product_Nested_product3  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (a))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (b))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (c))))) (box ((sharpurs_apply (box (Data_Const_Const)) (box (Data_Unit_unit)))))))))))))))

let Data_Functor_Product_Nested_product2  = (fun (a: obj) -> (fun (b: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (a))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (b))))) (box ((sharpurs_apply (box (Data_Const_Const)) (box (Data_Unit_unit)))))))))))

let Data_Functor_Product_Nested_product10  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (fun (g: obj) -> (fun (h: obj) -> (fun (i: obj) -> (fun (j: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (a))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (b))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (c))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (d))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (e))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (f))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (g))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (h))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (i))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (j))))) (box ((sharpurs_apply (box (Data_Const_Const)) (box (Data_Unit_unit)))))))))))))))))))))))))))))))))))))))))))

let Data_Functor_Product_Nested_product1  = (fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box (a))))) (box ((sharpurs_apply (box (Data_Const_Const)) (box (Data_Unit_unit)))))))

let Data_Functor_Product_Nested_get9  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(i, _))))))))))))))))) -> (box (i))))

let Data_Functor_Product_Nested_get8  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(h, _))))))))))))))) -> (box (h))))

let Data_Functor_Product_Nested_get7  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(g, _))))))))))))) -> (box (g))))

let Data_Functor_Product_Nested_get6  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(f, _))))))))))) -> (box (f))))

let Data_Functor_Product_Nested_get5  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(e, _))))))))) -> (box (e))))

let Data_Functor_Product_Nested_get4  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(d, _))))))) -> (box (d))))

let Data_Functor_Product_Nested_get3  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(c, _))))) -> (box (c))))

let Data_Functor_Product_Nested_get2  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(b, _))) -> (box (b))))

let Data_Functor_Product_Nested_get10  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(j, _))))))))))))))))))) -> (box (j))))

let Data_Functor_Product_Nested_get1  = (fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(a, _) -> (box (a))))
