[<AutoOpen>]
module PureScript_Data_Functor_Product

open System
open System.Collections.Generic

let Data_Functor_Product_append  = (sharpurs_apply (box (Data_Semigroup_append)) (box (Data_Semigroup_semigroupString)))

let Data_Functor_Product_bimap  = (sharpurs_apply (box (Data_Bifunctor_bimap)) (box (Data_Bifunctor_bifunctorTuple)))

let Data_Functor_Product_conj  = (sharpurs_apply (box (Data_HeytingAlgebra_conj)) (box (Data_HeytingAlgebra_heytingAlgebraBoolean)))

let Data_Functor_Product_compose  = (sharpurs_apply (box (Control_Semigroupoid_compose)) (box (Control_Semigroupoid_semigroupoidFn)))

let Data_Functor_Product_unwrap  = (sharpurs_apply (box (Data_Newtype_unwrap)) (box (Prim_undefined)))

let Data_Functor_Product_Product  = (fun (x: obj) -> x)

let Data_Functor_Product_showProduct  = (fun (dictShow: obj) -> (let show = (sharpurs_apply (box (Data_Show_show)) (box (dictShow))) in (fun (dictShow1: obj) -> (let show1 = (sharpurs_apply (box (Data_Show_show)) (box (dictShow1))) in (sharpurs_apply (box (Data_Show_Showusd_Dict)) (box ((Map.add "show" (box ((fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(fa, ga) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_append)) (box ((box "(product ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_append)) (box ((sharpurs_apply (box (show)) (box (fa)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_append)) (box ((box " ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_append)) (box ((sharpurs_apply (box (show1)) (box (ga)))))))) (box ((box ")"))))))))))))))))))) Map.empty))))))))

let Data_Functor_Product_product  = (fun (fa: obj) -> (fun (ga: obj) -> (sharpurs_apply (box (Data_Functor_Product_Product)) (box ((box (Data_Tuple_Tupleusd_Ctor(fa, ga))))))))

let Data_Functor_Product_newtypeProduct  = (sharpurs_apply (box (Data_Newtype_Newtypeusd_Dict)) (box ((Map.add "Coercible0" (box ((fun (_: obj) -> Prim_undefined))) Map.empty))))

let Data_Functor_Product_functorProduct  = (fun (dictFunctor: obj) -> (let map = (sharpurs_apply (box (Data_Functor_map)) (box (dictFunctor))) in (fun (dictFunctor1: obj) -> (let map1 = (sharpurs_apply (box (Data_Functor_map)) (box (dictFunctor1))) in (sharpurs_apply (box (Data_Functor_Functorusd_Dict)) (box ((Map.add "map" (box ((fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, fga) -> (box ((sharpurs_apply (box (Data_Functor_Product_Product)) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_bimap)) (box ((sharpurs_apply (box (map)) (box (f1)))))))) (box ((sharpurs_apply (box (map1)) (box (f1)))))))) (box (fga))))))))))))) Map.empty))))))))

let Data_Functor_Product_eq1Product  = (fun (dictEq1: obj) -> (let eq1 = (sharpurs_apply (box (Data_Eq_eq1)) (box (dictEq1))) in (fun (dictEq11: obj) -> (let eq11 = (sharpurs_apply (box (Data_Eq_eq1)) (box (dictEq11))) in (sharpurs_apply (box (Data_Eq_Eq1usd_Dict)) (box ((Map.add "eq1" (box ((fun (dictEq: obj) -> (let eq12 = (sharpurs_apply (box (eq1)) (box (dictEq))) in let eq13 = (sharpurs_apply (box (eq11)) (box (dictEq))) in (fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (Data_Tuple_Tupleusd_Ctor(l1, r1), Data_Tuple_Tupleusd_Ctor(l2, r2)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_conj)) (box ((sharpurs_apply (box ((sharpurs_apply (box (eq12)) (box (l1))))) (box (l2)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (eq13)) (box (r1))))) (box (r2))))))))))))))) Map.empty))))))))

let Data_Functor_Product_eqProduct  = (fun (dictEq1: obj) -> (let eq1Product1 = (sharpurs_apply (box (Data_Functor_Product_eq1Product)) (box (dictEq1))) in (fun (dictEq11: obj) -> (let eq1 = (sharpurs_apply (box (Data_Eq_eq1)) (box ((sharpurs_apply (box (eq1Product1)) (box (dictEq11)))))) in (fun (dictEq: obj) -> (sharpurs_apply (box (Data_Eq_Equsd_Dict)) (box ((Map.add "eq" (box ((sharpurs_apply (box (eq1)) (box (dictEq))))) Map.empty)))))))))

let Data_Functor_Product_ord1Product  = (fun (dictOrd1: obj) -> (let compare1 = (sharpurs_apply (box (Data_Ord_compare1)) (box (dictOrd1))) in let eq1Product1 = (sharpurs_apply (box (Data_Functor_Product_eq1Product)) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> (dictOrd1))))) (box (Prim_undefined)))))) in (fun (dictOrd11: obj) -> (let compare11 = (sharpurs_apply (box (Data_Ord_compare1)) (box (dictOrd11))) in let eq1Product2 = (sharpurs_apply (box (eq1Product1)) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> (dictOrd11))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Ord_Ord1usd_Dict)) (box ((Map.add "compare1" (box ((fun (dictOrd: obj) -> (let compare12 = (sharpurs_apply (box (compare1)) (box (dictOrd))) in let compare13 = (sharpurs_apply (box (compare11)) (box (dictOrd))) in (fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (Data_Tuple_Tupleusd_Ctor(l1, r1), Data_Tuple_Tupleusd_Ctor(l2, r2)) -> (box ((let v2 = (sharpurs_apply (box ((sharpurs_apply (box (compare12)) (box (l1))))) (box (l2))) in (match ((unbox (v2))) with | Data_Ordering_EQusd_Ctor -> (box ((sharpurs_apply (box ((sharpurs_apply (box (compare13)) (box (r1))))) (box (r2))))) | o -> (box (o))))))))))))) (Map.add "Eq10" (box ((fun (_: obj) -> eq1Product2))) Map.empty)))))))))

let Data_Functor_Product_ordProduct  = (fun (dictOrd1: obj) -> (let ord1Product1 = (sharpurs_apply (box (Data_Functor_Product_ord1Product)) (box (dictOrd1))) in let eqProduct1 = (sharpurs_apply (box (Data_Functor_Product_eqProduct)) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> (dictOrd1))))) (box (Prim_undefined)))))) in (fun (dictOrd11: obj) -> (let compare1 = (sharpurs_apply (box (Data_Ord_compare1)) (box ((sharpurs_apply (box (ord1Product1)) (box (dictOrd11)))))) in let eqProduct2 = (sharpurs_apply (box (eqProduct1)) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> (dictOrd11))))) (box (Prim_undefined)))))) in (fun (dictOrd: obj) -> (let eqProduct3 = (sharpurs_apply (box (eqProduct2)) (box ((sharpurs_apply (box ((Map.find "Eq0" (unbox<Map<string, obj>> (dictOrd))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Ord_Ordusd_Dict)) (box ((Map.add "compare" (box ((sharpurs_apply (box (compare1)) (box (dictOrd))))) (Map.add "Eq0" (box ((fun (_: obj) -> eqProduct3))) Map.empty)))))))))))

let Data_Functor_Product_bihoistProduct  = (fun (natF: obj) -> (fun (natG: obj) -> (fun (v: obj) -> (match (((unbox (natF)), (unbox (natG)), (unbox (v)))) with | (natF1, natG1, e) -> (box ((sharpurs_apply (box (Data_Functor_Product_Product)) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_bimap)) (box (natF1))))) (box (natG1))))) (box (e))))))))))))

let Data_Functor_Product_applyProduct  = (fun (dictApply: obj) -> (let apply = (sharpurs_apply (box (Control_Apply_apply)) (box (dictApply))) in let functorProduct1 = (sharpurs_apply (box (Data_Functor_Product_functorProduct)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (dictApply))))) (box (Prim_undefined)))))) in (fun (dictApply1: obj) -> (let apply1 = (sharpurs_apply (box (Control_Apply_apply)) (box (dictApply1))) in let functorProduct2 = (sharpurs_apply (box (functorProduct1)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (dictApply1))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Control_Apply_Applyusd_Dict)) (box ((Map.add "apply" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (Data_Tuple_Tupleusd_Ctor(f, g), Data_Tuple_Tupleusd_Ctor(a, b)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box ((sharpurs_apply (box ((sharpurs_apply (box (apply)) (box (f))))) (box (a)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (apply1)) (box (g))))) (box (b))))))))))))) (Map.add "Functor0" (box ((fun (_: obj) -> functorProduct2))) Map.empty)))))))))

let Data_Functor_Product_bindProduct  = (fun (dictBind: obj) -> (let bind_ = (sharpurs_apply (box (Control_Bind_bind)) (box (dictBind))) in let applyProduct1 = (sharpurs_apply (box (Data_Functor_Product_applyProduct)) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> (dictBind))))) (box (Prim_undefined)))))) in (fun (dictBind1: obj) -> (let bind1 = (sharpurs_apply (box (Control_Bind_bind)) (box (dictBind1))) in let applyProduct2 = (sharpurs_apply (box (applyProduct1)) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> (dictBind1))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Control_Bind_Bindusd_Dict)) (box ((Map.add "bind" (box ((fun (v: obj) -> (fun (f: obj) -> (match (((unbox (v)), (unbox (f)))) with | (Data_Tuple_Tupleusd_Ctor(fa, ga), f1) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box ((sharpurs_apply (box ((sharpurs_apply (box (bind_)) (box (fa))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_compose)) (box (Data_Tuple_fst))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_compose)) (box (Data_Functor_Product_unwrap))))) (box (f1)))))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (bind1)) (box (ga))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_compose)) (box (Data_Tuple_snd))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_compose)) (box (Data_Functor_Product_unwrap))))) (box (f1))))))))))))))))))) (Map.add "Apply0" (box ((fun (_: obj) -> applyProduct2))) Map.empty)))))))))

let Data_Functor_Product_applicativeProduct  = (fun (dictApplicative: obj) -> (let pure_ = (sharpurs_apply (box (Control_Applicative_pure)) (box (dictApplicative))) in let applyProduct1 = (sharpurs_apply (box (Data_Functor_Product_applyProduct)) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> (dictApplicative))))) (box (Prim_undefined)))))) in (fun (dictApplicative1: obj) -> (let pure1 = (sharpurs_apply (box (Control_Applicative_pure)) (box (dictApplicative1))) in let applyProduct2 = (sharpurs_apply (box (applyProduct1)) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> (dictApplicative1))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Control_Applicative_Applicativeusd_Dict)) (box ((Map.add "pure" (box ((fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Product_product)) (box ((sharpurs_apply (box (pure_)) (box (a)))))))) (box ((sharpurs_apply (box (pure1)) (box (a))))))))) (Map.add "Apply0" (box ((fun (_: obj) -> applyProduct2))) Map.empty)))))))))

let Data_Functor_Product_monadProduct  = (fun (dictMonad: obj) -> (let applicativeProduct1 = (sharpurs_apply (box (Data_Functor_Product_applicativeProduct)) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> (dictMonad))))) (box (Prim_undefined)))))) in let bindProduct1 = (sharpurs_apply (box (Data_Functor_Product_bindProduct)) (box ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> (dictMonad))))) (box (Prim_undefined)))))) in (fun (dictMonad1: obj) -> (let applicativeProduct2 = (sharpurs_apply (box (applicativeProduct1)) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> (dictMonad1))))) (box (Prim_undefined)))))) in let bindProduct2 = (sharpurs_apply (box (bindProduct1)) (box ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> (dictMonad1))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Control_Monad_Monadusd_Dict)) (box ((Map.add "Applicative0" (box ((fun (_: obj) -> applicativeProduct2))) (Map.add "Bind1" (box ((fun (_: obj) -> bindProduct2))) Map.empty)))))))))
