[<AutoOpen>]
module PureScript_Data_Either_Nested

open System
open System.Collections.Generic

let Data_Either_Nested_in9  = (fun (v: obj) -> (box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Leftusd_Ctor(v))))))))))))))))))))))))))))

let Data_Either_Nested_in8  = (fun (v: obj) -> (box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Leftusd_Ctor(v)))))))))))))))))))))))))

let Data_Either_Nested_in7  = (fun (v: obj) -> (box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Leftusd_Ctor(v))))))))))))))))))))))

let Data_Either_Nested_in6  = (fun (v: obj) -> (box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Leftusd_Ctor(v)))))))))))))))))))

let Data_Either_Nested_in5  = (fun (v: obj) -> (box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Leftusd_Ctor(v))))))))))))))))

let Data_Either_Nested_in4  = (fun (v: obj) -> (box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Leftusd_Ctor(v)))))))))))))

let Data_Either_Nested_in3  = (fun (v: obj) -> (box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Leftusd_Ctor(v))))))))))

let Data_Either_Nested_in2  = (fun (v: obj) -> (box (Data_Either_Rightusd_Ctor((box (Data_Either_Leftusd_Ctor(v)))))))

let Data_Either_Nested_in10  = (fun (v: obj) -> (box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Rightusd_Ctor((box (Data_Either_Leftusd_Ctor(v)))))))))))))))))))))))))))))))

let Data_Either_Nested_in1  = (fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1))))

let Data_Either_Nested_either9  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (fun (g: obj) -> (fun (h: obj) -> (fun (i: obj) -> (fun (y: obj) -> (match ((unbox (y))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (a)) (box (r))))) | Data_Either_Rightusd_Ctor(_1) -> (box ((match ((unbox (_1))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (b)) (box (r))))) | Data_Either_Rightusd_Ctor(_2) -> (box ((match ((unbox (_2))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (c)) (box (r))))) | Data_Either_Rightusd_Ctor(_3) -> (box ((match ((unbox (_3))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (d)) (box (r))))) | Data_Either_Rightusd_Ctor(_4) -> (box ((match ((unbox (_4))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (e)) (box (r))))) | Data_Either_Rightusd_Ctor(_5) -> (box ((match ((unbox (_5))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (f)) (box (r))))) | Data_Either_Rightusd_Ctor(_6) -> (box ((match ((unbox (_6))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (g)) (box (r))))) | Data_Either_Rightusd_Ctor(_7) -> (box ((match ((unbox (_7))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (h)) (box (r))))) | Data_Either_Rightusd_Ctor(_8) -> (box ((match ((unbox (_8))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (i)) (box (r))))) | Data_Either_Rightusd_Ctor(_9) -> (box ((sharpurs_apply (box (Data_Void_absurd)) (box (_9))))))))))))))))))))))))))))))))))))))))

let Data_Either_Nested_either8  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (fun (g: obj) -> (fun (h: obj) -> (fun (y: obj) -> (match ((unbox (y))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (a)) (box (r))))) | Data_Either_Rightusd_Ctor(_1) -> (box ((match ((unbox (_1))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (b)) (box (r))))) | Data_Either_Rightusd_Ctor(_2) -> (box ((match ((unbox (_2))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (c)) (box (r))))) | Data_Either_Rightusd_Ctor(_3) -> (box ((match ((unbox (_3))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (d)) (box (r))))) | Data_Either_Rightusd_Ctor(_4) -> (box ((match ((unbox (_4))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (e)) (box (r))))) | Data_Either_Rightusd_Ctor(_5) -> (box ((match ((unbox (_5))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (f)) (box (r))))) | Data_Either_Rightusd_Ctor(_6) -> (box ((match ((unbox (_6))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (g)) (box (r))))) | Data_Either_Rightusd_Ctor(_7) -> (box ((match ((unbox (_7))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (h)) (box (r))))) | Data_Either_Rightusd_Ctor(_8) -> (box ((sharpurs_apply (box (Data_Void_absurd)) (box (_8))))))))))))))))))))))))))))))))))))

let Data_Either_Nested_either7  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (fun (g: obj) -> (fun (y: obj) -> (match ((unbox (y))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (a)) (box (r))))) | Data_Either_Rightusd_Ctor(_1) -> (box ((match ((unbox (_1))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (b)) (box (r))))) | Data_Either_Rightusd_Ctor(_2) -> (box ((match ((unbox (_2))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (c)) (box (r))))) | Data_Either_Rightusd_Ctor(_3) -> (box ((match ((unbox (_3))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (d)) (box (r))))) | Data_Either_Rightusd_Ctor(_4) -> (box ((match ((unbox (_4))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (e)) (box (r))))) | Data_Either_Rightusd_Ctor(_5) -> (box ((match ((unbox (_5))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (f)) (box (r))))) | Data_Either_Rightusd_Ctor(_6) -> (box ((match ((unbox (_6))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (g)) (box (r))))) | Data_Either_Rightusd_Ctor(_7) -> (box ((sharpurs_apply (box (Data_Void_absurd)) (box (_7))))))))))))))))))))))))))))))))

let Data_Either_Nested_either6  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (fun (y: obj) -> (match ((unbox (y))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (a)) (box (r))))) | Data_Either_Rightusd_Ctor(_1) -> (box ((match ((unbox (_1))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (b)) (box (r))))) | Data_Either_Rightusd_Ctor(_2) -> (box ((match ((unbox (_2))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (c)) (box (r))))) | Data_Either_Rightusd_Ctor(_3) -> (box ((match ((unbox (_3))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (d)) (box (r))))) | Data_Either_Rightusd_Ctor(_4) -> (box ((match ((unbox (_4))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (e)) (box (r))))) | Data_Either_Rightusd_Ctor(_5) -> (box ((match ((unbox (_5))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (f)) (box (r))))) | Data_Either_Rightusd_Ctor(_6) -> (box ((sharpurs_apply (box (Data_Void_absurd)) (box (_6))))))))))))))))))))))))))))

let Data_Either_Nested_either5  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (y: obj) -> (match ((unbox (y))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (a)) (box (r))))) | Data_Either_Rightusd_Ctor(_1) -> (box ((match ((unbox (_1))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (b)) (box (r))))) | Data_Either_Rightusd_Ctor(_2) -> (box ((match ((unbox (_2))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (c)) (box (r))))) | Data_Either_Rightusd_Ctor(_3) -> (box ((match ((unbox (_3))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (d)) (box (r))))) | Data_Either_Rightusd_Ctor(_4) -> (box ((match ((unbox (_4))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (e)) (box (r))))) | Data_Either_Rightusd_Ctor(_5) -> (box ((sharpurs_apply (box (Data_Void_absurd)) (box (_5))))))))))))))))))))))))

let Data_Either_Nested_either4  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (y: obj) -> (match ((unbox (y))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (a)) (box (r))))) | Data_Either_Rightusd_Ctor(_1) -> (box ((match ((unbox (_1))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (b)) (box (r))))) | Data_Either_Rightusd_Ctor(_2) -> (box ((match ((unbox (_2))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (c)) (box (r))))) | Data_Either_Rightusd_Ctor(_3) -> (box ((match ((unbox (_3))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (d)) (box (r))))) | Data_Either_Rightusd_Ctor(_4) -> (box ((sharpurs_apply (box (Data_Void_absurd)) (box (_4))))))))))))))))))))

let Data_Either_Nested_either3  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (y: obj) -> (match ((unbox (y))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (a)) (box (r))))) | Data_Either_Rightusd_Ctor(_1) -> (box ((match ((unbox (_1))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (b)) (box (r))))) | Data_Either_Rightusd_Ctor(_2) -> (box ((match ((unbox (_2))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (c)) (box (r))))) | Data_Either_Rightusd_Ctor(_3) -> (box ((sharpurs_apply (box (Data_Void_absurd)) (box (_3))))))))))))))))

let Data_Either_Nested_either2  = (fun (a: obj) -> (fun (b: obj) -> (fun (y: obj) -> (match ((unbox (y))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (a)) (box (r))))) | Data_Either_Rightusd_Ctor(_1) -> (box ((match ((unbox (_1))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (b)) (box (r))))) | Data_Either_Rightusd_Ctor(_2) -> (box ((sharpurs_apply (box (Data_Void_absurd)) (box (_2))))))))))))

let Data_Either_Nested_either10  = (fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (fun (g: obj) -> (fun (h: obj) -> (fun (i: obj) -> (fun (j: obj) -> (fun (y: obj) -> (match ((unbox (y))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (a)) (box (r))))) | Data_Either_Rightusd_Ctor(_1) -> (box ((match ((unbox (_1))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (b)) (box (r))))) | Data_Either_Rightusd_Ctor(_2) -> (box ((match ((unbox (_2))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (c)) (box (r))))) | Data_Either_Rightusd_Ctor(_3) -> (box ((match ((unbox (_3))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (d)) (box (r))))) | Data_Either_Rightusd_Ctor(_4) -> (box ((match ((unbox (_4))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (e)) (box (r))))) | Data_Either_Rightusd_Ctor(_5) -> (box ((match ((unbox (_5))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (f)) (box (r))))) | Data_Either_Rightusd_Ctor(_6) -> (box ((match ((unbox (_6))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (g)) (box (r))))) | Data_Either_Rightusd_Ctor(_7) -> (box ((match ((unbox (_7))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (h)) (box (r))))) | Data_Either_Rightusd_Ctor(_8) -> (box ((match ((unbox (_8))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (i)) (box (r))))) | Data_Either_Rightusd_Ctor(_9) -> (box ((match ((unbox (_9))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (j)) (box (r))))) | Data_Either_Rightusd_Ctor(_10) -> (box ((sharpurs_apply (box (Data_Void_absurd)) (box (_10))))))))))))))))))))))))))))))))))))))))))))

let Data_Either_Nested_either1  = (fun (y: obj) -> (match ((unbox (y))) with | Data_Either_Leftusd_Ctor(r) -> (box (r)) | Data_Either_Rightusd_Ctor(_1) -> (box ((sharpurs_apply (box (Data_Void_absurd)) (box (_1)))))))

let Data_Either_Nested_at9  = (fun (b: obj) -> (fun (f: obj) -> (fun (y: obj) -> (match ((unbox (y))) with | Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Leftusd_Ctor(r))))))))))))))))) -> (box ((sharpurs_apply (box (f)) (box (r))))) | _ -> (box (b))))))

let Data_Either_Nested_at8  = (fun (b: obj) -> (fun (f: obj) -> (fun (y: obj) -> (match ((unbox (y))) with | Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Leftusd_Ctor(r))))))))))))))) -> (box ((sharpurs_apply (box (f)) (box (r))))) | _ -> (box (b))))))

let Data_Either_Nested_at7  = (fun (b: obj) -> (fun (f: obj) -> (fun (y: obj) -> (match ((unbox (y))) with | Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Leftusd_Ctor(r))))))))))))) -> (box ((sharpurs_apply (box (f)) (box (r))))) | _ -> (box (b))))))

let Data_Either_Nested_at6  = (fun (b: obj) -> (fun (f: obj) -> (fun (y: obj) -> (match ((unbox (y))) with | Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Leftusd_Ctor(r))))))))))) -> (box ((sharpurs_apply (box (f)) (box (r))))) | _ -> (box (b))))))

let Data_Either_Nested_at5  = (fun (b: obj) -> (fun (f: obj) -> (fun (y: obj) -> (match ((unbox (y))) with | Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Leftusd_Ctor(r))))))))) -> (box ((sharpurs_apply (box (f)) (box (r))))) | _ -> (box (b))))))

let Data_Either_Nested_at4  = (fun (b: obj) -> (fun (f: obj) -> (fun (y: obj) -> (match ((unbox (y))) with | Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Leftusd_Ctor(r))))))) -> (box ((sharpurs_apply (box (f)) (box (r))))) | _ -> (box (b))))))

let Data_Either_Nested_at3  = (fun (b: obj) -> (fun (f: obj) -> (fun (y: obj) -> (match ((unbox (y))) with | Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Leftusd_Ctor(r))))) -> (box ((sharpurs_apply (box (f)) (box (r))))) | _ -> (box (b))))))

let Data_Either_Nested_at2  = (fun (b: obj) -> (fun (f: obj) -> (fun (y: obj) -> (match ((unbox (y))) with | Data_Either_Rightusd_Ctor(Unbox(Data_Either_Leftusd_Ctor(r))) -> (box ((sharpurs_apply (box (f)) (box (r))))) | _ -> (box (b))))))

let Data_Either_Nested_at10  = (fun (b: obj) -> (fun (f: obj) -> (fun (y: obj) -> (match ((unbox (y))) with | Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Leftusd_Ctor(r))))))))))))))))))) -> (box ((sharpurs_apply (box (f)) (box (r))))) | _ -> (box (b))))))

let Data_Either_Nested_at1  = (fun (b: obj) -> (fun (f: obj) -> (fun (y: obj) -> (match ((unbox (y))) with | Data_Either_Leftusd_Ctor(r) -> (box ((sharpurs_apply (box (f)) (box (r))))) | _ -> (box (b))))))
