[<AutoOpen>]
module PureScript_Data_List_Types

open System
open System.Collections.Generic

type Data_List_Types_List =
  | Data_List_Types_Nilusd_Ctor
  | Data_List_Types_Consusd_Ctor of obj * obj

let Data_List_Types_compose  = (sharpurs_apply (box (Control_Semigroupoid_compose)) (box (Control_Semigroupoid_semigroupoidFn)))

let Data_List_Types_add  = (sharpurs_apply (box (Data_Semiring_add)) (box (Data_Semiring_semiringInt)))

let Data_List_Types_sub  = (sharpurs_apply (box (Data_Ring_sub)) (box (Data_Ring_ringInt)))

let Data_List_Types_append  = (sharpurs_apply (box (Data_Semigroup_append)) (box (Data_Semigroup_semigroupString)))

let Data_List_Types_identity  = (sharpurs_apply (box (Control_Category_identity)) (box (Control_Category_categoryFn)))

let Data_List_Types_conj  = (sharpurs_apply (box (Data_HeytingAlgebra_conj)) (box (Data_HeytingAlgebra_heytingAlgebraBoolean)))

let Data_List_Types_Nil  = (box Data_List_Types_Nilusd_Ctor)

let Data_List_Types_Cons  = (fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Types_Consusd_Ctor(usd__arg1, usd__arg2)))))

let Data_List_Types_NonEmptyList  = (fun (x: obj) -> x)

let Data_List_Types_toList  = (fun (v: obj) -> (match ((unbox (v))) with | Data_NonEmpty_NonEmptyusd_Ctor(x, xs) -> (box ((box (Data_List_Types_Consusd_Ctor(x, xs)))))))

let Data_List_Types_newtypeNonEmptyList  = (sharpurs_apply (box (Data_Newtype_Newtypeusd_Dict)) (box ((Map.add "Coercible0" (box ((fun (_: obj) -> Prim_undefined))) Map.empty))))

let Data_List_Types_nelCons  = (fun (a: obj) -> (fun (v: obj) -> (match (((unbox (a)), (unbox (v)))) with | (a1, Data_NonEmpty_NonEmptyusd_Ctor(b, bs)) -> (box ((sharpurs_apply (box (Data_List_Types_NonEmptyList)) (box ((box (Data_NonEmpty_NonEmptyusd_Ctor(a1, (box (Data_List_Types_Consusd_Ctor(b, bs))))))))))))))

let Data_List_Types_listMap  = (fun (f: obj) -> (let mutable chunkedRevMap : obj = null in chunkedRevMap <- (fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (chunksAcc, (Data_List_Types_Consusd_Ctor(_, Unbox(Data_List_Types_Consusd_Ctor(_, Unbox(Data_List_Types_Consusd_Ctor(_, xs))))) as chunk)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (chunkedRevMap)) (box ((box (Data_List_Types_Consusd_Ctor(chunk, chunksAcc)))))))) (box (xs))))) | (chunksAcc, xs) -> (box ((let unrolledMap = (fun (v2: obj) -> (match ((unbox (v2))) with | Data_List_Types_Consusd_Ctor(x1, Unbox(Data_List_Types_Consusd_Ctor(x2, Unbox(Data_List_Types_Nilusd_Ctor)))) -> (box ((box (Data_List_Types_Consusd_Ctor((sharpurs_apply (box (f)) (box (x1))), (box (Data_List_Types_Consusd_Ctor((sharpurs_apply (box (f)) (box (x2))), (box Data_List_Types_Nilusd_Ctor))))))))) | Data_List_Types_Consusd_Ctor(x1, Unbox(Data_List_Types_Nilusd_Ctor)) -> (box ((box (Data_List_Types_Consusd_Ctor((sharpurs_apply (box (f)) (box (x1))), (box Data_List_Types_Nilusd_Ctor)))))) | _ -> (box ((box Data_List_Types_Nilusd_Ctor))))) in let mutable reverseUnrolledMap : obj = null in reverseUnrolledMap <- (fun (v2: obj) -> (fun (v3: obj) -> (match (((unbox (v2)), (unbox (v3)))) with | (Data_List_Types_Consusd_Ctor(Unbox(Data_List_Types_Consusd_Ctor(x1, Unbox(Data_List_Types_Consusd_Ctor(x2, Unbox(Data_List_Types_Consusd_Ctor(x3, _)))))), cs), acc) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (reverseUnrolledMap)) (box (cs))))) (box ((box (Data_List_Types_Consusd_Ctor((sharpurs_apply (box (f)) (box (x1))), (box (Data_List_Types_Consusd_Ctor((sharpurs_apply (box (f)) (box (x2))), (box (Data_List_Types_Consusd_Ctor((sharpurs_apply (box (f)) (box (x3))), acc)))))))))))))) | (_, acc) -> (box (acc))))); (sharpurs_apply (box ((sharpurs_apply (box (reverseUnrolledMap)) (box (chunksAcc))))) (box ((sharpurs_apply (box (unrolledMap)) (box (xs)))))))))))); (sharpurs_apply (box (chunkedRevMap)) (box ((box Data_List_Types_Nilusd_Ctor))))))

let Data_List_Types_functorList  = (sharpurs_apply (box (Data_Functor_Functorusd_Dict)) (box ((Map.add "map" (box (Data_List_Types_listMap)) Map.empty))))

let Data_List_Types_map  = (sharpurs_apply (box (Data_Functor_map)) (box (Data_List_Types_functorList)))

let Data_List_Types_functorNonEmptyList  = (sharpurs_apply (box (Data_NonEmpty_functorNonEmpty)) (box (Data_List_Types_functorList)))

let rec Data_List_Types_foldableList  = (sharpurs_apply (box (Data_Foldable_Foldableusd_Dict)) (box ((Map.add "foldr" (box ((fun (f: obj) -> (fun (b: obj) -> (let rev = (let mutable go : obj = null in go <- (fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (acc, Data_List_Types_Nilusd_Ctor) -> (box (acc)) | (acc, Data_List_Types_Consusd_Ctor(x, xs)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (go)) (box ((box (Data_List_Types_Consusd_Ctor(x, acc)))))))) (box (xs)))))))); (sharpurs_apply (box (go)) (box ((box Data_List_Types_Nilusd_Ctor))))) in (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_compose)) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Foldable_foldl)) (box (Data_List_Types_foldableList))))) (box ((sharpurs_apply (box (Data_Function_flip)) (box (f)))))))) (box (b)))))))) (box (rev)))))))) (Map.add "foldl" (box ((fun (f: obj) -> (let mutable go : obj = null in go <- (fun (b: obj) -> (fun (v: obj) -> (match ((unbox (v))) with | Data_List_Types_Nilusd_Ctor -> (box (b)) | Data_List_Types_Consusd_Ctor(a, as_) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (go)) (box ((sharpurs_apply (box ((sharpurs_apply (box (f)) (box (b))))) (box (a)))))))) (box (as_)))))))); go)))) (Map.add "foldMap" (box ((fun (dictMonoid: obj) -> (let append2 = (sharpurs_apply (box (Data_Semigroup_append)) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> (dictMonoid))))) (box (Prim_undefined)))))) in let mempty = (sharpurs_apply (box (Data_Monoid_mempty)) (box (dictMonoid))) in (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Foldable_foldl)) (box (Data_List_Types_foldableList))))) (box ((fun (acc: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_compose)) (box ((sharpurs_apply (box (append2)) (box (acc)))))))) (box (f))))))))) (box (mempty)))))))) Map.empty))))))

let Data_List_Types_foldl  = (sharpurs_apply (box (Data_Foldable_foldl)) (box (Data_List_Types_foldableList)))

let Data_List_Types_foldr  = (sharpurs_apply (box (Data_Foldable_foldr)) (box (Data_List_Types_foldableList)))

let Data_List_Types_intercalate  = (sharpurs_apply (box ((sharpurs_apply (box (Data_Foldable_intercalate)) (box (Data_List_Types_foldableList))))) (box (Data_Monoid_monoidString)))

let Data_List_Types_foldableNonEmptyList  = (sharpurs_apply (box (Data_NonEmpty_foldableNonEmpty)) (box (Data_List_Types_foldableList)))

let rec Data_List_Types_foldableWithIndexList  = (sharpurs_apply (box (Data_FoldableWithIndex_FoldableWithIndexusd_Dict)) (box ((Map.add "foldrWithIndex" (box ((fun (f: obj) -> (fun (b: obj) -> (fun (xs: obj) -> (let v = (let rev = (sharpurs_apply (box (Data_List_Types_foldl)) (box ((fun (v1: obj) -> (match ((unbox (v1))) with | Data_Tuple_Tupleusd_Ctor(i, acc) -> (box ((fun (a: obj) -> (box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_add)) (box (i))))) (box ((box 1)))), (box (Data_List_Types_Consusd_Ctor(a, acc)))))))))))))) in (sharpurs_apply (box ((sharpurs_apply (box (rev)) (box ((box (Data_Tuple_Tupleusd_Ctor((box 0), (box Data_List_Types_Nilusd_Ctor))))))))) (box (xs)))) in (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(len, revList) -> (box ((sharpurs_apply (box (Data_Tuple_snd)) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_foldl)) (box ((fun (v1: obj) -> (match ((unbox (v1))) with | Data_Tuple_Tupleusd_Ctor(i, b_prime) -> (box ((fun (a: obj) -> (box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_sub)) (box (i))))) (box ((box 1)))), (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (f)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_sub)) (box (i))))) (box ((box 1))))))))) (box (a))))) (box (b_prime)))))))))))))))) (box ((box (Data_Tuple_Tupleusd_Ctor(len, b)))))))) (box (revList))))))))))))))) (Map.add "foldlWithIndex" (box ((fun (f: obj) -> (fun (acc: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_compose)) (box (Data_Tuple_snd))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_foldl)) (box ((fun (v: obj) -> (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(i, b) -> (box ((fun (a: obj) -> (box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_add)) (box (i))))) (box ((box 1)))), (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (f)) (box (i))))) (box (b))))) (box (a)))))))))))))))) (box ((box (Data_Tuple_Tupleusd_Ctor((box 0), acc))))))))))))) (Map.add "foldMapWithIndex" (box ((fun (dictMonoid: obj) -> (let append2 = (sharpurs_apply (box (Data_Semigroup_append)) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> (dictMonoid))))) (box (Prim_undefined)))))) in let mempty = (sharpurs_apply (box (Data_Monoid_mempty)) (box (dictMonoid))) in (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_FoldableWithIndex_foldlWithIndex)) (box (Data_List_Types_foldableWithIndexList))))) (box ((fun (i: obj) -> (fun (acc: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_compose)) (box ((sharpurs_apply (box (append2)) (box (acc)))))))) (box ((sharpurs_apply (box (f)) (box (i))))))))))))) (box (mempty)))))))) (Map.add "Foldable0" (box ((fun (_: obj) -> Data_List_Types_foldableList))) Map.empty)))))))

let Data_List_Types_foldableWithIndexNonEmpty  = (sharpurs_apply (box (Data_NonEmpty_foldableWithIndexNonEmpty)) (box (Data_List_Types_foldableWithIndexList)))

let Data_List_Types_foldMapWithIndex  = (sharpurs_apply (box (Data_FoldableWithIndex_foldMapWithIndex)) (box (Data_List_Types_foldableWithIndexNonEmpty)))

let Data_List_Types_foldlWithIndex  = (sharpurs_apply (box (Data_FoldableWithIndex_foldlWithIndex)) (box (Data_List_Types_foldableWithIndexNonEmpty)))

let Data_List_Types_foldrWithIndex  = (sharpurs_apply (box (Data_FoldableWithIndex_foldrWithIndex)) (box (Data_List_Types_foldableWithIndexNonEmpty)))

let Data_List_Types_foldrWithIndex1  = (sharpurs_apply (box (Data_FoldableWithIndex_foldrWithIndex)) (box (Data_List_Types_foldableWithIndexList)))

let Data_List_Types_foldlWithIndex1  = (sharpurs_apply (box (Data_FoldableWithIndex_foldlWithIndex)) (box (Data_List_Types_foldableWithIndexList)))

let Data_List_Types_foldableWithIndexNonEmptyList  = (sharpurs_apply (box (Data_FoldableWithIndex_FoldableWithIndexusd_Dict)) (box ((Map.add "foldMapWithIndex" (box ((fun (dictMonoid: obj) -> (let foldMapWithIndex1 = (sharpurs_apply (box (Data_List_Types_foldMapWithIndex)) (box (dictMonoid))) in (fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, ne) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (foldMapWithIndex1)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_compose)) (box (f1))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Maybe_maybe)) (box ((box 0)))))) (box ((sharpurs_apply (box (Data_List_Types_add)) (box ((box 1))))))))))))))) (box (ne)))))))))))) (Map.add "foldlWithIndex" (box ((fun (f: obj) -> (fun (b: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (b)), (unbox (v)))) with | (f1, b1, ne) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_foldlWithIndex)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_compose)) (box (f1))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Maybe_maybe)) (box ((box 0)))))) (box ((sharpurs_apply (box (Data_List_Types_add)) (box ((box 1))))))))))))))) (box (b1))))) (box (ne))))))))))) (Map.add "foldrWithIndex" (box ((fun (f: obj) -> (fun (b: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (b)), (unbox (v)))) with | (f1, b1, ne) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_foldrWithIndex)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_compose)) (box (f1))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Maybe_maybe)) (box ((box 0)))))) (box ((sharpurs_apply (box (Data_List_Types_add)) (box ((box 1))))))))))))))) (box (b1))))) (box (ne))))))))))) (Map.add "Foldable0" (box ((fun (_: obj) -> Data_List_Types_foldableNonEmptyList))) Map.empty)))))))

let Data_List_Types_functorWithIndexList  = (sharpurs_apply (box (Data_FunctorWithIndex_FunctorWithIndexusd_Dict)) (box ((Map.add "mapWithIndex" (box ((fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_foldrWithIndex1)) (box ((fun (i: obj) -> (fun (x: obj) -> (fun (acc: obj) -> (box (Data_List_Types_Consusd_Ctor((sharpurs_apply (box ((sharpurs_apply (box (f)) (box (i))))) (box (x))), acc))))))))))) (box ((box Data_List_Types_Nilusd_Ctor))))))) (Map.add "Functor0" (box ((fun (_: obj) -> Data_List_Types_functorList))) Map.empty)))))

let Data_List_Types_mapWithIndex  = (sharpurs_apply (box (Data_FunctorWithIndex_mapWithIndex)) (box ((sharpurs_apply (box (Data_NonEmpty_functorWithIndex)) (box (Data_List_Types_functorWithIndexList))))))

let Data_List_Types_functorWithIndexNonEmptyList  = (sharpurs_apply (box (Data_FunctorWithIndex_FunctorWithIndexusd_Dict)) (box ((Map.add "mapWithIndex" (box ((fun (fn: obj) -> (fun (v: obj) -> (match (((unbox (fn)), (unbox (v)))) with | (fn1, ne) -> (box ((sharpurs_apply (box (Data_List_Types_NonEmptyList)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_mapWithIndex)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_compose)) (box (fn1))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Maybe_maybe)) (box ((box 0)))))) (box ((sharpurs_apply (box (Data_List_Types_add)) (box ((box 1))))))))))))))) (box (ne))))))))))))) (Map.add "Functor0" (box ((fun (_: obj) -> Data_List_Types_functorNonEmptyList))) Map.empty)))))

let Data_List_Types_semigroupList  = (sharpurs_apply (box (Data_Semigroup_Semigroupusd_Dict)) (box ((Map.add "append" (box ((fun (xs: obj) -> (fun (ys: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_foldr)) (box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Types_Consusd_Ctor(usd__arg1, usd__arg2)))))))))) (box (ys))))) (box (xs))))))) Map.empty))))

let Data_List_Types_append1  = (sharpurs_apply (box (Data_Semigroup_append)) (box (Data_List_Types_semigroupList)))

let Data_List_Types_monoidList  = (sharpurs_apply (box (Data_Monoid_Monoidusd_Dict)) (box ((Map.add "mempty" (box ((box Data_List_Types_Nilusd_Ctor))) (Map.add "Semigroup0" (box ((fun (_: obj) -> Data_List_Types_semigroupList))) Map.empty)))))

let Data_List_Types_semigroupNonEmptyList  = (sharpurs_apply (box (Data_Semigroup_Semigroupusd_Dict)) (box ((Map.add "append" (box ((fun (v: obj) -> (fun (as_prime: obj) -> (match (((unbox (v)), (unbox (as_prime)))) with | (Data_NonEmpty_NonEmptyusd_Ctor(a, as_), as_prime1) -> (box ((sharpurs_apply (box (Data_List_Types_NonEmptyList)) (box ((box (Data_NonEmpty_NonEmptyusd_Ctor(a, (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_append1)) (box (as_))))) (box ((sharpurs_apply (box (Data_List_Types_toList)) (box (as_prime1))))))))))))))))))) Map.empty))))

let Data_List_Types_showList  = (fun (dictShow: obj) -> (let show = (sharpurs_apply (box (Data_Show_show)) (box (dictShow))) in (sharpurs_apply (box (Data_Show_Showusd_Dict)) (box ((Map.add "show" (box ((fun (v: obj) -> (match ((unbox (v))) with | Data_List_Types_Nilusd_Ctor -> (box ((box "Nil"))) | xs -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_append)) (box ((box "(")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_append)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_intercalate)) (box ((box " : ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_map)) (box (show))))) (box (xs))))))))))) (box ((box " : Nil)"))))))))))))) Map.empty))))))

let Data_List_Types_showNonEmptyList  = (fun (dictShow: obj) -> (let show = (sharpurs_apply (box (Data_Show_show)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_NonEmpty_showNonEmpty)) (box (dictShow))))) (box ((sharpurs_apply (box (Data_List_Types_showList)) (box (dictShow))))))))) in (sharpurs_apply (box (Data_Show_Showusd_Dict)) (box ((Map.add "show" (box ((fun (v: obj) -> (match ((unbox (v))) with | nel -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_append)) (box ((box "(NonEmptyList ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_append)) (box ((sharpurs_apply (box (show)) (box (nel)))))))) (box ((box ")"))))))))))))) Map.empty))))))

let rec Data_List_Types_traversableList  = (sharpurs_apply (box (Data_Traversable_Traversableusd_Dict)) (box ((Map.add "traverse" (box ((fun (dictApplicative: obj) -> (let Apply0 = (sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> (dictApplicative))))) (box (Prim_undefined))) in let map1 = (sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (Apply0))))) (box (Prim_undefined)))))) in let lift2 = (sharpurs_apply (box (Control_Apply_lift2)) (box (Apply0))) in let pure1 = (sharpurs_apply (box (Control_Applicative_pure)) (box (dictApplicative))) in (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_compose)) (box ((sharpurs_apply (box (map1)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_foldl)) (box ((sharpurs_apply (box (Data_Function_flip)) (box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))))))) (box ((box Data_List_Types_Nilusd_Ctor)))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_foldl)) (box ((fun (acc: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_compose)) (box ((sharpurs_apply (box ((sharpurs_apply (box (lift2)) (box ((sharpurs_apply (box (Data_Function_flip)) (box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))))))) (box (acc)))))))) (box (f))))))))) (box ((sharpurs_apply (box (pure1)) (box ((box Data_List_Types_Nilusd_Ctor))))))))))))))) (Map.add "sequence" (box ((fun (dictApplicative: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Traversable_traverse)) (box (Data_List_Types_traversableList))))) (box (dictApplicative))))) (box (Data_List_Types_identity)))))) (Map.add "Functor0" (box ((fun (_: obj) -> Data_List_Types_functorList))) (Map.add "Foldable1" (box ((fun (_: obj) -> Data_List_Types_foldableList))) Map.empty)))))))

let Data_List_Types_traversableNonEmptyList  = (sharpurs_apply (box (Data_NonEmpty_traversableNonEmpty)) (box (Data_List_Types_traversableList)))

let Data_List_Types_traversableWithIndexList  = (sharpurs_apply (box (Data_TraversableWithIndex_TraversableWithIndexusd_Dict)) (box ((Map.add "traverseWithIndex" (box ((fun (dictApplicative: obj) -> (let Apply0 = (sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> (dictApplicative))))) (box (Prim_undefined))) in let map1 = (sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (Apply0))))) (box (Prim_undefined)))))) in let lift2 = (sharpurs_apply (box (Control_Apply_lift2)) (box (Apply0))) in let pure1 = (sharpurs_apply (box (Control_Applicative_pure)) (box (dictApplicative))) in (fun (f: obj) -> (let rev = (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_foldl)) (box ((sharpurs_apply (box (Data_Function_flip)) (box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))))))) (box ((box Data_List_Types_Nilusd_Ctor)))) in (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_compose)) (box ((sharpurs_apply (box (map1)) (box (rev)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_foldlWithIndex1)) (box ((fun (i: obj) -> (fun (acc: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_compose)) (box ((sharpurs_apply (box ((sharpurs_apply (box (lift2)) (box ((sharpurs_apply (box (Data_Function_flip)) (box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))))))) (box (acc)))))))) (box ((sharpurs_apply (box (f)) (box (i))))))))))))) (box ((sharpurs_apply (box (pure1)) (box ((box Data_List_Types_Nilusd_Ctor)))))))))))))))) (Map.add "FunctorWithIndex0" (box ((fun (_: obj) -> Data_List_Types_functorWithIndexList))) (Map.add "FoldableWithIndex1" (box ((fun (_: obj) -> Data_List_Types_foldableWithIndexList))) (Map.add "Traversable2" (box ((fun (_: obj) -> Data_List_Types_traversableList))) Map.empty)))))))

let Data_List_Types_traverseWithIndex  = (sharpurs_apply (box (Data_TraversableWithIndex_traverseWithIndex)) (box ((sharpurs_apply (box (Data_NonEmpty_traversableWithIndexNonEmpty)) (box (Data_List_Types_traversableWithIndexList))))))

let Data_List_Types_traversableWithIndexNonEmptyList  = (sharpurs_apply (box (Data_TraversableWithIndex_TraversableWithIndexusd_Dict)) (box ((Map.add "traverseWithIndex" (box ((fun (dictApplicative: obj) -> (let map1 = (sharpurs_apply (box (Data_Functor_map)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> (dictApplicative))))) (box (Prim_undefined)))))))) (box (Prim_undefined)))))) in let traverseWithIndex1 = (sharpurs_apply (box (Data_List_Types_traverseWithIndex)) (box (dictApplicative))) in (fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, ne) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (map1)) (box (Data_List_Types_NonEmptyList))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (traverseWithIndex1)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_compose)) (box (f1))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Maybe_maybe)) (box ((box 0)))))) (box ((sharpurs_apply (box (Data_List_Types_add)) (box ((box 1))))))))))))))) (box (ne))))))))))))))) (Map.add "FunctorWithIndex0" (box ((fun (_: obj) -> Data_List_Types_functorWithIndexNonEmptyList))) (Map.add "FoldableWithIndex1" (box ((fun (_: obj) -> Data_List_Types_foldableWithIndexNonEmptyList))) (Map.add "Traversable2" (box ((fun (_: obj) -> Data_List_Types_traversableNonEmptyList))) Map.empty)))))))

let Data_List_Types_unfoldable1List  = (sharpurs_apply (box (Data_Unfoldable1_Unfoldable1usd_Dict)) (box ((Map.add "unfoldr1" (box ((fun (f: obj) -> (fun (b: obj) -> (let mutable go : obj = null in go <- (fun (source: obj) -> (fun (memo: obj) -> (let v = (sharpurs_apply (box (f)) (box (source))) in (match ((unbox (v))) with | Data_Tuple_Tupleusd_Ctor(one, Unbox(Data_Maybe_Justusd_Ctor(rest))) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (go)) (box (rest))))) (box ((box (Data_List_Types_Consusd_Ctor(one, memo)))))))) | Data_Tuple_Tupleusd_Ctor(one, Unbox(Data_Maybe_Nothingusd_Ctor)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_foldl)) (box ((sharpurs_apply (box (Data_Function_flip)) (box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))))))) (box ((box Data_List_Types_Nilusd_Ctor)))))) (box ((box (Data_List_Types_Consusd_Ctor(one, memo)))))))))))); (sharpurs_apply (box ((sharpurs_apply (box (go)) (box (b))))) (box ((box Data_List_Types_Nilusd_Ctor))))))))) Map.empty))))

let Data_List_Types_unfoldableList  = (sharpurs_apply (box (Data_Unfoldable_Unfoldableusd_Dict)) (box ((Map.add "unfoldr" (box ((fun (f: obj) -> (fun (b: obj) -> (let mutable go : obj = null in go <- (fun (source: obj) -> (fun (memo: obj) -> (let v = (sharpurs_apply (box (f)) (box (source))) in (match ((unbox (v))) with | Data_Maybe_Nothingusd_Ctor -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_foldl)) (box ((sharpurs_apply (box (Data_Function_flip)) (box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))))))) (box ((box Data_List_Types_Nilusd_Ctor)))))) (box (memo))))) | Data_Maybe_Justusd_Ctor(Unbox(Data_Tuple_Tupleusd_Ctor(one, rest))) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (go)) (box (rest))))) (box ((box (Data_List_Types_Consusd_Ctor(one, memo)))))))))))); (sharpurs_apply (box ((sharpurs_apply (box (go)) (box (b))))) (box ((box Data_List_Types_Nilusd_Ctor))))))))) (Map.add "Unfoldable10" (box ((fun (_: obj) -> Data_List_Types_unfoldable1List))) Map.empty)))))

let Data_List_Types_unfoldable1NonEmptyList  = (sharpurs_apply (box (Data_NonEmpty_unfoldable1NonEmpty)) (box (Data_List_Types_unfoldableList)))

let Data_List_Types_foldable1NonEmptyList  = (sharpurs_apply (box (Data_NonEmpty_foldable1NonEmpty)) (box (Data_List_Types_foldableList)))

let Data_List_Types_extendNonEmptyList  = (sharpurs_apply (box (Control_Extend_Extendusd_Dict)) (box ((Map.add "extend" (box ((fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, (Data_NonEmpty_NonEmptyusd_Ctor(_, as_) as w)) -> (box ((let go = (fun (a: obj) -> (fun (v1: obj) -> (match (((unbox (a)), (unbox (v1)))) with | (a1, (HasProp "val" (val_) & HasProp "acc" (acc))) -> (box ((Map.add "val" (box ((box (Data_List_Types_Consusd_Ctor((sharpurs_apply (box (f1)) (box ((sharpurs_apply (box (Data_List_Types_NonEmptyList)) (box ((box (Data_NonEmpty_NonEmptyusd_Ctor(a1, acc))))))))), val_))))) (Map.add "acc" (box ((box (Data_List_Types_Consusd_Ctor(a1, acc))))) Map.empty))))))) in (sharpurs_apply (box (Data_List_Types_NonEmptyList)) (box ((box (Data_NonEmpty_NonEmptyusd_Ctor((sharpurs_apply (box (f1)) (box (w))), (Map.find "val" (unbox<Map<string, obj>> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_foldr)) (box (go))))) (box ((Map.add "val" (box ((box Data_List_Types_Nilusd_Ctor))) (Map.add "acc" (box ((box Data_List_Types_Nilusd_Ctor))) Map.empty))))))) (box (as_)))))))))))))))))))) (Map.add "Functor0" (box ((fun (_: obj) -> Data_List_Types_functorNonEmptyList))) Map.empty)))))

let Data_List_Types_extendList  = (sharpurs_apply (box (Control_Extend_Extendusd_Dict)) (box ((Map.add "extend" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (_, Data_List_Types_Nilusd_Ctor) -> (box ((box Data_List_Types_Nilusd_Ctor))) | (f, (Data_List_Types_Consusd_Ctor(_, as_) as l)) -> (box ((let go = (fun (a_prime: obj) -> (fun (v2: obj) -> (match (((unbox (a_prime)), (unbox (v2)))) with | (a_prime1, (HasProp "val" (val_) & HasProp "acc" (acc))) -> (box ((let acc_prime = (box (Data_List_Types_Consusd_Ctor(a_prime1, acc))) in (Map.add "val" (box ((box (Data_List_Types_Consusd_Ctor((sharpurs_apply (box (f)) (box (acc_prime))), val_))))) (Map.add "acc" (box (acc_prime)) Map.empty)))))))) in (box (Data_List_Types_Consusd_Ctor((sharpurs_apply (box (f)) (box (l))), (Map.find "val" (unbox<Map<string, obj>> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_foldr)) (box (go))))) (box ((Map.add "val" (box ((box Data_List_Types_Nilusd_Ctor))) (Map.add "acc" (box ((box Data_List_Types_Nilusd_Ctor))) Map.empty))))))) (box (as_))))))))))))))))) (Map.add "Functor0" (box ((fun (_: obj) -> Data_List_Types_functorList))) Map.empty)))))

let Data_List_Types_eq1List  = (sharpurs_apply (box (Data_Eq_Eq1usd_Dict)) (box ((Map.add "eq1" (box ((fun (dictEq: obj) -> (let eq = (sharpurs_apply (box (Data_Eq_eq)) (box (dictEq))) in (fun (xs: obj) -> (fun (ys: obj) -> (let mutable go : obj = null in go <- (fun (v: obj) -> (fun (v1: obj) -> (fun (v2: obj) -> (match (((unbox (v)), (unbox (v1)), (unbox (v2)))) with | (_, _, LitBool false ()) -> (box ((box false))) | (Data_List_Types_Nilusd_Ctor, Data_List_Types_Nilusd_Ctor, acc) -> (box (acc)) | (Data_List_Types_Consusd_Ctor(x, xs_prime), Data_List_Types_Consusd_Ctor(y, ys_prime), acc) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (go)) (box (xs_prime))))) (box (ys_prime))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_conj)) (box (acc))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (eq)) (box (y))))) (box (x))))))))))) | (_, _, _) -> (box ((box false))))))); (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (go)) (box (xs))))) (box (ys))))) (box ((box true))))))))))) Map.empty))))

let Data_List_Types_eq1  = (sharpurs_apply (box (Data_Eq_eq1)) (box (Data_List_Types_eq1List)))

let Data_List_Types_eqNonEmpty  = (sharpurs_apply (box (Data_NonEmpty_eqNonEmpty)) (box (Data_List_Types_eq1List)))

let Data_List_Types_eq1NonEmptyList  = (sharpurs_apply (box (Data_NonEmpty_eq1NonEmpty)) (box (Data_List_Types_eq1List)))

let Data_List_Types_eqList  = (fun (dictEq: obj) -> (sharpurs_apply (box (Data_Eq_Equsd_Dict)) (box ((Map.add "eq" (box ((sharpurs_apply (box (Data_List_Types_eq1)) (box (dictEq))))) Map.empty)))))

let Data_List_Types_eqNonEmptyList  = (fun (dictEq: obj) -> (sharpurs_apply (box (Data_List_Types_eqNonEmpty)) (box (dictEq))))

let Data_List_Types_ord1List  = (sharpurs_apply (box (Data_Ord_Ord1usd_Dict)) (box ((Map.add "compare1" (box ((fun (dictOrd: obj) -> (let compare = (sharpurs_apply (box (Data_Ord_compare)) (box (dictOrd))) in (fun (xs: obj) -> (fun (ys: obj) -> (let mutable go : obj = null in go <- (fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (Data_List_Types_Nilusd_Ctor, Data_List_Types_Nilusd_Ctor) -> (box ((box Data_Ordering_EQusd_Ctor))) | (Data_List_Types_Nilusd_Ctor, _) -> (box ((box Data_Ordering_LTusd_Ctor))) | (_, Data_List_Types_Nilusd_Ctor) -> (box ((box Data_Ordering_GTusd_Ctor))) | (Data_List_Types_Consusd_Ctor(x, xs_prime), Data_List_Types_Consusd_Ctor(y, ys_prime)) -> (box ((let v2 = (sharpurs_apply (box ((sharpurs_apply (box (compare)) (box (x))))) (box (y))) in (match ((unbox (v2))) with | Data_Ordering_EQusd_Ctor -> (box ((sharpurs_apply (box ((sharpurs_apply (box (go)) (box (xs_prime))))) (box (ys_prime))))) | other -> (box (other))))))))); (sharpurs_apply (box ((sharpurs_apply (box (go)) (box (xs))))) (box (ys)))))))))) (Map.add "Eq10" (box ((fun (_: obj) -> Data_List_Types_eq1List))) Map.empty)))))

let Data_List_Types_compare1  = (sharpurs_apply (box (Data_Ord_compare1)) (box (Data_List_Types_ord1List)))

let Data_List_Types_ordNonEmpty  = (sharpurs_apply (box (Data_NonEmpty_ordNonEmpty)) (box (Data_List_Types_ord1List)))

let Data_List_Types_ord1NonEmptyList  = (sharpurs_apply (box (Data_NonEmpty_ord1NonEmpty)) (box (Data_List_Types_ord1List)))

let Data_List_Types_ordList  = (fun (dictOrd: obj) -> (let eqList1 = (sharpurs_apply (box (Data_List_Types_eqList)) (box ((sharpurs_apply (box ((Map.find "Eq0" (unbox<Map<string, obj>> (dictOrd))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Ord_Ordusd_Dict)) (box ((Map.add "compare" (box ((sharpurs_apply (box (Data_List_Types_compare1)) (box (dictOrd))))) (Map.add "Eq0" (box ((fun (_: obj) -> eqList1))) Map.empty)))))))

let Data_List_Types_ordNonEmptyList  = (fun (dictOrd: obj) -> (sharpurs_apply (box (Data_List_Types_ordNonEmpty)) (box (dictOrd))))

let Data_List_Types_comonadNonEmptyList  = (sharpurs_apply (box (Control_Comonad_Comonadusd_Dict)) (box ((Map.add "extract" (box ((fun (v: obj) -> (match ((unbox (v))) with | Data_NonEmpty_NonEmptyusd_Ctor(a, _) -> (box (a)))))) (Map.add "Extend0" (box ((fun (_: obj) -> Data_List_Types_extendNonEmptyList))) Map.empty)))))

let rec Data_List_Types_applyList  = (sharpurs_apply (box (Control_Apply_Applyusd_Dict)) (box ((Map.add "apply" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (Data_List_Types_Nilusd_Ctor, _) -> (box ((box Data_List_Types_Nilusd_Ctor))) | (Data_List_Types_Consusd_Ctor(f, fs), xs) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_append1)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_map)) (box (f))))) (box (xs)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Control_Apply_apply)) (box (Data_List_Types_applyList))))) (box (fs))))) (box (xs))))))))))))) (Map.add "Functor0" (box ((fun (_: obj) -> Data_List_Types_functorList))) Map.empty)))))

let Data_List_Types_apply  = (sharpurs_apply (box (Control_Apply_apply)) (box (Data_List_Types_applyList)))

let Data_List_Types_applyNonEmptyList  = (sharpurs_apply (box (Control_Apply_Applyusd_Dict)) (box ((Map.add "apply" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (Data_NonEmpty_NonEmptyusd_Ctor(f, fs), Data_NonEmpty_NonEmptyusd_Ctor(a, as_)) -> (box ((sharpurs_apply (box (Data_List_Types_NonEmptyList)) (box ((box (Data_NonEmpty_NonEmptyusd_Ctor((sharpurs_apply (box (f)) (box (a))), (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_append1)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_apply)) (box (fs))))) (box ((box (Data_List_Types_Consusd_Ctor(a, (box Data_List_Types_Nilusd_Ctor)))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_apply)) (box ((box (Data_List_Types_Consusd_Ctor(f, fs)))))))) (box (as_))))))))))))))))))) (Map.add "Functor0" (box ((fun (_: obj) -> Data_List_Types_functorNonEmptyList))) Map.empty)))))

let rec Data_List_Types_bindList  = (sharpurs_apply (box (Control_Bind_Bindusd_Dict)) (box ((Map.add "bind" (box ((fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (Data_List_Types_Nilusd_Ctor, _) -> (box ((box Data_List_Types_Nilusd_Ctor))) | (Data_List_Types_Consusd_Ctor(x, xs), f) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_append1)) (box ((sharpurs_apply (box (f)) (box (x)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Control_Bind_bind)) (box (Data_List_Types_bindList))))) (box (xs))))) (box (f))))))))))))) (Map.add "Apply0" (box ((fun (_: obj) -> Data_List_Types_applyList))) Map.empty)))))

let Data_List_Types_bind  = (sharpurs_apply (box (Control_Bind_bind)) (box (Data_List_Types_bindList)))

let Data_List_Types_bindNonEmptyList  = (sharpurs_apply (box (Control_Bind_Bindusd_Dict)) (box ((Map.add "bind" (box ((fun (v: obj) -> (fun (f: obj) -> (match (((unbox (v)), (unbox (f)))) with | (Data_NonEmpty_NonEmptyusd_Ctor(a, as_), f1) -> (box ((let v1 = (sharpurs_apply (box (f1)) (box (a))) in (match ((unbox (v1))) with | Data_NonEmpty_NonEmptyusd_Ctor(b, bs) -> (box ((sharpurs_apply (box (Data_List_Types_NonEmptyList)) (box ((box (Data_NonEmpty_NonEmptyusd_Ctor(b, (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_append1)) (box (bs))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_bind)) (box (as_))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_compose)) (box (Data_List_Types_toList))))) (box (f1)))))))))))))))))))))))))) (Map.add "Apply0" (box ((fun (_: obj) -> Data_List_Types_applyNonEmptyList))) Map.empty)))))

let Data_List_Types_applicativeList  = (sharpurs_apply (box (Control_Applicative_Applicativeusd_Dict)) (box ((Map.add "pure" (box ((fun (a: obj) -> (box (Data_List_Types_Consusd_Ctor(a, (box Data_List_Types_Nilusd_Ctor))))))) (Map.add "Apply0" (box ((fun (_: obj) -> Data_List_Types_applyList))) Map.empty)))))

let Data_List_Types_monadList  = (sharpurs_apply (box (Control_Monad_Monadusd_Dict)) (box ((Map.add "Applicative0" (box ((fun (_: obj) -> Data_List_Types_applicativeList))) (Map.add "Bind1" (box ((fun (_: obj) -> Data_List_Types_bindList))) Map.empty)))))

let Data_List_Types_altNonEmptyList  = (sharpurs_apply (box (Control_Alt_Altusd_Dict)) (box ((Map.add "alt" (box ((sharpurs_apply (box (Data_Semigroup_append)) (box (Data_List_Types_semigroupNonEmptyList))))) (Map.add "Functor0" (box ((fun (_: obj) -> Data_List_Types_functorNonEmptyList))) Map.empty)))))

let Data_List_Types_altList  = (sharpurs_apply (box (Control_Alt_Altusd_Dict)) (box ((Map.add "alt" (box (Data_List_Types_append1)) (Map.add "Functor0" (box ((fun (_: obj) -> Data_List_Types_functorList))) Map.empty)))))

let Data_List_Types_plusList  = (sharpurs_apply (box (Control_Plus_Plususd_Dict)) (box ((Map.add "empty" (box ((box Data_List_Types_Nilusd_Ctor))) (Map.add "Alt0" (box ((fun (_: obj) -> Data_List_Types_altList))) Map.empty)))))

let Data_List_Types_alternativeList  = (sharpurs_apply (box (Control_Alternative_Alternativeusd_Dict)) (box ((Map.add "Applicative0" (box ((fun (_: obj) -> Data_List_Types_applicativeList))) (Map.add "Plus1" (box ((fun (_: obj) -> Data_List_Types_plusList))) Map.empty)))))

let Data_List_Types_monadPlusList  = (sharpurs_apply (box (Control_MonadPlus_MonadPlususd_Dict)) (box ((Map.add "Monad0" (box ((fun (_: obj) -> Data_List_Types_monadList))) (Map.add "Alternative1" (box ((fun (_: obj) -> Data_List_Types_alternativeList))) Map.empty)))))

let Data_List_Types_applicativeNonEmptyList  = (sharpurs_apply (box (Control_Applicative_Applicativeusd_Dict)) (box ((Map.add "pure" (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_compose)) (box (Data_List_Types_NonEmptyList))))) (box ((sharpurs_apply (box (Data_NonEmpty_singleton)) (box (Data_List_Types_plusList)))))))) (Map.add "Apply0" (box ((fun (_: obj) -> Data_List_Types_applyNonEmptyList))) Map.empty)))))

let Data_List_Types_pure  = (sharpurs_apply (box (Control_Applicative_pure)) (box (Data_List_Types_applicativeNonEmptyList)))

let Data_List_Types_monadNonEmptyList  = (sharpurs_apply (box (Control_Monad_Monadusd_Dict)) (box ((Map.add "Applicative0" (box ((fun (_: obj) -> Data_List_Types_applicativeNonEmptyList))) (Map.add "Bind1" (box ((fun (_: obj) -> Data_List_Types_bindNonEmptyList))) Map.empty)))))

let rec Data_List_Types_traversable1NonEmptyList  = (sharpurs_apply (box (Data_Semigroup_Traversable_Traversable1usd_Dict)) (box ((Map.add "traverse1" (box ((fun (dictApply: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (dictApply))))) (box (Prim_undefined))) in let mapFlipped = (sharpurs_apply (box (Data_Functor_mapFlipped)) (box (Functor0))) in let lift2 = (sharpurs_apply (box (Control_Apply_lift2)) (box (dictApply))) in let map1 = (sharpurs_apply (box (Data_Functor_map)) (box (Functor0))) in (fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, Data_NonEmpty_NonEmptyusd_Ctor(a, as_)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (mapFlipped)) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_foldl)) (box ((fun (acc: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_compose)) (box ((sharpurs_apply (box ((sharpurs_apply (box (lift2)) (box ((sharpurs_apply (box (Data_Function_flip)) (box (Data_List_Types_nelCons)))))))) (box (acc)))))))) (box (f1))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (map1)) (box (Data_List_Types_pure))))) (box ((sharpurs_apply (box (f1)) (box (a))))))))))) (box (as_)))))))) (box ((fun (v1: obj) -> (match ((unbox (v1))) with | Data_NonEmpty_NonEmptyusd_Ctor(x, xs) -> (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_List_Types_foldl)) (box ((sharpurs_apply (box (Data_Function_flip)) (box (Data_List_Types_nelCons)))))))) (box ((sharpurs_apply (box (Data_List_Types_pure)) (box (x)))))))) (box (xs))))))))))))))))))) (Map.add "sequence1" (box ((fun (dictApply: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Semigroup_Traversable_traverse1)) (box (Data_List_Types_traversable1NonEmptyList))))) (box (dictApply))))) (box (Data_List_Types_identity)))))) (Map.add "Foldable10" (box ((fun (_: obj) -> Data_List_Types_foldable1NonEmptyList))) (Map.add "Traversable1" (box ((fun (_: obj) -> Data_List_Types_traversableNonEmptyList))) Map.empty)))))))
