[<AutoOpen>]
module PureScript_Data_Functor_Coproduct

open System
open System.Collections.Generic

let Data_Functor_Coproduct_append  = (sharpurs_apply (box (Data_Semigroup_append)) (box (Data_Semigroup_semigroupString)))

let Data_Functor_Coproduct_bimap  = (sharpurs_apply (box (Data_Bifunctor_bimap)) (box (Data_Bifunctor_bifunctorEither)))

let Data_Functor_Coproduct_compose  = (sharpurs_apply (box (Control_Semigroupoid_compose)) (box (Control_Semigroupoid_semigroupoidFn)))

let Data_Functor_Coproduct_Coproduct  = (fun (x: obj) -> x)

let Data_Functor_Coproduct_showCoproduct  = (fun (dictShow: obj) -> (let show = (sharpurs_apply (box (Data_Show_show)) (box (dictShow))) in (fun (dictShow1: obj) -> (let show1 = (sharpurs_apply (box (Data_Show_show)) (box (dictShow1))) in (sharpurs_apply (box (Data_Show_Showusd_Dict)) (box ((Map.add "show" (box ((fun (v: obj) -> (match ((unbox (v))) with | Data_Either_Leftusd_Ctor(fa) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Coproduct_append)) (box ((box "(left ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Coproduct_append)) (box ((sharpurs_apply (box (show)) (box (fa)))))))) (box ((box ")"))))))))) | Data_Either_Rightusd_Ctor(ga) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Coproduct_append)) (box ((box "(right ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Coproduct_append)) (box ((sharpurs_apply (box (show1)) (box (ga)))))))) (box ((box ")"))))))))))))) Map.empty))))))))

let Data_Functor_Coproduct_right  = (fun (ga: obj) -> (sharpurs_apply (box (Data_Functor_Coproduct_Coproduct)) (box ((box (Data_Either_Rightusd_Ctor(ga)))))))

let Data_Functor_Coproduct_newtypeCoproduct  = (sharpurs_apply (box (Data_Newtype_Newtypeusd_Dict)) (box ((Map.add "Coercible0" (box ((fun (_: obj) -> Prim_undefined))) Map.empty))))

let Data_Functor_Coproduct_left  = (fun (fa: obj) -> (sharpurs_apply (box (Data_Functor_Coproduct_Coproduct)) (box ((box (Data_Either_Leftusd_Ctor(fa)))))))

let Data_Functor_Coproduct_functorCoproduct  = (fun (dictFunctor: obj) -> (let map = (sharpurs_apply (box (Data_Functor_map)) (box (dictFunctor))) in (fun (dictFunctor1: obj) -> (let map1 = (sharpurs_apply (box (Data_Functor_map)) (box (dictFunctor1))) in (sharpurs_apply (box (Data_Functor_Functorusd_Dict)) (box ((Map.add "map" (box ((fun (f: obj) -> (fun (v: obj) -> (match (((unbox (f)), (unbox (v)))) with | (f1, e) -> (box ((sharpurs_apply (box (Data_Functor_Coproduct_Coproduct)) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Coproduct_bimap)) (box ((sharpurs_apply (box (map)) (box (f1)))))))) (box ((sharpurs_apply (box (map1)) (box (f1)))))))) (box (e))))))))))))) Map.empty))))))))

let Data_Functor_Coproduct_eq1Coproduct  = (fun (dictEq1: obj) -> (let eq1 = (sharpurs_apply (box (Data_Eq_eq1)) (box (dictEq1))) in (fun (dictEq11: obj) -> (let eq11 = (sharpurs_apply (box (Data_Eq_eq1)) (box (dictEq11))) in (sharpurs_apply (box (Data_Eq_Eq1usd_Dict)) (box ((Map.add "eq1" (box ((fun (dictEq: obj) -> (let eq12 = (sharpurs_apply (box (eq1)) (box (dictEq))) in let eq13 = (sharpurs_apply (box (eq11)) (box (dictEq))) in (fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (x, y) -> (box ((match (((unbox (x)), (unbox (y)))) with | (Data_Either_Leftusd_Ctor(fa), Data_Either_Leftusd_Ctor(ga)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (eq12)) (box (fa))))) (box (ga))))) | (Data_Either_Rightusd_Ctor(fa), Data_Either_Rightusd_Ctor(ga)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (eq13)) (box (fa))))) (box (ga))))) | (_, _) -> (box ((box false))))))))))))) Map.empty))))))))

let Data_Functor_Coproduct_eqCoproduct  = (fun (dictEq1: obj) -> (let eq1Coproduct1 = (sharpurs_apply (box (Data_Functor_Coproduct_eq1Coproduct)) (box (dictEq1))) in (fun (dictEq11: obj) -> (let eq1 = (sharpurs_apply (box (Data_Eq_eq1)) (box ((sharpurs_apply (box (eq1Coproduct1)) (box (dictEq11)))))) in (fun (dictEq: obj) -> (sharpurs_apply (box (Data_Eq_Equsd_Dict)) (box ((Map.add "eq" (box ((sharpurs_apply (box (eq1)) (box (dictEq))))) Map.empty)))))))))

let Data_Functor_Coproduct_ord1Coproduct  = (fun (dictOrd1: obj) -> (let compare1 = (sharpurs_apply (box (Data_Ord_compare1)) (box (dictOrd1))) in let eq1Coproduct1 = (sharpurs_apply (box (Data_Functor_Coproduct_eq1Coproduct)) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> (dictOrd1))))) (box (Prim_undefined)))))) in (fun (dictOrd11: obj) -> (let compare11 = (sharpurs_apply (box (Data_Ord_compare1)) (box (dictOrd11))) in let eq1Coproduct2 = (sharpurs_apply (box (eq1Coproduct1)) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> (dictOrd11))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Ord_Ord1usd_Dict)) (box ((Map.add "compare1" (box ((fun (dictOrd: obj) -> (let compare12 = (sharpurs_apply (box (compare1)) (box (dictOrd))) in let compare13 = (sharpurs_apply (box (compare11)) (box (dictOrd))) in (fun (v: obj) -> (fun (v1: obj) -> (match (((unbox (v)), (unbox (v1)))) with | (x, y) -> (box ((match (((unbox (x)), (unbox (y)))) with | (Data_Either_Leftusd_Ctor(fa), Data_Either_Leftusd_Ctor(ga)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (compare12)) (box (fa))))) (box (ga))))) | (Data_Either_Leftusd_Ctor(_), _) -> (box ((box Data_Ordering_LTusd_Ctor))) | (_, Data_Either_Leftusd_Ctor(_)) -> (box ((box Data_Ordering_GTusd_Ctor))) | (Data_Either_Rightusd_Ctor(fa), Data_Either_Rightusd_Ctor(ga)) -> (box ((sharpurs_apply (box ((sharpurs_apply (box (compare13)) (box (fa))))) (box (ga))))))))))))))) (Map.add "Eq10" (box ((fun (_: obj) -> eq1Coproduct2))) Map.empty)))))))))

let Data_Functor_Coproduct_ordCoproduct  = (fun (dictOrd1: obj) -> (let ord1Coproduct1 = (sharpurs_apply (box (Data_Functor_Coproduct_ord1Coproduct)) (box (dictOrd1))) in let eqCoproduct1 = (sharpurs_apply (box (Data_Functor_Coproduct_eqCoproduct)) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> (dictOrd1))))) (box (Prim_undefined)))))) in (fun (dictOrd11: obj) -> (let compare1 = (sharpurs_apply (box (Data_Ord_compare1)) (box ((sharpurs_apply (box (ord1Coproduct1)) (box (dictOrd11)))))) in let eqCoproduct2 = (sharpurs_apply (box (eqCoproduct1)) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> (dictOrd11))))) (box (Prim_undefined)))))) in (fun (dictOrd: obj) -> (let eqCoproduct3 = (sharpurs_apply (box (eqCoproduct2)) (box ((sharpurs_apply (box ((Map.find "Eq0" (unbox<Map<string, obj>> (dictOrd))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Ord_Ordusd_Dict)) (box ((Map.add "compare" (box ((sharpurs_apply (box (compare1)) (box (dictOrd))))) (Map.add "Eq0" (box ((fun (_: obj) -> eqCoproduct3))) Map.empty)))))))))))

let Data_Functor_Coproduct_coproduct  = (fun (v: obj) -> (fun (v1: obj) -> (fun (v2: obj) -> (match (((unbox (v)), (unbox (v1)), (unbox (v2)))) with | (f, _, Data_Either_Leftusd_Ctor(a)) -> (box ((sharpurs_apply (box (f)) (box (a))))) | (_, g, Data_Either_Rightusd_Ctor(b)) -> (box ((sharpurs_apply (box (g)) (box (b)))))))))

let Data_Functor_Coproduct_extendCoproduct  = (fun (dictExtend: obj) -> (let extend = (sharpurs_apply (box (Control_Extend_extend)) (box (dictExtend))) in let functorCoproduct1 = (sharpurs_apply (box (Data_Functor_Coproduct_functorCoproduct)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (dictExtend))))) (box (Prim_undefined)))))) in (fun (dictExtend1: obj) -> (let extend1 = (sharpurs_apply (box (Control_Extend_extend)) (box (dictExtend1))) in let functorCoproduct2 = (sharpurs_apply (box (functorCoproduct1)) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> (dictExtend1))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Control_Extend_Extendusd_Dict)) (box ((Map.add "extend" (box ((fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Coproduct_compose)) (box (Data_Functor_Coproduct_Coproduct))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Coproduct_coproduct)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Coproduct_compose)) (box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1))))))))) (box ((sharpurs_apply (box (extend)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Coproduct_compose)) (box (f))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Coproduct_compose)) (box (Data_Functor_Coproduct_Coproduct))))) (box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1))))))))))))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Coproduct_compose)) (box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1))))))))) (box ((sharpurs_apply (box (extend1)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Coproduct_compose)) (box (f))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Coproduct_compose)) (box (Data_Functor_Coproduct_Coproduct))))) (box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1))))))))))))))))))))))))) (Map.add "Functor0" (box ((fun (_: obj) -> functorCoproduct2))) Map.empty)))))))))

let Data_Functor_Coproduct_comonadCoproduct  = (fun (dictComonad: obj) -> (let extract = (sharpurs_apply (box (Control_Comonad_extract)) (box (dictComonad))) in let extendCoproduct1 = (sharpurs_apply (box (Data_Functor_Coproduct_extendCoproduct)) (box ((sharpurs_apply (box ((Map.find "Extend0" (unbox<Map<string, obj>> (dictComonad))))) (box (Prim_undefined)))))) in (fun (dictComonad1: obj) -> (let extendCoproduct2 = (sharpurs_apply (box (extendCoproduct1)) (box ((sharpurs_apply (box ((Map.find "Extend0" (unbox<Map<string, obj>> (dictComonad1))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Control_Comonad_Comonadusd_Dict)) (box ((Map.add "extract" (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Coproduct_coproduct)) (box (extract))))) (box ((sharpurs_apply (box (Control_Comonad_extract)) (box (dictComonad1)))))))) (Map.add "Extend0" (box ((fun (_: obj) -> extendCoproduct2))) Map.empty)))))))))

let Data_Functor_Coproduct_bihoistCoproduct  = (fun (natF: obj) -> (fun (natG: obj) -> (fun (v: obj) -> (match (((unbox (natF)), (unbox (natG)), (unbox (v)))) with | (natF1, natG1, e) -> (box ((sharpurs_apply (box (Data_Functor_Coproduct_Coproduct)) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Data_Functor_Coproduct_bimap)) (box (natF1))))) (box (natG1))))) (box (e))))))))))))
