[<AutoOpen>]
module PureScript_Effect_Uncurried

open System
open System.Collections.Generic

module Effect_Uncurried_FFI =
    let mkEffectFn1 _ = undefined
    let mkEffectFn2 _ = undefined
    let mkEffectFn3 _ = undefined
    let mkEffectFn4 _ = undefined
    let mkEffectFn5 _ = undefined
    let mkEffectFn6 _ = undefined
    let mkEffectFn7 _ = undefined
    let mkEffectFn8 _ = undefined
    let mkEffectFn9 _ = undefined
    let mkEffectFn10 _ = undefined
    let runEffectFn1 _ _ = undefined
    let runEffectFn2 _ _ _ = undefined
    let runEffectFn3 _ _ _ _ = undefined
    let runEffectFn4 _ _ _ _ _ = undefined
    let runEffectFn5 _ _ _ _ _ _ = undefined
    let runEffectFn6 _ _ _ _ _ _ _ = undefined
    let runEffectFn7 _ _ _ _ _ _ _ _ = undefined
    let runEffectFn8 _ _ _ _ _ _ _ _ _ = undefined
    let runEffectFn9 _ _ _ _ _ _ _ _ _ _ = undefined
    let runEffectFn10 _ _ _ _ _ _ _ _ _ _ _ = undefined
    

let Effect_Uncurried_mkEffectFn1 = box (fun (arg0: obj) -> box (Effect_Uncurried_FFI.``mkEffectFn1`` (unbox arg0)))
let Effect_Uncurried_mkEffectFn2 = box (fun (arg0: obj) -> box (Effect_Uncurried_FFI.``mkEffectFn2`` (unbox arg0)))
let Effect_Uncurried_mkEffectFn3 = box (fun (arg0: obj) -> box (Effect_Uncurried_FFI.``mkEffectFn3`` (unbox arg0)))
let Effect_Uncurried_mkEffectFn4 = box (fun (arg0: obj) -> box (Effect_Uncurried_FFI.``mkEffectFn4`` (unbox arg0)))
let Effect_Uncurried_mkEffectFn5 = box (fun (arg0: obj) -> box (Effect_Uncurried_FFI.``mkEffectFn5`` (unbox arg0)))
let Effect_Uncurried_mkEffectFn6 = box (fun (arg0: obj) -> box (Effect_Uncurried_FFI.``mkEffectFn6`` (unbox arg0)))
let Effect_Uncurried_mkEffectFn7 = box (fun (arg0: obj) -> box (Effect_Uncurried_FFI.``mkEffectFn7`` (unbox arg0)))
let Effect_Uncurried_mkEffectFn8 = box (fun (arg0: obj) -> box (Effect_Uncurried_FFI.``mkEffectFn8`` (unbox arg0)))
let Effect_Uncurried_mkEffectFn9 = box (fun (arg0: obj) -> box (Effect_Uncurried_FFI.``mkEffectFn9`` (unbox arg0)))
let Effect_Uncurried_mkEffectFn10 = box (fun (arg0: obj) -> box (Effect_Uncurried_FFI.``mkEffectFn10`` (unbox arg0)))
let Effect_Uncurried_runEffectFn1 = box (fun (arg0: obj) -> box (fun (arg1: obj) -> box (Effect_Uncurried_FFI.``runEffectFn1`` (unbox arg0) (unbox arg1))))
let Effect_Uncurried_runEffectFn2 = box (fun (arg0: obj) -> box (fun (arg1: obj) -> box (fun (arg2: obj) -> box (Effect_Uncurried_FFI.``runEffectFn2`` (unbox arg0) (unbox arg1) (unbox arg2)))))
let Effect_Uncurried_runEffectFn3 = box (fun (arg0: obj) -> box (fun (arg1: obj) -> box (fun (arg2: obj) -> box (fun (arg3: obj) -> box (Effect_Uncurried_FFI.``runEffectFn3`` (unbox arg0) (unbox arg1) (unbox arg2) (unbox arg3))))))
let Effect_Uncurried_runEffectFn4 = box (fun (arg0: obj) -> box (fun (arg1: obj) -> box (fun (arg2: obj) -> box (fun (arg3: obj) -> box (fun (arg4: obj) -> box (Effect_Uncurried_FFI.``runEffectFn4`` (unbox arg0) (unbox arg1) (unbox arg2) (unbox arg3) (unbox arg4)))))))
let Effect_Uncurried_runEffectFn5 = box (fun (arg0: obj) -> box (fun (arg1: obj) -> box (fun (arg2: obj) -> box (fun (arg3: obj) -> box (fun (arg4: obj) -> box (fun (arg5: obj) -> box (Effect_Uncurried_FFI.``runEffectFn5`` (unbox arg0) (unbox arg1) (unbox arg2) (unbox arg3) (unbox arg4) (unbox arg5))))))))
let Effect_Uncurried_runEffectFn6 = box (fun (arg0: obj) -> box (fun (arg1: obj) -> box (fun (arg2: obj) -> box (fun (arg3: obj) -> box (fun (arg4: obj) -> box (fun (arg5: obj) -> box (fun (arg6: obj) -> box (Effect_Uncurried_FFI.``runEffectFn6`` (unbox arg0) (unbox arg1) (unbox arg2) (unbox arg3) (unbox arg4) (unbox arg5) (unbox arg6)))))))))
let Effect_Uncurried_runEffectFn7 = box (fun (arg0: obj) -> box (fun (arg1: obj) -> box (fun (arg2: obj) -> box (fun (arg3: obj) -> box (fun (arg4: obj) -> box (fun (arg5: obj) -> box (fun (arg6: obj) -> box (fun (arg7: obj) -> box (Effect_Uncurried_FFI.``runEffectFn7`` (unbox arg0) (unbox arg1) (unbox arg2) (unbox arg3) (unbox arg4) (unbox arg5) (unbox arg6) (unbox arg7))))))))))
let Effect_Uncurried_runEffectFn8 = box (fun (arg0: obj) -> box (fun (arg1: obj) -> box (fun (arg2: obj) -> box (fun (arg3: obj) -> box (fun (arg4: obj) -> box (fun (arg5: obj) -> box (fun (arg6: obj) -> box (fun (arg7: obj) -> box (fun (arg8: obj) -> box (Effect_Uncurried_FFI.``runEffectFn8`` (unbox arg0) (unbox arg1) (unbox arg2) (unbox arg3) (unbox arg4) (unbox arg5) (unbox arg6) (unbox arg7) (unbox arg8)))))))))))
let Effect_Uncurried_runEffectFn9 = box (fun (arg0: obj) -> box (fun (arg1: obj) -> box (fun (arg2: obj) -> box (fun (arg3: obj) -> box (fun (arg4: obj) -> box (fun (arg5: obj) -> box (fun (arg6: obj) -> box (fun (arg7: obj) -> box (fun (arg8: obj) -> box (fun (arg9: obj) -> box (Effect_Uncurried_FFI.``runEffectFn9`` (unbox arg0) (unbox arg1) (unbox arg2) (unbox arg3) (unbox arg4) (unbox arg5) (unbox arg6) (unbox arg7) (unbox arg8) (unbox arg9))))))))))))
let Effect_Uncurried_runEffectFn10 = box (fun (arg0: obj) -> box (fun (arg1: obj) -> box (fun (arg2: obj) -> box (fun (arg3: obj) -> box (fun (arg4: obj) -> box (fun (arg5: obj) -> box (fun (arg6: obj) -> box (fun (arg7: obj) -> box (fun (arg8: obj) -> box (fun (arg9: obj) -> box (fun (arg10: obj) -> box (Effect_Uncurried_FFI.``runEffectFn10`` (unbox arg0) (unbox arg1) (unbox arg2) (unbox arg3) (unbox arg4) (unbox arg5) (unbox arg6) (unbox arg7) (unbox arg8) (unbox arg9) (unbox arg10)))))))))))))


let Effect_Uncurried_semigroupEffectFn9  = (fun (dictSemigroup: obj) -> (let append = (sharpurs_apply (box (Data_Semigroup_append)) (box ((sharpurs_apply (box (Effect_semigroupEffect)) (box (dictSemigroup)))))) in (sharpurs_apply (box (Data_Semigroup_Semigroupusd_Dict)) (box ((Map.add "append" (box ((fun (f1: obj) -> (fun (f2: obj) -> (sharpurs_apply (box (Effect_Uncurried_mkEffectFn9)) (box ((fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (fun (g: obj) -> (fun (h: obj) -> (fun (i: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (append)) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Effect_Uncurried_runEffectFn9)) (box (f1))))) (box (a))))) (box (b))))) (box (c))))) (box (d))))) (box (e))))) (box (f))))) (box (g))))) (box (h))))) (box (i)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Effect_Uncurried_runEffectFn9)) (box (f2))))) (box (a))))) (box (b))))) (box (c))))) (box (d))))) (box (e))))) (box (f))))) (box (g))))) (box (h))))) (box (i)))))))))))))))))))))) Map.empty))))))

let Effect_Uncurried_semigroupEffectFn8  = (fun (dictSemigroup: obj) -> (let append = (sharpurs_apply (box (Data_Semigroup_append)) (box ((sharpurs_apply (box (Effect_semigroupEffect)) (box (dictSemigroup)))))) in (sharpurs_apply (box (Data_Semigroup_Semigroupusd_Dict)) (box ((Map.add "append" (box ((fun (f1: obj) -> (fun (f2: obj) -> (sharpurs_apply (box (Effect_Uncurried_mkEffectFn8)) (box ((fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (fun (g: obj) -> (fun (h: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (append)) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Effect_Uncurried_runEffectFn8)) (box (f1))))) (box (a))))) (box (b))))) (box (c))))) (box (d))))) (box (e))))) (box (f))))) (box (g))))) (box (h)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Effect_Uncurried_runEffectFn8)) (box (f2))))) (box (a))))) (box (b))))) (box (c))))) (box (d))))) (box (e))))) (box (f))))) (box (g))))) (box (h))))))))))))))))))))) Map.empty))))))

let Effect_Uncurried_semigroupEffectFn7  = (fun (dictSemigroup: obj) -> (let append = (sharpurs_apply (box (Data_Semigroup_append)) (box ((sharpurs_apply (box (Effect_semigroupEffect)) (box (dictSemigroup)))))) in (sharpurs_apply (box (Data_Semigroup_Semigroupusd_Dict)) (box ((Map.add "append" (box ((fun (f1: obj) -> (fun (f2: obj) -> (sharpurs_apply (box (Effect_Uncurried_mkEffectFn7)) (box ((fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (fun (g: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (append)) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Effect_Uncurried_runEffectFn7)) (box (f1))))) (box (a))))) (box (b))))) (box (c))))) (box (d))))) (box (e))))) (box (f))))) (box (g)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Effect_Uncurried_runEffectFn7)) (box (f2))))) (box (a))))) (box (b))))) (box (c))))) (box (d))))) (box (e))))) (box (f))))) (box (g)))))))))))))))))))) Map.empty))))))

let Effect_Uncurried_semigroupEffectFn6  = (fun (dictSemigroup: obj) -> (let append = (sharpurs_apply (box (Data_Semigroup_append)) (box ((sharpurs_apply (box (Effect_semigroupEffect)) (box (dictSemigroup)))))) in (sharpurs_apply (box (Data_Semigroup_Semigroupusd_Dict)) (box ((Map.add "append" (box ((fun (f1: obj) -> (fun (f2: obj) -> (sharpurs_apply (box (Effect_Uncurried_mkEffectFn6)) (box ((fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (append)) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Effect_Uncurried_runEffectFn6)) (box (f1))))) (box (a))))) (box (b))))) (box (c))))) (box (d))))) (box (e))))) (box (f)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Effect_Uncurried_runEffectFn6)) (box (f2))))) (box (a))))) (box (b))))) (box (c))))) (box (d))))) (box (e))))) (box (f))))))))))))))))))) Map.empty))))))

let Effect_Uncurried_semigroupEffectFn5  = (fun (dictSemigroup: obj) -> (let append = (sharpurs_apply (box (Data_Semigroup_append)) (box ((sharpurs_apply (box (Effect_semigroupEffect)) (box (dictSemigroup)))))) in (sharpurs_apply (box (Data_Semigroup_Semigroupusd_Dict)) (box ((Map.add "append" (box ((fun (f1: obj) -> (fun (f2: obj) -> (sharpurs_apply (box (Effect_Uncurried_mkEffectFn5)) (box ((fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (append)) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Effect_Uncurried_runEffectFn5)) (box (f1))))) (box (a))))) (box (b))))) (box (c))))) (box (d))))) (box (e)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Effect_Uncurried_runEffectFn5)) (box (f2))))) (box (a))))) (box (b))))) (box (c))))) (box (d))))) (box (e)))))))))))))))))) Map.empty))))))

let Effect_Uncurried_semigroupEffectFn4  = (fun (dictSemigroup: obj) -> (let append = (sharpurs_apply (box (Data_Semigroup_append)) (box ((sharpurs_apply (box (Effect_semigroupEffect)) (box (dictSemigroup)))))) in (sharpurs_apply (box (Data_Semigroup_Semigroupusd_Dict)) (box ((Map.add "append" (box ((fun (f1: obj) -> (fun (f2: obj) -> (sharpurs_apply (box (Effect_Uncurried_mkEffectFn4)) (box ((fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (append)) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Effect_Uncurried_runEffectFn4)) (box (f1))))) (box (a))))) (box (b))))) (box (c))))) (box (d)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Effect_Uncurried_runEffectFn4)) (box (f2))))) (box (a))))) (box (b))))) (box (c))))) (box (d))))))))))))))))) Map.empty))))))

let Effect_Uncurried_semigroupEffectFn3  = (fun (dictSemigroup: obj) -> (let append = (sharpurs_apply (box (Data_Semigroup_append)) (box ((sharpurs_apply (box (Effect_semigroupEffect)) (box (dictSemigroup)))))) in (sharpurs_apply (box (Data_Semigroup_Semigroupusd_Dict)) (box ((Map.add "append" (box ((fun (f1: obj) -> (fun (f2: obj) -> (sharpurs_apply (box (Effect_Uncurried_mkEffectFn3)) (box ((fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (append)) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Effect_Uncurried_runEffectFn3)) (box (f1))))) (box (a))))) (box (b))))) (box (c)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Effect_Uncurried_runEffectFn3)) (box (f2))))) (box (a))))) (box (b))))) (box (c)))))))))))))))) Map.empty))))))

let Effect_Uncurried_semigroupEffectFn2  = (fun (dictSemigroup: obj) -> (let append = (sharpurs_apply (box (Data_Semigroup_append)) (box ((sharpurs_apply (box (Effect_semigroupEffect)) (box (dictSemigroup)))))) in (sharpurs_apply (box (Data_Semigroup_Semigroupusd_Dict)) (box ((Map.add "append" (box ((fun (f1: obj) -> (fun (f2: obj) -> (sharpurs_apply (box (Effect_Uncurried_mkEffectFn2)) (box ((fun (a: obj) -> (fun (b: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (append)) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Effect_Uncurried_runEffectFn2)) (box (f1))))) (box (a))))) (box (b)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Effect_Uncurried_runEffectFn2)) (box (f2))))) (box (a))))) (box (b))))))))))))))) Map.empty))))))

let Effect_Uncurried_semigroupEffectFn10  = (fun (dictSemigroup: obj) -> (let append = (sharpurs_apply (box (Data_Semigroup_append)) (box ((sharpurs_apply (box (Effect_semigroupEffect)) (box (dictSemigroup)))))) in (sharpurs_apply (box (Data_Semigroup_Semigroupusd_Dict)) (box ((Map.add "append" (box ((fun (f1: obj) -> (fun (f2: obj) -> (sharpurs_apply (box (Effect_Uncurried_mkEffectFn10)) (box ((fun (a: obj) -> (fun (b: obj) -> (fun (c: obj) -> (fun (d: obj) -> (fun (e: obj) -> (fun (f: obj) -> (fun (g: obj) -> (fun (h: obj) -> (fun (i: obj) -> (fun (j: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (append)) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Effect_Uncurried_runEffectFn10)) (box (f1))))) (box (a))))) (box (b))))) (box (c))))) (box (d))))) (box (e))))) (box (f))))) (box (g))))) (box (h))))) (box (i))))) (box (j)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box (Effect_Uncurried_runEffectFn10)) (box (f2))))) (box (a))))) (box (b))))) (box (c))))) (box (d))))) (box (e))))) (box (f))))) (box (g))))) (box (h))))) (box (i))))) (box (j))))))))))))))))))))))) Map.empty))))))

let Effect_Uncurried_semigroupEffectFn1  = (fun (dictSemigroup: obj) -> (let append = (sharpurs_apply (box (Data_Semigroup_append)) (box ((sharpurs_apply (box (Effect_semigroupEffect)) (box (dictSemigroup)))))) in (sharpurs_apply (box (Data_Semigroup_Semigroupusd_Dict)) (box ((Map.add "append" (box ((fun (f1: obj) -> (fun (f2: obj) -> (sharpurs_apply (box (Effect_Uncurried_mkEffectFn1)) (box ((fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box (append)) (box ((sharpurs_apply (box ((sharpurs_apply (box (Effect_Uncurried_runEffectFn1)) (box (f1))))) (box (a)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box (Effect_Uncurried_runEffectFn1)) (box (f2))))) (box (a)))))))))))))) Map.empty))))))

let Effect_Uncurried_monoidEffectFn9  = (fun (dictMonoid: obj) -> (let mempty = (sharpurs_apply (box (Data_Monoid_mempty)) (box ((sharpurs_apply (box (Effect_monoidEffect)) (box (dictMonoid)))))) in let semigroupEffectFn91 = (sharpurs_apply (box (Effect_Uncurried_semigroupEffectFn9)) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> (dictMonoid))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Monoid_Monoidusd_Dict)) (box ((Map.add "mempty" (box ((sharpurs_apply (box (Effect_Uncurried_mkEffectFn9)) (box ((fun (v: obj) -> (fun (v1: obj) -> (fun (v2: obj) -> (fun (v3: obj) -> (fun (v4: obj) -> (fun (v5: obj) -> (fun (v6: obj) -> (fun (v7: obj) -> (fun (v8: obj) -> mempty)))))))))))))) (Map.add "Semigroup0" (box ((fun (_: obj) -> semigroupEffectFn91))) Map.empty)))))))

let Effect_Uncurried_monoidEffectFn8  = (fun (dictMonoid: obj) -> (let mempty = (sharpurs_apply (box (Data_Monoid_mempty)) (box ((sharpurs_apply (box (Effect_monoidEffect)) (box (dictMonoid)))))) in let semigroupEffectFn81 = (sharpurs_apply (box (Effect_Uncurried_semigroupEffectFn8)) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> (dictMonoid))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Monoid_Monoidusd_Dict)) (box ((Map.add "mempty" (box ((sharpurs_apply (box (Effect_Uncurried_mkEffectFn8)) (box ((fun (v: obj) -> (fun (v1: obj) -> (fun (v2: obj) -> (fun (v3: obj) -> (fun (v4: obj) -> (fun (v5: obj) -> (fun (v6: obj) -> (fun (v7: obj) -> mempty))))))))))))) (Map.add "Semigroup0" (box ((fun (_: obj) -> semigroupEffectFn81))) Map.empty)))))))

let Effect_Uncurried_monoidEffectFn7  = (fun (dictMonoid: obj) -> (let mempty = (sharpurs_apply (box (Data_Monoid_mempty)) (box ((sharpurs_apply (box (Effect_monoidEffect)) (box (dictMonoid)))))) in let semigroupEffectFn71 = (sharpurs_apply (box (Effect_Uncurried_semigroupEffectFn7)) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> (dictMonoid))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Monoid_Monoidusd_Dict)) (box ((Map.add "mempty" (box ((sharpurs_apply (box (Effect_Uncurried_mkEffectFn7)) (box ((fun (v: obj) -> (fun (v1: obj) -> (fun (v2: obj) -> (fun (v3: obj) -> (fun (v4: obj) -> (fun (v5: obj) -> (fun (v6: obj) -> mempty)))))))))))) (Map.add "Semigroup0" (box ((fun (_: obj) -> semigroupEffectFn71))) Map.empty)))))))

let Effect_Uncurried_monoidEffectFn6  = (fun (dictMonoid: obj) -> (let mempty = (sharpurs_apply (box (Data_Monoid_mempty)) (box ((sharpurs_apply (box (Effect_monoidEffect)) (box (dictMonoid)))))) in let semigroupEffectFn61 = (sharpurs_apply (box (Effect_Uncurried_semigroupEffectFn6)) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> (dictMonoid))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Monoid_Monoidusd_Dict)) (box ((Map.add "mempty" (box ((sharpurs_apply (box (Effect_Uncurried_mkEffectFn6)) (box ((fun (v: obj) -> (fun (v1: obj) -> (fun (v2: obj) -> (fun (v3: obj) -> (fun (v4: obj) -> (fun (v5: obj) -> mempty))))))))))) (Map.add "Semigroup0" (box ((fun (_: obj) -> semigroupEffectFn61))) Map.empty)))))))

let Effect_Uncurried_monoidEffectFn5  = (fun (dictMonoid: obj) -> (let mempty = (sharpurs_apply (box (Data_Monoid_mempty)) (box ((sharpurs_apply (box (Effect_monoidEffect)) (box (dictMonoid)))))) in let semigroupEffectFn51 = (sharpurs_apply (box (Effect_Uncurried_semigroupEffectFn5)) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> (dictMonoid))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Monoid_Monoidusd_Dict)) (box ((Map.add "mempty" (box ((sharpurs_apply (box (Effect_Uncurried_mkEffectFn5)) (box ((fun (v: obj) -> (fun (v1: obj) -> (fun (v2: obj) -> (fun (v3: obj) -> (fun (v4: obj) -> mempty)))))))))) (Map.add "Semigroup0" (box ((fun (_: obj) -> semigroupEffectFn51))) Map.empty)))))))

let Effect_Uncurried_monoidEffectFn4  = (fun (dictMonoid: obj) -> (let mempty = (sharpurs_apply (box (Data_Monoid_mempty)) (box ((sharpurs_apply (box (Effect_monoidEffect)) (box (dictMonoid)))))) in let semigroupEffectFn41 = (sharpurs_apply (box (Effect_Uncurried_semigroupEffectFn4)) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> (dictMonoid))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Monoid_Monoidusd_Dict)) (box ((Map.add "mempty" (box ((sharpurs_apply (box (Effect_Uncurried_mkEffectFn4)) (box ((fun (v: obj) -> (fun (v1: obj) -> (fun (v2: obj) -> (fun (v3: obj) -> mempty))))))))) (Map.add "Semigroup0" (box ((fun (_: obj) -> semigroupEffectFn41))) Map.empty)))))))

let Effect_Uncurried_monoidEffectFn3  = (fun (dictMonoid: obj) -> (let mempty = (sharpurs_apply (box (Data_Monoid_mempty)) (box ((sharpurs_apply (box (Effect_monoidEffect)) (box (dictMonoid)))))) in let semigroupEffectFn31 = (sharpurs_apply (box (Effect_Uncurried_semigroupEffectFn3)) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> (dictMonoid))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Monoid_Monoidusd_Dict)) (box ((Map.add "mempty" (box ((sharpurs_apply (box (Effect_Uncurried_mkEffectFn3)) (box ((fun (v: obj) -> (fun (v1: obj) -> (fun (v2: obj) -> mempty)))))))) (Map.add "Semigroup0" (box ((fun (_: obj) -> semigroupEffectFn31))) Map.empty)))))))

let Effect_Uncurried_monoidEffectFn2  = (fun (dictMonoid: obj) -> (let mempty = (sharpurs_apply (box (Data_Monoid_mempty)) (box ((sharpurs_apply (box (Effect_monoidEffect)) (box (dictMonoid)))))) in let semigroupEffectFn21 = (sharpurs_apply (box (Effect_Uncurried_semigroupEffectFn2)) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> (dictMonoid))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Monoid_Monoidusd_Dict)) (box ((Map.add "mempty" (box ((sharpurs_apply (box (Effect_Uncurried_mkEffectFn2)) (box ((fun (v: obj) -> (fun (v1: obj) -> mempty))))))) (Map.add "Semigroup0" (box ((fun (_: obj) -> semigroupEffectFn21))) Map.empty)))))))

let Effect_Uncurried_monoidEffectFn10  = (fun (dictMonoid: obj) -> (let mempty = (sharpurs_apply (box (Data_Monoid_mempty)) (box ((sharpurs_apply (box (Effect_monoidEffect)) (box (dictMonoid)))))) in let semigroupEffectFn101 = (sharpurs_apply (box (Effect_Uncurried_semigroupEffectFn10)) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> (dictMonoid))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Monoid_Monoidusd_Dict)) (box ((Map.add "mempty" (box ((sharpurs_apply (box (Effect_Uncurried_mkEffectFn10)) (box ((fun (v: obj) -> (fun (v1: obj) -> (fun (v2: obj) -> (fun (v3: obj) -> (fun (v4: obj) -> (fun (v5: obj) -> (fun (v6: obj) -> (fun (v7: obj) -> (fun (v8: obj) -> (fun (v9: obj) -> mempty))))))))))))))) (Map.add "Semigroup0" (box ((fun (_: obj) -> semigroupEffectFn101))) Map.empty)))))))

let Effect_Uncurried_monoidEffectFn1  = (fun (dictMonoid: obj) -> (let mempty = (sharpurs_apply (box (Data_Monoid_mempty)) (box ((sharpurs_apply (box (Effect_monoidEffect)) (box (dictMonoid)))))) in let semigroupEffectFn11 = (sharpurs_apply (box (Effect_Uncurried_semigroupEffectFn1)) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> (dictMonoid))))) (box (Prim_undefined)))))) in (sharpurs_apply (box (Data_Monoid_Monoidusd_Dict)) (box ((Map.add "mempty" (box ((sharpurs_apply (box (Effect_Uncurried_mkEffectFn1)) (box ((fun (v: obj) -> mempty)))))) (Map.add "Semigroup0" (box ((fun (_: obj) -> semigroupEffectFn11))) Map.empty)))))))
