<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <WarningsAsErrors>false</WarningsAsErrors>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <OutputPath>bin/csharp/</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Control.Monad.ST.Uncurried.cs" />
    <Compile Include="Data.Array.cs" />
    <Compile Include="Data.Int.Bits.cs" />
    <Compile Include="Data.String.CodePoints.cs" />
    <Compile Include="Data.String.Unsafe.cs" />
    <Compile Include="Data.Unit.cs" />
    <Compile Include="Effect.Unsafe.cs" />
    <Compile Include="Record.Unsafe.cs" />
    <Compile Include="Test.Assert.cs" />
    <Compile Include="Unsafe.Coerce.cs" />
  </ItemGroup>
</Project>
