[<AutoOpen>]
module PureScript_Foreign_Object_Gen

open System
open System.Collections.Generic

let Foreign_Object_Gen_fromFoldable  = (sharpurs_apply (box ((box Foreign_Object_fromFoldable))) (box ((box Data_List_Types_foldableList))))

let Foreign_Object_Gen_genForeignObject  = (box (fun (dictMonadRec: obj) -> (box (fun (dictMonadGen: obj) -> (let Monad0 = (sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadGen)))))) (box ((box Prim_undefined)))) in let Bind1 = (sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box Monad0)))))) (box ((box Prim_undefined)))) in let Bind11 = (sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box Monad0)))))) (box ((box Prim_undefined)))) in let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box Bind11)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined)))) in let Apply0 = (sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box Bind11)))))) (box ((box Prim_undefined)))) in (box (fun (genKey: obj) -> (box (fun (genValue: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Gen_Class_sized))) (box ((box dictMonadGen)))))) (box ((box (fun (size: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Bind1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Gen_Class_chooseInt))) (box ((box dictMonadGen)))))) (box ((box 0)))))) (box ((box size))))))))) (box ((box (fun (newSize: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Gen_Class_resize))) (box ((box dictMonadGen)))))) (box ((sharpurs_apply (box ((box Data_Function_const))) (box ((box newSize)))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box Foreign_Object_Gen_fromFoldable)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Gen_unfoldable))) (box ((box dictMonadRec)))))) (box ((box dictMonadGen)))))) (box ((box Data_List_Types_unfoldableList)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Apply_apply))) (box ((box Apply0)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box Data_Tuple_Tuple)))))) (box ((box genKey))))))))) (box ((box genValue))))))))))))))))))))))))))))))))
